### ISSUE TITLE
[Responsive Navigation] Can't do vertical small screen top bar menu list

### ISSUE THREAD

**Issue by nikola87kg** [zurb/foundation-sites#8028] opened 2016-01-28 11:08 UTC
**How can we reproduce this bug?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**
Can't do vertical small screen top bar menu list
**What happened instead?**
vertical top bar manu in small screen

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment] 2016-01-28 17:15
Can you describe in more detail what you want to create?

**Comment by nikola87kg** [comment] 2016-01-29 09:37
i have dropdown top bar menu on large screen with arrows pointing down and sublist that is under tab. And I want it stays like that. 
But when I insert code from foundation site for responsive design dropdown menu, small-screen is OK, but large-screen is problem. Arrows now point to the right and sublist jumpout on right side of tab, what I don't want. I want it to stay under tabs, not on right side. 

**(dropdown menu vertical medium-horizontal)**

That was easy with foundation 5, but with foundation 6 I can't do that :/

**Comment by colin-marshall** [comment] 2016-01-29 21:13
Duplicate: https://github.com/zurb/foundation-sites/issues/7978

**Comment by gakimball** [comment] 2016-02-01 21:46
Indeed, duplicate of #7978

**Closed by gakimball** 2016-02-01 21:46 UTC
Labels: awaiting reply, scss
