### ISSUE TITLE
[Sticky] Magellan links is not scrolling to anchored section in 6.5.0-rc.1

### ISSUE THREAD

**Issue by mbmk14** [zurb/foundation-sites#11384] opened 2018-07-05 10:57 UTC
## Expected Behavior
Magellan link should scroll to that section on click

## Current Behavior
but its not working

## Possible Solution
its working on last release

How to reproduce:
1. Go to > https://foundation.zurb.com/sites/docs/sticky.html#javascript-reference
2. try Clicking other Sticky Navigation e.g. "Sticky Navigation", "Stick to Bottom"
3. page is not taking to that section

## Your Environment

- Foundation version(s) used: Latest (6.5.0-rc.1)
- Browser(s) name and version(s): Firefox, Chrome
- Operating System and version (desktop or mobile): Mac
- Link to your project:

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by DanielRuf** [comment] 2018-07-05 11:36
Duplicate of https://github.com/zurb/foundation-sites/issues/11355

**Closed by DanielRuf** 2018-07-05 11:36 UTC
