### ISSUE TITLE
[Dropdown] Code does not work out of the box

### ISSUE THREAD

**Issue by stljeff1** [zurb/foundation-sites#9400] opened 2016-11-22 18:28 UTC
The code you provide should work on my test web page as is. please provide more specific instructions on how to make this work OUT OF THE BOX

1. copy code from Foundation Docs onto test webpage containing all necessary Foundation assets
2. View webpage

**What did you expect to happen?**
for it to work as described in the documentation.

**What happened instead?**
absolutely nothing. (this happens all the time, btw)

**Test case:**

Use your own code.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by kball** [comment] 2016-11-22 18:35
So... it does work (you can test by pasting in either of those pens from the template), so I'm guessing that something else is going wrong.

Are you initializing the foundation javascript using

```
$(document).foundation()
```

Perhaps you have an example somewhere that you can point us to to help you debug?

**Comment by stljeff1** [comment] 2016-11-22 18:38
its from your own documentation. Yes I am calling that

**Comment by kball** [comment] 2016-11-22 18:40
I can tell you're frustrated, I'm sorry its not working, however saying "Its from your own documentation" isn't helping me solving your problem because it is working for me both in the documentation and in various examples and codepens copying and pasting.  If you could upload the *exact example* as you have implemented it either in a zipfile here or someplace online where I can take a look, I'd be able to be more helpful

**Comment by stljeff1** [comment] 2016-11-22 18:42
Can you show me a code pen that shows the basic code that I need to make this to run?

**Comment by kball** [comment] 2016-11-22 18:43
http://codepen.io/kball/pen/xRdOEz

**Comment by stljeff1** [comment] 2016-11-22 18:50
Thank you very much. That helps. I figured out that someone was loading the date picker plugin despite loading foundation.min.js.

Sorry for the frustration, but i always get caught with a frivolous bug like this when implementing foundation widgets, and I often find it difficult to debug by referencing the foundation docs

**Comment by kball** [comment] 2016-11-22 18:53
@stljeff1 I'm glad that resolved it for you - can you help me understand what was the insight that finally caused the breakthrough, so we can try to reproduce it in the docs?  Or do you think having links to codepens with isolated examples from each of the docs pages would be helpful?

**Comment by stljeff1** [comment] 2016-11-22 19:01
[This link](http://stackoverflow.com/questions/22850510/foundation-zurb-dropdown-not-working) and the [Foundation Docs](http://foundation.zurb.com/sites/docs/javascript.html), along with the stripped down example you provided, allowed my to realize that including other widgets (like the Foundation DatePicker) will break when using the foundation.min.js include. With that knowledge, I discovered that I was indeed including the Datepicker include by mistake. Once i took that out, it worked.

**Comment by kball** [comment] 2016-11-22 19:06
Ah interesting... it looks like the Foundation DatePicker has not been updated for Foundation 6 (see https://github.com/najlepsiwebdesigner/foundation-datepicker/issues/154)... :( It would be nice if they called that out in their README.  If I have some time in the next week or two I'll see if I can put together a PR for them to bring it up for Foundation 6.

In the meanwhile, I'm going to close this, and take a note for us to add more stripped down examples to our docs via codepen or something similar.

**Closed by kball** 2016-11-22 19:06 UTC
