### ISSUE TITLE
Page with 60 Tooltips - slow to display on Chrome

### ISSUE THREAD

**Issue by RWAP** [zurb/foundation-sites#11777] opened 2019-06-11 16:21 UTC
When viewing my website in Chrome, there is one page which has about 60 tooltips on it.  Unfortunately, when foundation initialises, it takes several seconds to finish processing the page.  Even worse on Safari (Chrome OSX) the page is completely blank until foundation completes.

Firefox is fine and displays the page rapidly.

From experience on another page where I had a similar issue due to my own javascript, the problem occurs (and is repeatable) if you append elements to the DOM - such as the following code:

```
var $element = $('#element-to-test');
var $c = $element
           .clone()
           .css({display: 'inline', width: 'auto', visibility: 'hidden'})
           .appendTo('body');

if( $c.width() > $element.width() ) {
    // text was truncated. 
    // do what you need to do
}

$c.remove();
```

I guess the problem is caused by foundation adding all of the data-tooltips to the end of the DOM.

Is there a better way around this from a foundation point of view?

**Comment by DanielRuf** [comment] 2019-06-11 17:38
Hi @RWAP 
thanks for filing the issue.

I am closing this as duplicate of https://github.com/zurb/foundation-sites/issues/11062

**Comment by DanielRuf** [comment] 2019-06-11 17:39
> When viewing my website in Chrome, there is one page which has about 60 tooltips on it. Unfortunately, when foundation initialises, it takes several seconds to finish processing the page. Even worse on Safari (Chrome OSX) the page is completely blank until foundation completes.

Quick question where do you load the JS files? In the head or on the very end of the body?

**Closed by DanielRuf** 2019-06-11 17:38 UTC
