### ISSUE TITLE
[Buttons] Can't override background without crash hover background color

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8135] opened 2016-02-11 08:08 UTC
I'm working know with Orbit and i have to override .orbit-previous and .orbit-next button background because the Orbit background is white, but i can't get it.
![seleccion_096](https://cloud.githubusercontent.com/assets/5034215/12971718/213d819c-d06c-11e5-8469-74b143adf45d.png)
![seleccion_097](https://cloud.githubusercontent.com/assets/5034215/12971796/f044d38c-d06c-11e5-9074-1efdf913d388.png)

As you can see, override the background-color for button element do that the background-color hover element will be unseeable.

Is a ugly problem because i can't see the arrows without override background-color's element, but i can't override it because i can't see the background-color hover's element.

**Comment by colin-marshall** [comment] 2016-04-27 23:37
@SalahAdDin I'm closing this issue because we don’t have a reproduceable case to test against. If this is still an issue, please reopen with the info requested here:
https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

**Closed by colin-marshall** 2016-04-27 23:37 UTC
Labels: bug, scss

**Comment by SalahAdDin** [comment] 2016-04-28 02:17
Ok, thanks :+1:
