### ISSUE TITLE
$body-font-color bad value?

### ISSUE THREAD

**Issue by soulcreate** [zurb/foundation-sites#9897] opened 2017-03-25 07:06 UTC
I set in _settings.scss color of text:
```
$body-font-color: #878787;
```
But have error:
```
WARNING: Contrast ratio of #878787 on #ffd5d5 is pretty bad, just 2.7
Backtrace:
	bower_components/foundation-sites-6.3.1/scss/util/_color.scss:75, in function `color-pick-contrast`
	bower_components/foundation-sites-6.3.1/scss/components/_callout.scss:70, in mixin `callout-style`
	bower_components/foundation-sites-6.3.1/scss/components/_callout.scss:94, in mixin `foundation-callout`
	bower_components/foundation-sites-6.3.1/scss/foundation.scss:87, in mixin `foundation-everything`
	app/styles/_settings.scss:89
```
What I do wrong?

**Comment by IamManchanda** [comment] 2017-03-25 12:07
my reply a bit off topic but if you want to use nearby [#878787](http://www.colorhexa.com/878787)
then you should use `$dark-gray` for `$body-font-color` instead which is [#8a8a8a](http://www.colorhexa.com/8a8a8a)

**Comment by Deckluhm** [comment] 2017-03-26 22:41
That's not an error, just a warning. Basically this warning just tells you that the contrast between your font color and your background color isn't high enough for optimal readability.

Unless you can't change colors (e.g. imposed by client), you should care about this warning because it improves accessibility and more generally UX.

**Comment by kball** [comment] 2017-04-06 22:19
Closing this as it is not a bug - a recent PR added the ability to disable this warning as well, see: https://github.com/zurb/foundation-sites/pull/9853

That PR will be in 6.4

**Closed by kball** 2017-04-06 22:19 UTC
