### ISSUE TITLE
Foundation.toggler.js is causing: `TypeError: Cannot read property '0' of undefined` when using ES6 modules

### ISSUE THREAD

**Issue by aaronjpitts** [zurb/foundation-sites#10892] opened 2018-01-29 23:30 UTC
When importing foundation plugins using ES6 modules, foundation.toggler.js is causing: `TypeError: Cannot read property '0' of undefined` if input is undefined on line 55 in js/foundation.toggler.js. This is the simple fix:

```
  if (input) {
    // Allow for a . at the beginning of the string
    this.className = input[0] === '.' ? input.slice(1) : input;
  }
```

**Comment by ncoden** [comment] 2018-01-30 12:37
Hi @aaronjpitts.

Thanks for the issue report and the fix. However I would like to make sure that this fix a correct usage of `Toggler`. Could you please describe your usage case ?

**Comment by aaronjpitts** [comment] 2018-01-30 14:02
Sure, so I am creating a Vue plugin which simple creates directives for all Foundation javascript widgets (https://github.com/aaronjpitts/vf-directives), I am implementing the toggler Vue directive below.

```
import $ from 'jquery'
import { Foundation } from 'foundation-sites/js/foundation.core'
import { Toggler } from 'foundation-sites/js/foundation.toggler'

Foundation.plugin(Toggler, 'Toggler')

export default {
  install (Vue) {
    Vue.directive('toggler', {
      inserted (el) {
        el.vfToggler = new Foundation.Toggler($(el))
      },
      unbind (el) {
        el.vfToggler.destroy()
      }
    })
  }
}
```

**Comment by kball** [comment] 2018-02-03 23:18
I think the fix is not correct, because the use case here is not quite right - toggler as designed is supposed to listen for the toggle event and simply toggle a class. Calling it without a class as an argument should not be valid!

However, I *do* think it should accept that class as an option and not only as a data attribute, which would allow us to wrap it up more nicely in a vue directive

**Comment by DanielRuf** [comment] 2018-04-13 12:59
@ncoden Is this resolved by https://github.com/zurb/foundation-sites/pull/10952 which is merged?

**Comment by ncoden** [comment] 2018-04-13 13:44
Yes, thanks for the bumb.

**Closed by ncoden** 2018-04-13 13:44 UTC
Labels: PR open, Toggler, bug
