### ISSUE TITLE
[Slider] Wrong thumb position at the right

### ISSUE THREAD

**Issue by ArtemZag** [zurb/foundation-sites#7782] opened 2016-01-06 15:42 UTC
**How can we reproduce this bug?**
Just move the slider thumb to the most right

**What did you expect to happen?**
I expect the thumb right border to be on the same line where the slider line ends

**What happened instead?**
The thumb position gets a bit more to right (~10px)

**Test case**
you can use your own page with examples: http://foundation.zurb.com/sites/docs/slider.html

**Comment by andycochran** [comment] 2016-01-06 16:27
Related to #7660.

**Comment by gakimball** [comment] 2016-01-06 17:02
Duplicate of #7660

**Closed by gakimball** 2016-01-06 17:02 UTC

**Comment by ArtemZag** [comment] 2016-01-07 21:00
Thanks, guys :) And sorry for the duplicate.

**Comment by gakimball** [comment] 2016-01-07 21:06
No worries!
