### ISSUE TITLE
Support more or all properties in $header-styles

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#10918] opened 2018-02-06 09:52 UTC
So far $header-styles only uses 'font-size', 'line-height', 'margin-top' and 'margin-bottom'.

It makes probably sense to support more or all properties to prevent duplicate declaration of header styles in more scss files which are not supported [here](
https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_base.scss#L320-L360)

https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L140-L157

https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_base.scss#L320-L360

**Comment by ncoden** [comment] 2018-02-06 15:28
See https://github.com/zurb/foundation-sites/issues/9483 and https://github.com/zurb/foundation-sites/pull/9500.

There was a lot of discussions about the subject, and I don't remember end up agreeing on something. The main problem is that `$header-styles` is a tool to help to quickly create header styles. With too many options or supported properties, it became easier to advise people to create their header styles manually.

**Comment by JeremyEnglert** [comment] 2018-02-12 18:31
Closing this as it is a duplicate of an existing ticket.

I think this is something we should definitely discuss for F7.

**Closed by JeremyEnglert** 2018-02-12 18:31 UTC
Labels: Typography, duplicate, feature request

**Comment by DanielRuf** [comment] 2018-02-12 18:40
Right. I'll subscribe to the other two issues.
