### ISSUE TITLE
[Tooltip] Corner arrow not showing properly

### ISSUE THREAD

**Issue by DaGhostman** [zurb/foundation-sites#8057] opened 2016-02-02 19:25 UTC
I am having an issue with the tooltips not showing correctly, as you can see from the screenshot, the corner which imitates a bubble is not showing correctly.

![this screenshot](https://cloud.githubusercontent.com/assets/2286949/12761050/63f6f090-c9e1-11e5-9f79-0f44b5b9f10a.png)

Here is the relative code:

```
<div class="switch float-left" data-tooltip aria-haspopup="true" title="Toggle the password field making it visible instead of dots">
    <input class="switch-input" id="passwordVisibility" type="checkbox">
    <label class="switch-paddle" for="passwordVisibility">
        <span class="show-for-sr">Toggle Password Visibility</span>
        <span class="switch-active" aria-hidden="true">
            <span class="material-icons">visibility</span>
        </span>
        <span class="switch-inactive" aria-hidden="true" style="color: #1583cc">
            <span class="material-icons">visibility_off</span>
        </span>
    </label>
</div>
```

the container tag is a `div.medium-6.medium-offset-3.columns` without any custom styling.

The issue is present in FireFox 44.0 and  Google Chrome 48.0.2564.97 both running with on Ubuntu 14.04, all is up to date

**Comment by gakimball** [comment] 2016-02-05 00:25
Not able to recreate this. The icons aren't there, but the tooltip works fine:

![image](https://cloud.githubusercontent.com/assets/1142001/12834389/d569047c-cb5b-11e5-9bfd-0ab92787a6d0.png)

We'll need to see any CSS applied to this to figure out what's wrong.

**Comment by DaGhostman** [comment] 2016-02-05 01:07
I was able to isolate the issue! The only way I can get it to show up properly is only when I use the `foundation.css` file instead of `foundation.min.css`.

Foundation version 6.1.2 installed using bower

**Comment by gakimball** [comment] 2016-02-05 23:07
Very interesting. Could you try comparing the two using your browser's web inspector, seeing if there are any differences in the CSS output?

I think the bug is coming from the CSS compressor messing up the `border` in the tooltip pip, which has a particular structure to make the triangle look right.

**Comment by DaGhostman** [comment] 2016-02-08 11:54
Sorry for the delayed response, I'll check that today.

**Comment by DaGhostman** [comment] 2016-03-04 14:08
Sorry again for the delay, some stuff came up. Unfortunately I am not able to identify the problem, myself. 

But it appears that it is related to the compressor as the issue persists when using latest `6.2.0`

**Comment by stephenhowells** [comment] 2016-04-15 17:31
I can confirm that I see the same behavior with the tooltip arrow bug and the minified Foundation css v6.2.1. Using the unminified css seems to fix the problem.

**Comment by tinyfly** [comment] 2016-05-24 19:40
@gakimball I can provide some details.

Here is the working css (un-minified version) for the arrow:

```css
.tooltip::before {
  content: '';
  display: block;
  width: 0;
  height: 0;
  border: inset 0.75rem;
  border-color: transparent transparent #0a0a0a;
  border-bottom-style: solid;
  border-top-width: 0;
  bottom: 100%;
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
  -ms-transform: translateX(-50%);
  transform: translateX(-50%);
}
```

Here is the broken css (minified version):

```css
.tooltip.top:before, .tooltip:before {
  content: '';
  display: block;
  width: 0;
  height: 0;
  border: .75rem inset;
}

.tooltip:before {
  border-color: transparent transparent #0a0a0a;
  border-bottom-style: solid;
  border-top-width: 0;
  bottom: 100%;
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
  transform: translateX(-50%);
}

**Comment by tinyfly** [comment] 2016-05-25 15:42
Okay, I've narrowed it down to one of the cssnano options. Laravel's Elixir uses cssnano which it looks like that is what foundation-sites uses in their build setup too.

Set `mergeRules: false` to get the arrows to show properly once minified.

**Comment by andycochran** [comment] 2016-06-20 17:58
Might this be a JavaScript bug? When the JavaScript changes the inline `display` value of a `.tooltip` on hover, this happens: 

![image](https://cloud.githubusercontent.com/assets/409279/16204373/845491e4-36ec-11e6-90f9-21af61d00899.png)

You can recreate this by inspecting the `.tooltip` in [this codepen](http://codepen.io/andycochran/pen/ezdbOv). When you manually change the inline style's `display` value to anything except `none` (static, block, inline-block, etc.) the border styles change to: 

```css
border: inset 0.75rem;
  border-top-color: initial;
  border-top-style: inset;
  border-top-width: 0.75rem;
  border-right-color: initial;
  border-right-style: inset;
  border-right-width: 0.75rem;
  border-bottom-color: initial;
  border-bottom-style: inset;
  border-bottom-width: 0.75rem;
  border-left-color: initial;
  border-left-style: inset;
  border-left-width: 0.75rem;
  border-image-source: initial;
  border-image-slice: initial;
  border-image-width: initial;
  border-image-outset: initial;
  border-image-repeat: initial;
```

…instead of: 

```css
border: inset 0.75rem;
  border-top-color: transparent;
  border-top-style: inset;
  border-top-width: 0;
  border-right-color: transparent;
  border-right-style: inset;
  border-right-width: 0.75rem;
  border-bottom-color: rgb(10, 10, 10);
  border-bottom-style: solid;
  border-bottom-width: 0.75rem;
  border-left-color: transparent;
  border-left-style: inset;
  border-left-width: 0.75rem;
  border-image-source: initial;
  border-image-slice: initial;
  border-image-width: initial;
  border-image-outset: initial;
  border-image-repeat: initial;
```
So, the styles are right, until you hover.

**Comment by Jflem1290** [comment] 2016-07-24 19:36
@tinyfly I agree, the issue seems to have to do with the CSS compressor [CSSnano](http://cssnano.co/). It seems to be a know issue in their community with CSS merging after compression. [Merge Rule Issues](https://github.com/ben-eb/postcss-merge-rules/issues), along with
[cssnano issue #41](https://github.com/ben-eb/cssnano/issues/41) & [cssnano issue #14]( https://github.com/ben-eb/postcss-merge-rules/issues/14
)

Pulled from [source](https: //github.com/ben-eb/postcss-merge-rules):
    Under Examples - It is explains that "This module will attempt to merge adjacent CSS rules:"
As you can see in this example: 

input
```
.tooltip: before {
    color: blue;
    font-weight: bold;
}

.tooltip.top: before {
    color: blue;
    font-weight: bold;
}
```
output
```
.tooltip: before, .tooltip.top: before {
    color: blue;
    font-weight: bold;
}
```

**Comment by kball** [comment] 2016-08-01 16:56
Nice job hunting that down @Jflem1290.  I see they've made a number of changes attempting to address this, have you checked if the latest version of cssnano resolves this?

If not, perhaps you can submit a PR disabling mergeRules in the build

**Comment by Jflem1290** [comment] 2016-08-02 15:44
@kball, it appears that these issues have been addressed in the later versions v2.0.10 or greater and a "[safe](https://github.com/ben-eb/cssnano/issues/28)" mode (3.0.1) has been created.

Fixed various merge issues by users @11bit & @ben-eb: 
[Pull #22](https://github.com/ben-eb/postcss-merge-rules/pull/22)
[Merging Order](https://github.com/ben-eb/postcss-merge-rules/issues/13), [Overflow properties](https://github.com/ben-eb/cssnano/issues/113), and more which can be found [here](https://github.com/ben-eb/postcss-merge-rules/commit/e14e0f5e340616a331d5d893333eb97aeb37cea8)

Feel free to view the [Changelog](http://cssnano.co/changelog/) for all addressed issues.

**Comment by Jflem1290** [comment] 2016-08-03 18:56
Hey @ tinyfly, I am attempting to address this issue and create a PR for it. I am having some issues finding the mergeRules in the build. Would you be able to help? Thanks!

**Comment by tinyfly** [comment] 2016-08-03 20:22
@Jflem1290 [Here is the line](https://github.com/zurb/foundation-sites/blob/develop/gulp/deploy.js#L73) mergeRules is enabled by default so you'll have to pass in a config object to turn it off.

Not sure exactly how to do it here but try this:
```
.pipe(cssnano({
  mergeRules: false
}))

**Comment by Jflem1290** [comment] 2016-08-03 20:55
@tinyfly Thanks for the response! This is about as far as I got. I'm running into the issue of recompling the foundation.css to the foundation.min.css version to test if this works.

**Comment by Jflem1290** [comment] 2016-08-03 22:00
@tinyfly Thanks for the response. I've managed to make it to the same part, where I'm stuck is:
```
// The Customizer runs this function to generate files it needs
gulp.task('deploy:custom', ['sass:foundation', 'javascript:foundation'], function() {
    gulp.src('./_build/assets/css/foundation.css')
        .pipe(cssnano({
            mergeRules: false
        }))
        .pipe(rename('foundation.min.css'))
        .pipe(gulp.dest('./_build/assets/css'));

    return gulp.src('_build/assets/js/foundation.js')
        .pipe(uglify())
        .pipe(rename('foundation.min.js'))
        .pipe(gulp.dest('./_build/assets/js'));
});
```

From my understanding, this creates a foundation.min.css file in ./_build/assets/css, but I am not seeing this take place.

**Comment by DanielRuf** [comment] 2018-02-17 12:35
What is the current state of this issue?

**Comment by DanielRuf** [comment] 2018-03-09 21:02
Can not reproduce this in the latest release anymore so I'll close it.

Feel free to reopen if this is not the case.

**Closed by DanielRuf** 2018-03-09 21:02 UTC
Labels: Tooltip, bug, javascript, scss
