### ISSUE TITLE
Buttons with disabled class are clickable with 6.2 (not clickable with 6.1)

### ISSUE THREAD

**Issue by EspadaV8** [zurb/foundation-sites#9121] opened 2016-08-18 00:59 UTC
This is probably an issue for the release notes rather than a chance in the SCSS but 6.2 removed the `pointer-events` rule here https://github.com/zurb/foundation-sites/commit/d8810b5466a777997e2882a3f283e430711793eb#diff-cb853bd67d0fa46de7bbe58852679eecL142

Was this intended? The release notes for 6.2 don't mention this change and we've just found that we were relying on the 6.1 functionality when someone accidently deleted a record that should've had the button disabled :-/

**Comment by markadrake** [comment] 2016-09-16 06:11
The philosophical issue with **pointer-events** is that this CSS property actually affects behavior and functionality -vs- style and design.

There is also a UX argument. If `pointer-events:none;` is applied to your disabled elements then you lose the ability to provide meaningful feedback to the user. No interaction whatsoever will trigger from both a CSS or JS perspective. I think this is a major fallback.

Just some follow-up thoughts.

**Comment by EspadaV8** [comment] 2016-09-16 08:28
Yeah. This was more of an FYI in case anyone else has the issue. Not sure what the BC should be  between point releases either. We ended up adding a little bit of JS to disable them correctly.

**Comment by andycochran** [comment] 2016-11-07 21:11
From the docs: 
> The .disabled class is a purely visual style, and won't actually disable a control. For <button> elements, you can add the disabled attribute to disable it. If you want to disable a link, you should add the aria-disabled attribute to mark it as disabled for assistive technology.

I'm gonna close this, as it's not a bug. But if y'all have any thoughts on how to improve on the way that `disabled` works — especially from a UX/a11y perspective — please continue the discussion here.

**Closed by andycochran** 2016-11-07 21:11 UTC

**Comment by EspadaV8** [comment] 2016-11-07 21:42
I mentioned we had some JS that got this to work, thought I'd post it in case anyone else finds it useful

```javascript
(function ($) {
    $(function () {
        $('body').on(
          'click',
          'a[disabled],a.disabled,button[disabled],button.disabled',
          function (e) {
            e.preventDefault();
          }
        );
    });
})(jQuery);
```

It just checks for any `button` or `anchor` with either the `disabled` attribute or `disabled` class and prevents the default actions. It works well for our use case.
