### ISSUE TITLE
[Sticky] "cb is not a function" on _calc run

### ISSUE THREAD

**Issue by piotr-radzikowski** [zurb/foundation-sites#8801] opened 2016-05-18 08:30 UTC
Hi, I have found bug of init _calc on sticky plugin for recalc sticky position.

example of invoke function:
```
$('.sticky').foundation('_calc', true);
```
then in console appear an error:
"Unhandled promise rejection TypeError: cb is not a function"

problem is in sticky plugin code of "_calc" function:
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.sticky.js#L162
function _setSizes is init without callback function and _setSizes function try run missing callback founction which is "Undefined".

Please help, to correct function an argument in _calc or add check for callback is it a function in setSizes.

**Comment by kball** [comment] 2016-09-27 23:12
I'm not able to reproduce this on any of 6.2.1, 6.2.3, or current develop branch... closing as fixed. If it is not fixed for you, please open with more steps to reproduce.

**Comment by pine3ree** [comment] 2016-09-28 00:28
@kball 
Hello, i will trye tomorrow to reproduce, it was long time ago and i have used some fixes in production to avoid javascript console errors.

anyway, i believe that if a function parameter is meant to be called as a function we should always check that it is indeed a function.....

**Comment by pine3ree** [comment] 2016-09-28 00:55
@kball,

i just re-checked (using 6.2.3). If I use a sticky topbar, scroll down to have it fixed to top and then resize di window to mobile range width (small, topbar menu is collapsed to accordion) i get the console error to the line when cb() is called in setSizes. I have not checked latest dev yet.

kind regards
maks

**Comment by pine3ree** [comment] 2016-09-28 01:32
here a codepen

http://codepen.io/anon/pen/xEAEdp

steps to reproduce:

1. start in full width (desktop) browser
2. scroll down a few time to activate sticky
3. resize the browser window to a fondation small width (menu is drilldown)
4. scrollup and click one of the drilldown links, you will get  the console error

**Comment by kball** [comment] 2016-09-28 17:44
Awesome.  Thanks for the repro case, and now I see what we were running into and how your PR was fixing this.

**Comment by kball** [comment] 2016-09-28 17:45
Now fixed.

**Closed by kball** 2016-09-28 17:45 UTC
