### ISSUE TITLE
[Accordion Menu] is-active class on inactive ul not getting removed

### ISSUE THREAD

**Issue by Bakuryu** [zurb/foundation-sites#11578] opened 2018-11-09 17:27 UTC
## What should happen?
When closing a accordion-menu-item via a subtoggler in a accordion-menu, the class `is-active` should be removed from the ul within the list-item.

## What happens instead?
The class `is-active` stays on the element, even if you close the item via a subtoggler.

## Possible Solution

The class is added in the "down" event:
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.accordionMenu.js#L243

The class should be removed in the "up" event, but its missing:
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.accordionMenu.js#L266
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 
You can check out the docs at:
https://foundation.zurb.com/sites/docs/accordion-menu.html#submenu-toggle

Just inspect the `<ul>` and check out the `is-active` class.

Here is a code pen of the same examples from the doc using 6.5.0. Same thing as above inspect the `<ul>` and notice `is-active` class does not disappear when the menu is closed. This includes submenus as well
https://codepen.io/Bakuryu/pen/RqRRNK?editors=1000

## Context

I want to style the active state of menu elements, this is impossible without the proper behavior pattern of the toggled element.

## Your Environment

- Foundation version(s) used: 6.5.0
- Browser(s) name and version(s): All
- Device, Operating System and version: Windows 10

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2018-11-09 18:19
According to https://github.com/zurb/foundation-sites/issues/11383 it should have been fixed in 6.5.0 RC3 and later but it seems it was not fixed there.

A regression or did it not land in the new releases @ncoden?

Also I think we can catch this with a unit test.

**Comment by ncoden** [comment] 2018-11-09 22:46
The patch is still there in v6.5.0:

https://github.com/zurb/foundation-sites/blob/e83e18899b4949a15d1f09dd34c53e201605a507/js/foundation.util.nest.js#L60

I remember having tested this manually. I'll check that again and add some unit tests if necessary. Thank you for the report @Bakuryu @DanielRuf

**Comment by ncoden** [comment] 2018-11-10 20:33
Ok so https://github.com/zurb/foundation-sites/pull/11469 removed the `is-active` class when menus where _destroyed_. But the bug in this issue and #11383 is for when the a submenu is _closed_.

Closing as duplicate and reopening the old issue.

**Comment by ncoden** [comment] 2018-11-10 20:36
Duplicate of https://github.com/zurb/foundation-sites/issues/11383

**Closed** 2018-11-10 20:36 UTC
Labels: Accordion Menu, duplicate
