### ISSUE TITLE
Abide validation of "required" radio buttons

### ISSUE THREAD

**Issue by Visiluna** [zurb/foundation-sites#8537] opened 2016-04-06 18:37 UTC
**How can we reproduce this bug?**

1. Create a form, set up for Abide validation, with a group of radio buttons as demonstrated in the [Foundation 6 for Sites docs](http://foundation.zurb.com/sites/docs/abide.html#abide-demo).
2. Add the "required" attribute to one of the radio buttons
3. In the browser, select one of the radio buttons without the "required" attribute and submit the form.

**What did you expect to happen?**

The form should validate if ANY of the radio buttons are selected.

**What happened instead?**

Abide displays the error that the field is required, even though one of the radio buttons IS selected. The form validates only if the specific radio button with the "required" attribute is selected.

If the "required" attribute is added to all the radio buttons in the group, the form will not validate at all.

**Test case:**

- [CodePen](http://codepen.io/visiluna/pen/yOpBJb)

**Comment by justrhysism** [comment] 2016-04-07 01:05
Even the current version of the Docs exhibits this issue: http://foundation.zurb.com/sites/docs/abide.html 

It seems Foundation really need to automate their testing to capture these types of regressions. This one is a deal-breaker for using Abide on my current project.

**Comment by justrhysism** [comment] 2016-04-07 02:05
Actually, I think this has already been fixed. Duplicate of: https://github.com/zurb/foundation-sites/issues/7196

**Comment by Visiluna** [comment] 2016-04-07 02:26
Except I'm experiencing this on 6.2, the current version.

**Comment by justrhysism** [comment] 2016-04-07 03:47
That fix was done _after_ 6.2 was released. So it's been fixed, but isn't released yet.

**Comment by Visiluna** [comment] 2016-04-07 03:48
Ah, got it. I guess I'll hang tight for now.

**Comment by kball** [comment] 2016-04-07 04:08
Yep.  We're in final testing for 6.2.1 so should be out soon, probably end of this week.

That being said, you have a great point on testing, and we definitely need to get better.  That is a big focus right now;  in the develop branch (and will be there in 6.2.1) we've set up scaffolds for unit tests of all of the plugins, and a number of contributors are working through those now to add tests.  If you'd like to help out, that would be great!  It looks like Abide definitely could use someone taking on the testing:  https://github.com/zurb/foundation-sites/blob/develop/test/javascript/components/abide.js

**Comment by briantan888** [comment] 2016-04-07 04:16
Propose pr #8542 for checkbox and radio group validation, if too late for 6.2.1, will target 6.3

**Comment by justrhysism** [comment] 2016-04-07 05:06
@briantan888 have fed back on your PR #8542.

**Comment by rafibomb** [comment] 2016-04-08 17:41
Looks like this is fixed in testing 6.2.1. Brian Tan also has a PR open for that we'll address for this release. Closing this as it is fixed!

**Closed by rafibomb** 2016-04-08 17:41 UTC
Labels: bug, javascript
