### ISSUE TITLE
Orbit not reinitializing

### ISSUE THREAD

**Issue by olefredrik** [zurb/foundation-sites#8333] opened 2016-03-04 10:52 UTC
**How you can reproduce this bug**
1. Place an orbit slider inside a hidden panel
2. Click a button to toggle the visibility for the panel
3. Verify that the height of the orbit-container and images are set to 0px

**What I expected would happen**
I would expect that there was a method available for reinitalizing the orbit component when toggling the visibility for the panel. 

Would be cool if this:
`$('.orbit').foundation('reflow');`

did not return this:
`Uncaught ReferenceError: We're sorry, 'reflow' is not an available method for this element.(…)`

**What happened instead**
Unless there is a good workaround for this, we're stuck with a third-party slider component, such as the [slick slider](https://github.com/kenwheeler/slick/). Which is a shame, because one of the reasons why we chose to use Foundation, was to have _one_ set of components to deal with.

**Comment by Deckluhm** [comment] 2016-03-04 17:47
I'm not sure I understand this part:
```
3. Verify that the height of the orbit-container and images are set to 0px 
```

But here is an interesting reply from Chris Oyler (@zurbchris) about reflow: http://foundation.zurb.com/forum/posts/36272-foundation-6--reflow

**Comment by olefredrik** [comment] 2016-03-07 12:18
@Deckluhm : What I meant was that the height of the orbit-container and related lists (containing the images) are dynamically set to 0px if it's placed in a hidden panel. 

``$('someSelector').foundation();`` is a good suggestion. Unfortunately it does not work with Orbit.

**Comment by IAmEddieDean** [comment] 2016-03-10 07:28
`Foundation.reInit($('some-orbit'));`

**Comment by travlos** [comment] 2016-05-18 13:07
Did you find any solution for this? I am facing the same problem using orbit slider inside an accordion,

**Comment by ahmetabdi** [comment] 2016-05-18 20:54
Same just trying to call reflow on `document`

**Comment by fmontes** [comment] 2016-05-31 18:53
I'm having the same issue:

I'm creating a Orbit instance dynamically and destroying or init on media queries change... the issue is that I'm getting the following error when I try to reinit the plugin: 
`
foundation.js:5808 Uncaught TypeError: Cannot read property 'filter' of null`

Here is an example of what I'm doing: [http://codepen.io/fmontes/pen/beNeov](http://codepen.io/fmontes/pen/beNeov)

And here is the code:

```
var $orbit = $('.orbit');
var orbitPlugin = new Foundation.Orbit($orbit);

setTimeout(function() {
  orbitPlugin.destroy();
}, 1000)

setTimeout(function() {
  orbitPlugin = new Foundation.Orbit($orbit);
}, 4000)

```
I don't know what else to test, Any ideas?

**Comment by sassanh** [comment] 2016-06-18 02:56
Similar problem here, I need to reflow because my content are loaded dynamically and is subject to change. I don't know why they removed the 'reflow' command in Foundation 6.

**Comment by bc-ian** [comment] 2016-07-14 21:16
Any update on this or anyone running orbit inside of an accordion? Might just switch to slick or something if there isnt a way to get this working with orbit.

**Comment by coreysyms** [comment] 2016-11-11 16:06
Tagging to #9320, this will address as Orbit will get a mutation event to listen for. Look for this in 6.3

**Comment by kball** [comment] 2016-11-18 19:31
Hmm... looking at implementing a mutation observer on Orbit, and running into the challenge that Orbit is mucking with styles of its internal stuff all the time in ways that it doesn't necessarily make sense to react to.  We either need a way to distinguish between "internally" triggered mutations and external, or make the function that is triggered really smart in terms of what it checks on and decides to do.  @coreysyms do you have thoughts on the right way to do this?

**Comment by martinschilliger** [comment] 2016-12-20 12:14
Same problem here with Equalizer inside of an orbit. My workaround was to trigger
```javascript
$(document).trigger("resize");
setTimeout(function(){$(document).trigger("resize")},100);
```
after loading the orbit-slide. It was needed to call `resize` two times…

**Comment by prkirby** [comment] 2017-04-21 00:10
@martinschilliger I'm having the same issue. Although using `.trigger('resize')` on my element for some reason breaks if I try to navigate backwards through the slides or loop to the beginning. Ended up using `Foundation.reInit($myElement)` but you can see it jump, and it's not a good solution.

**Comment by martinschilliger** [comment] 2017-04-21 07:21
Oh, meanwhile I had some problems also and changed it to the following:
```javascript
$(document).on(Foundation.transitionend(), function() {
  $(document).trigger("resize");
});
```
It works quite good now that way. Maybe it will help you also?

**Comment by DanielRuf** [comment] 2017-07-13 12:42
Generally I get `is not an available method for this element` errors when trying to destroy already initialized components. Were there some changes that are not documented?

**Comment by DanielRuf** [comment] 2017-07-13 12:51
Using

```
$(window).on("resize orientationchange", function() {
	$('[data-equalizer]').foundation('_destroy');
	Foundation.reInit($('[data-equalizer]'));
});
```

solved it for us.

**Comment by tobychin** [comment] 2018-02-01 04:31
We ran into this issue, too (a while ago), and got around the errors being thrown by implementing our own function to call when we need to reinit the orbit container. Here's the code we implemented to work around this issue:
```js
function orbitreflow() {
  if ( !$('.orbit-container:visible').length ) { return; }
  Foundation.reInit($('.orbit-container'));
}
```
Hope this helps someone.

**Comment by daigofuji** [comment] 2019-02-26 19:29
Got around t by doing 
```
      $('#myTab').on('change.zf.tabs', function() {
        Foundation.reInit($('.orbit'));
      });
```

**Comment by DanielRuf** [comment] 2019-08-03 16:40
Closing as we have different workarounds. 

Mutation observers are not supported by all browsers that we support so this is also not a solution.

If there is anything that we can do in the core, please let us know.

**Closed by DanielRuf** 2019-08-03 16:40 UTC
Labels: Orbit, javascript, 🐛bug
