### ISSUE TITLE
[DOCS] xy-cell-breakpoints() mixin is documented but doesn't seem to exist.

### ISSUE THREAD

**Issue by farrago** [zurb/foundation-sites#10643] opened 2017-09-13 10:59 UTC
#### How to reproduce this bug:

1. Visit http://foundation.zurb.com/sites/docs/xy-grid.html#responsive-grids
2. See documentation saying:
> We also have a shorthand option for the above which outputs the same CSS:
> ```
> .main-content {
>   @include xy-cell-breakpoints((small: full, medium: 8));
> }
> ```
3. Try and use xy-cell-breakpoints().

#### What should happen:
Mixin should exist, or more likely the documentation should be removed as this mixin isn't detailed in the full mixin section further down.

#### What happened instead:
> Error: no mixin named xy-cell-breakpoints

#### Browser(s) and Device(s) tested on:
gulp-sass @ 2.3.2 => node-sass @ 3.13.0

#### Foundation Version(s) you are using:
Foundation-sites @ 6.4.3
Latest content of website (which shows @ 6.4.2)

#### Test case link:
n/a

**Comment by guci0** [comment] 2017-12-04 17:49
Same. //Error: no mixin named xy-cell-breakpoints

**Comment by featherbelly** [comment] 2018-01-02 01:45
Same...

**Comment by ncoden** [comment] 2018-01-02 07:47
Thanks for the update @featherbelly. I'll check that;

**Comment by ncoden** [comment] 2018-01-02 15:55
Duplicate of https://github.com/zurb/foundation-sites/issues/10276

> Bother I think this made it into the docs at some point but the final PR for this was never merged as we did not get it working with responsive gutters yet (handling responsive gutters with the margin-based grids is unfortunately quite complex).
-- @kball

**Closed** 2018-01-02 15:55 UTC
Labels: duplicate

**Comment by cannanso** [comment] 2018-02-07 02:14
Why is this still in the doc? 
https://foundation.zurb.com/sites/docs/xy-grid.html#responsive-grids

**Comment by guci0** [comment] 2018-02-07 07:58
to remember I think so... Big update is coming?

**Comment by ncoden** [comment] 2018-02-07 09:33
@cannanso The doc is not up to date with master. We'll correct that soon.

**Comment by pklicko** [comment] 2020-01-16 22:39
Soonish...
