### ISSUE TITLE
[Sticky] Sticky navigation jumps to the bottom of the page

### ISSUE THREAD

**Issue by sharifzadesina** [zurb/foundation-sites#11185] opened 2018-04-17 19:08 UTC
Sticky navigation jumps to the bottom of the page when you refresh while the page is scrolled, but as sticky is disabled on small screens, nothing should happen and it should stay on its own place. see the gif:
![screencast from 04-17-2018 11_30_02 pm](https://user-images.githubusercontent.com/15300551/38890974-39fff2b4-4298-11e8-8a18-b25ffc96bd2b.gif)

**Comment by DanielRuf** [comment] 2018-04-17 19:13
Can you provide some codepen and more details about the used Foundation version?

**Comment by sharifzadesina** [comment] 2018-04-17 19:17
@DanielRuf I am using last stable version 6.4.3, If it is really required I can create a codepen, but on the gif you can see all my options. it only happens on small screens when sticky should be disabled when I am adding data-sticky-on="small" which enables sticky also on small screens there is not bug and everything works as it should.

**Comment by mattbag** [comment] 2018-04-18 00:11
I think I have faced this before, and the solution was data-sticky-on="large".

I attach a question: Does anything sticky work on safari with that version?

**Comment by sharifzadesina** [comment] 2018-04-18 09:56
@mattbag I've added data-sticky-on="large", so it is now ok on small screens, but now the bug is on medium screens :)

**Comment by sharifzadesina** [comment] 2018-04-19 20:15
@DanielRuf Guys what we can do about this issue? I think this is really a problem.

**Comment by DanielRuf** [comment] 2018-04-19 20:28
A codepen would be helpful so we have a testcase that we can use to debug and fix this.

**Comment by sharifzadesina** [comment] 2018-04-19 21:54
@DanielRuf There is no need for codepen, your demo also has the problem, here test it:
https://foundation.zurb.com/sites/docs/assets/partials/sticky-nav.html

**Comment by DanielRuf** [comment] 2018-04-19 22:11
https://codepen.io/DanielRuf/pen/vjEwKr

Can nor reproduce it.

**Comment by DanielRuf** [comment] 2018-04-19 22:13
https://github.com/zurb/foundation-sites/commits/develop/js/foundation.sticky.js

**Comment by sharifzadesina** [comment] 2018-04-19 22:13
@DanielRuf Have you checked the demo fron foundation website? also last develop build means 6.4.4-rc1 or develop branch?

**Comment by DanielRuf** [comment] 2018-04-19 22:14
> develop branch

This

**Comment by sharifzadesina** [comment] 2018-04-19 22:16
@DanielRuf ok then, so I think we can have this bug fix on stable 6.4.4 or  6.4.4-rc2.

**Comment by robabel** [comment] 2018-04-20 21:02
I also have this issue.

**Comment by DanielRuf** [comment] 2018-04-20 21:53
The next release will be 6.5.

@ncoden wasn't there already a related issue where someone had a credit card info box at the bottom?

**Comment by sharifzadesina** [comment] 2018-04-20 22:02
@DanielRuf I think as this bug breaks our applications, we should get an early bug fix. stable 6.4.4 would be nice.

**Comment by DanielRuf** [comment] 2018-04-20 22:44
> The next release will be 6.5.

There will not be a 6.4.4 in general.

**Comment by rediris** [comment] 2018-04-30 15:00
I can also confirm this issue exists in Foundation 6.4.3.

**Comment by ncoden** [comment] 2018-04-30 15:50
Duplicate of https://github.com/zurb/foundation-sites/issues/11098. Closing.

**Closed by ncoden** 2018-04-30 15:50 UTC
Labels: Sticky

**Comment by sashabeep** [comment] 2019-09-04 10:57
Issue stil exists on current version 6.5.3!
Sticky top bar moves to the bottom of page on mobile chrome/firefox/etc!
I haven't even set any data-option to force sticky to work on small, i don't need this behavior on small device

**Comment by DanielRuf** [comment] 2019-09-04 11:40
Hi @sashabeep,

this issue was closed as duplicate. Please see #11098.

**Comment by Corncakes** [comment] 2020-11-13 20:01
Hi, I enclosed all the content in a layer and I told the sticky layer to stick to that container layer width **data-options="anchor: page-container"**

Example:

`{{ Any container layer with things (Social share icons, address, etc) }}
<div id="page-container">
        <div class="top-bar-container" data-sticky-container>
          <div class="header-sticky" data-sticky data-options="anchor: page-container; marginTop:0; stickyOn: small;">
            <header class="row large-collapse" role="banner" aria-label="{{ 'Site header'|t }}">
                <div class="large-12 columns header-container">
                  {{ main navigation }}
                  <div class="menu-bars show-for-small-only" data-toggle="right-off-canvas-menu">
                    <i class="fas fa-bars"></i>
                  </div>
                </div>
            </header>
          </div>
        </div>
        {{ Rest of site content }}
</div>`
