### ISSUE TITLE
"Position:Fixed" inside off-canvas-content? (v6.3)?

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#9710] opened 2017-01-27 14:26 UTC
Not sure this issue has been addressed but has anyone noticed a problem with fixed position elements or (.sticky) inside of the off-canvas-content? It seams that any fixed position element does not stay in place after the canvas has been opened (if inside the content area). Once opened, the fixed positioned element inside the content area moves in respect to the scroll position and is no longer visible if the position is set to "top:0".

The example below demonstrates the issue. If you scroll down a bit before opening the menu you can see the drop in nav will disappear.
[EXAMPLE HERE](http://inchdesigns.com/projects/OFFCANVAS/)

Is there anyway to achieve a fixed element when the off-canvas-content is both open and closed?

**Comment by brettsmason** [comment] 2017-01-27 16:31
@jinch thanks for the bug report. I'm going to close this as its a duplicate of #9629 but please keep an eye on that issue, as @colin-marshall and myself are going to try and get a fix into the next release (fingers crossed!).

**Closed by brettsmason** 2017-01-27 16:31 UTC
