### ISSUE TITLE
UX issue: users use backbutton to 'close' full screen modal

### ISSUE THREAD

**Issue by tristandenyer** [zurb/foundation-sites#7606] opened 2015-12-18 05:08 UTC
We have been using Foundation 5 in prototypes and some aspects of production. We user-test our site about twice a month, and have been noticing a common issue with virtually all of our users: they use the backbutton to close the "Clearing lightbox" (F5) and "Full-screen modal" (F6). 

I think this stems from the two modals displaying so quickly they think they are on a new page. They don't see the page behind it, or any indication it is underneath it. Also, the "X" to close it is hard to see for most users, and there is no affordance of being able to click in the whitespace to close it like you can with other modals.

We have found with virtually all of our users that they feel the need to click the backbutton to close it and get confused why they are on a previous page.

We can (and will) be working on a fade in animation and a larger 'close' UI, possibly reducing the background opacity to .9 or .8 to let the original page peek through.

Would love for others to test this with their users and see what they find. Thanks!

**Comment by rafibomb** [comment] 2015-12-18 23:19
Are you referring to a full screen modal vs one where you can see and click the background?

There are ways to do this though not sure if it is a best practice either. Seems like the issue is a design problem with how a full screen modal looks like a new page. There are ways to to make modal close more obvious.

Thoughts?

**Comment by rafibomb** [comment] 2015-12-18 23:41
Maybe an option to enable it? Anyone want to take a stab at it?

**Comment by tristandenyer** [comment] 2015-12-18 23:43
Yes, the modal that takes up the entire screen, not the traditional one that has semi-opaque clickable space around it.

With the one that takes up the whole screen, we found that users thought it was a new page, and felt compelled to use the backbutton.

We are thinking of making an easy improvement to it by being more overt about the 'close' button (though it doesn't fix the 'looks like a new page issue.')  Open this article: http://www.bizjournals.com/sanfrancisco/blog/2015/12/boutique-independent-hotel-oakland-waterfront.html
Click on image to expand in modal.
See their CTA on how to 'close' it? Did you notice the animation of it sliding in?

Again, this is an iteration on the original design, and may work for us. My concern is that the F5/6 framework is being used and accepted en masse. That's a lot of websites that could be suffering from the backbutton issue and not knowing it.

**Comment by andycochran** [comment] 2015-12-21 17:05
Could you force a hash change in in the URL when you open the full-screen modal? Then instead of breaking the back button, you could take advantage of it.

**Comment by tristandenyer** [comment] 2015-12-21 18:58
+1 to @andycochran 's suggestion.

**Comment by andycochran** [comment] 2015-12-21 19:06
Apps should probably handle their own URL change history. Maybe there should be a data option to not `preventDefault()`? Then an app could watch for a hash change when a modal is open.

**Comment by zurbchris** [comment] 2016-01-06 22:31
I think this is useful, though I don't think it'll make it into F5, as we're not adding features to that. For F6 though, I can see adding this in. Probably using similar methods to Magellan's deepLinking feature. I'll take a look.

**Comment by zurbchris** [comment] 2016-01-18 21:56
Implemented in v6.1 closing this for v5 though. Thanks!

**Closed by zurbchris** 2016-01-18 21:56 UTC
Labels: feature, Foundation 5, javascript
