### ISSUE TITLE
F6 SCSS not compiling in Koala

### ISSUE THREAD

**Issue by aleroma** [zurb/foundation-sites#7881] opened 2016-01-14 17:32 UTC
OS - Win7 x64
Koala 2.0.4
Foundation version 6
Compiling result is empty file

**Comment by gakimball** [comment] 2016-01-14 18:12
Make sure that, in addition to importing Foundation, you're also adding these CSS includes: <https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss#L7>

I wasn't able to figure out what version of Sass Koala uses. Foundation 6 is compatible with Libsass and Ruby Sass 3.4 or greater.

**Comment by aleroma** [comment] 2016-01-14 19:15
Koala 2.0.4 uses Sass 3.4.9 (https://github.com/oklai/koala/blob/master/Changelog.md)
But I dont understand where to place app.scss
I have in my scss folder two files: _global.scss and foundation.scss
foundation.scss I guess should compile to foundation.css but it compiles to blank

**Comment by gakimball** [comment] 2016-01-14 19:43
The framework is designed to be externally loaded. Try making a new main Sass file, like `style.scss`, and add `@import "foundation"` at the top. If the two files are in the same folder, it will load automatically.

From there, use `@include`s to add the CSS for components you want. Check out our [starter template Sass file](https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss) for an example—you can see below the imports is a big list of includes. Each include is a CSS component.

**Comment by gakimball** [comment] 2016-01-15 00:30
Closing this as it's not a framework issue, but let me know if my suggestion worked for you. Thanks! :)

**Closed by gakimball** 2016-01-15 00:30 UTC
Labels: awaiting reply, scss

**Comment by aleroma** [comment] 2016-01-15 05:58
It seems that your suggestion worked. So thanks a lot!
I have added file `style.scss` and copy there contents of [app.css](https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss) but some strings need to be corrected:
1) remove strings related to `motion-ui` (causing Error: File to import not found or unreadable: motion-ui)
2) change `@import 'settings';` to `@import 'settings/settings';`
And viola - now I have compiled framework in `style.css`! 
And I can adjust settings - so that`s what all the fuss is about.

**Comment by aleroma** [comment] 2016-01-15 06:12
May be it woould be usefull to extend framework documentation (or create some template) for Windows users who only want to tune framework by adjusting `scss` files and dont want to dig into `node.js`, `gulp`, `ruby`, `rails`, `libsass`, `cli` and other weird terms?

**Comment by gakimball** [comment] 2016-01-15 06:16
@aleroma Some of this is covered in the [Sass documentation](http://foundation.zurb.com/sites/docs/sass.html#loading-the-framework), but we do need to do a better job breaking down all of the install options.

**Comment by aleroma** [comment] 2016-01-15 06:31
O! New term `Autoprefixer`. Ding-ding, a new issue occurs :) And how it can be used on windows systems?...

**Comment by gakimball** [comment] 2016-01-16 01:04
You need Ruby or Node on your machine no matter what to use Sass, unless you use a tool like Koala, CodeKit, Prepros, etc. Those GUIs are really nice because they don't require you to have a dev environment setup. If you're not interested in the hassle of maintaining a dev environment (and it *is* a huge hassle for sure), then I'd recommend sticking with Koala.

**Comment by tomByrer** [comment] 2016-01-16 04:38
> From there, use @includes to add the CSS for components you want. Check out our starter template Sass file for an example—you can see below the imports is a big list of includes. Each include is a CSS component.

Took me hours to figured out why upgrading from v5 Foundation to v6 Foundation-Sites broke my Guip script.  The old `foundation.scss` `@include`ed everything by default, but now it is hidden behind a switch/`@mixin`.

Part of the problem is with SASS IMHO since it uses both `include` & `import` to do similar but different duties, where they are also [the same terms in different languages](http://stackoverflow.com/questions/172262/c-include-and-import-difference) without being exactly the same.

But I think if I found an upgrade guide v5 to v6 on Foundation's site/GH, that could have spared me a few hours.

**Comment by aleroma** [comment] 2016-01-16 05:06
OK, it seems that I found solution for autoprefixer - [Autoprefixer online](http://autoprefixer.github.io/).
And if I understand correctly, I should apply autoprefixer to framework after compilation.

**Comment by tomByrer** [comment] 2016-01-16 13:20
[koala has autoprefix](https://github.com/oklai/koala/search?utf8=%E2%9C%93&q=autoprefix).    I personally prefer [Gulp's flexability](http://gulpjs.com/plugins/).  But I think we're getting off topic. ;)

Yes, autoprefix after compiling to CSS, before minification.
