### ISSUE TITLE
Dropdown menu issue

### ISSUE THREAD

**Issue by apcrane** [zurb/foundation-sites#7063] opened 2015-11-20 16:05 UTC
I seem to having issues with links in the dropdown menu not working, for example my syntax is below.
I've highlighted via ** the links that nothing happens for. 

```
  <ul class="dropdown menu" data-dropdown-menu>
                    <li>
                    <a>Settings</a>
                        <ul class="menu">
                             <li>**<a href="http://www.bbc.co.uk">Test Link</a>**</li>
                            <li>**<a href="http://www.msn.co.uk">Log Out</a>**</li>
                        </ul>
                    </li>
                </ul>
```
Also, I noticed in your example (http://foundation.zurb.com/sites/docs/dropdown-menu.html) the links are '#', but when clicking on them the '#' isn't appearing the address bar, which I would expect it to.

**Comment by zurbchris** [comment] 2015-11-20 18:56
What browser are you using? I just took this screen cap from the live docs page, and it's working as intended.

![screen shot 2015-11-20 at 10 55 32 am](https://cloud.githubusercontent.com/assets/13631168/11308820/49ef24e8-8f75-11e5-968e-260ce99f3622.png)

**Comment by zurbchris** [comment] 2015-11-20 20:07
The title issue is totally *my* fault only. I had a separate branch at one point working on menus and there was a change or two that never got merged in. The title attribute will be reassigned to the proper `aria-label` in the next patch.
![tom is sorry](https://media.giphy.com/media/gEOUGN3HnK5Fu/giphy.gif)

**Comment by JeremyEnglert** [comment] 2015-11-22 03:51
Having the same issue. You can see it here: http://jointswp.com/demo/

Running 6.0.3.

**Comment by zurbchris** [comment] 2015-11-22 04:00
Dropdown menus are getting a non-breaking overhaul, I've worked on it most of today and it should be ready before thanksgiving.

**Closed** 2015-11-25 05:19 UTC
