### ISSUE TITLE
Tooltip Hovering

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#7645] opened 2015-12-21 19:18 UTC
Small issue with the tooltips. When you hover over the letters where the tooltip arrow appears it causes the tooltip to constantly interfere with hovering the tooltip-ed element in Firefox. In Chrome it only does it while moving the mouse
http://foundation.zurb.com/sites/docs/tooltip.html
In Firefox if you hover over the B in scarabaeus you can see what I'm talking about. As I said, Chrome does the same thing, but only when the mouse is moving.

**Comment by zurbchris** [comment] 2015-12-22 21:42
I see the issue, it's the triangle receiving hover, I'll see about getting that fixed in the new year.

**Comment by ivanjaros** [comment] 2016-01-01 16:06
I have tooltip where it is applied only to single character(?) and in my case it flickers constantly, it's basically unusable.

**Comment by ivanjaros** [comment] 2016-01-05 19:25
I have fixed my issue by setting the horizontal and vertical offset. The issue comes from the "beak" which cuts off from the offset so I had to take that into account and increase the value. I think that should be in the core by default.

**Comment by andycochran** [comment] 2016-01-06 15:50
The problem is the border for the triangle is a uniform width on all 4 sides. We don't need a border on the side adjacent to the hover area. Could be fixed by something like: 
```
.tooltip.top::before {
  border-bottom-width: 0;
}
.tooltip.bottom::before {
  border-top-width: 0;
}
```

**Comment by andycochran** [comment] 2016-01-06 16:04
Actually, I found a better fix in `@mixin css-triangle()`. Making a PR…

**Closed** 2016-01-06 21:30 UTC
Labels: bug, javascript
