### ISSUE TITLE
[Orbit] Orbit js don't put the nav bullets

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8134] opened 2016-02-11 03:02 UTC
Hi guys, i have this problem with the new orbit version, but i don't know if is a deprecated feature or you forgot it:
![area de trabajo 1_090](https://cloud.githubusercontent.com/assets/5034215/12968567/afa080d6-d041-11e5-8cc9-98f5998fc07a.png)

As you can see, in older versions the bullets are putting by orbit script, but in the new version doesn't it.
i can see in the docs that we should put the bullets, but it's a difficult way to put it, but i don't know then why we have this options:
![seleccion_093](https://cloud.githubusercontent.com/assets/5034215/12971535/24284830-d06a-11e5-8f04-47866a0867a4.png)

Oh, will be better put a orbit-margin option.

And, using &#9664 and &#9654 we have a ugly effect:
![seleccion_092](https://cloud.githubusercontent.com/assets/5034215/12968824/2da52e34-d045-11e5-9410-3fd203afdd98.png)
I think that this will be solver easy using Foundation icons, i solved this using Font-Awesome icons inside &#9664 and &#9654, change this in the documentation will be useful.

Thanks.

**Comment by colin-marshall** [comment] 2016-04-27 23:37
@SalahAdDin I'm closing this issue because we don’t have a reproduceable case to test against. If this is still an issue, please reopen with the info requested here:
https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

**Closed by colin-marshall** 2016-04-27 23:37 UTC
Labels: bug, javascript

**Comment by SalahAdDin** [comment] 2016-04-28 02:13
Ok, thanks :+1:
