### ISSUE TITLE
[Reveal] Ajax reveal and inline reveal don't work well together

### ISSUE THREAD

**Issue by briantan888** [zurb/foundation-sites#7414] opened 2015-12-05 18:34 UTC
If I have a reveal opened by Ajax and then closed, later when an inline reveal is opened, the windows background will become dark-gray (not the usual light-gray tint). Closing the inline reveal does not restore windows from modal mode, and becomes inoperable.

The more times Ajax reveal are opened and closed, the darker the background will be when inline reveal is opened.

This problem does not occurred if both reveals are Ajax opened,

**Comment by Owlbertz** [comment] 2015-12-05 20:38
Any code example? E.g. in a Codepen?

**Comment by briantan888** [comment] 2015-12-05 22:44
Ok. I reproduce problem here.

http://codepen.io/briantan888/pen/gPOBKG#0

Click ajax first, close, then click inline.

**Comment by Owlbertz** [comment] 2015-12-05 22:58
I think the issue is that you call `$(document).foundation()` in your function.

**Comment by briantan888** [comment] 2015-12-05 23:48
I needed that as my ajax loaded modal contains js components.

anyway, I converted the inline open to js open, and it is OK.

**Comment by zurbchris** [comment] 2015-12-06 06:19
Should have been fixed with b0d86fb

**Comment by briantan888** [comment] 2015-12-06 06:35
I apply this patch and confirm fixed the issue. Thanks Chris.

**Closed** 2015-12-06 14:42 UTC
