### ISSUE TITLE
Foundation 6 - deep linking for tabs no documentation

### ISSUE THREAD

**Issue by jnartey** [zurb/foundation-sites#7652] opened 2015-12-22 07:56 UTC
There is no documentation on deep linking for tabs in zurb foundation 6. How is deep linking done?

**Comment by zurbchris** [comment] 2015-12-22 20:03
This feature is not yet implemented. If you would like to take a crack at it and submit a pr, I'd love to see it.

**Comment by tehlivi** [comment] 2015-12-29 20:02
Waiting for this as well.

**Comment by jaysonbrown** [comment] 2015-12-30 21:26
Mee too! ... I coded an entire site based on the assumption this function would be available.

**Comment by Giltvedt** [comment] 2016-01-18 11:04
Me too! I need to use custom jQuery meanwhile.

**Comment by zerodahero** [comment] 2016-01-18 16:43
Here's my workaround for it, jQuery style, in the meantime:

```javascript
var link_tab = window.location.hash.substr(1);
if(link_tab){
    $('[data-tabs]').eq(0).foundation('selectTab', $('#'+link_tab));
}
```

**Comment by jaysonbrown** [comment] 2016-02-25 15:39
I really need a solution today ... built an entire project on foundation 6, and now foundation 5 can no longer generate custom builds ... what do I do?!

**Comment by rafibomb** [comment] 2016-02-25 18:14
We're adding this to our roadmap for this plugin in a future release. Thanks @zerodahero for providing your solution!

We'd love a PR on this in the meantime - it is being added to the development roadmap which we'll be publishing within a week.

**Comment by jaysonbrown** [comment] 2016-02-25 18:43
Hi Team,

I ended up loading foundation 5 below 6. Removed everything but 'tabs' in the CSS and the class 'meta.foundation-data-attribute-namespace'. also needed to load modernizer.

This works with no issues (on the pages I needed deep-linking tabs!) Not the tidiest solution, but it works!

**Comment by jaysonbrown** [comment] 2016-03-23 23:27
Looking forward to the deep-linking tabs coming back :)

**Comment by JTallis** [comment] 2016-04-08 20:28
I'm waiting for this, too. My laziness kicks in and I'd rather wait for this to be released than to code a work-around. Especially seeing as anchors aren't even being set when you click tabs.

**Comment by jaysonbrown** [comment] 2016-04-08 23:31
I really need this feature :(

**Comment by chrismacho** [comment] 2016-05-27 03:07
Nothing yet? ughhhhhh

**Comment by jaysonbrown** [comment] 2016-05-27 03:17
@chrismacho ... hey, it doesn't have a call back but this works:

`
$(document).ready(function() {

	// Hash tab

	var link_tab = window.location.hash.substr(1);
	
	if (link_tab) {
		
		$('[data-tabs]').eq(0).foundation('selectTab', $('#'+link_tab));
	}
	
	// Select tab
	
	document.getElementById("tabs-mobile").onchange = function() {
    if (this.selectedIndex!==0) {	
     tabs_selected = this.value;
     $('[data-tabs]').eq(0).foundation('selectTab', $('#'+tabs_selected));
    }        
  };

});

`

**Comment by jaysonbrown** [comment] 2016-05-27 03:19
Hey @chrismacho ... it doesn't have callbacks, but this works for me.

// Hash tab

var link_tab = window.location.hash.substr(1);

if (link_tab) {

	$('[data-tabs]').eq(0).foundation('selectTab', $('#'+link_tab));

}

// Select tab

document.getElementById("tabs-mobile").onchange = function() {
  if (this.selectedIndex!==0) {	
   tabs_selected = this.value;
   $('[data-tabs]').eq(0).foundation('selectTab', $('#'+tabs_selected));
  }      
};

**Comment by jaysonbrown** [comment] 2016-05-29 17:43
I really need to figure out callbacks, I use them too much in foundation 5. :(

**Comment by LiamW** [comment] 2016-06-30 17:54
Not a JS expert, and can't get this to work. Just wanted to confirm it still works in latest Foundation sites and maybe some example code of how exactly to set this up?

I just have a super basic need where I have a page with tabs and would like to link to each tab across the site in the footer menu. The footer links will loop through pages from the CMS and output a link like `<a href="/page/#panel$Pos">$MenuTitle</a>` though it can easily be customized.

Can that be achieved with the JS above? And do I just call that after the `$(document).foundation();` call?

I've tried a few things and nothing seems to work.

**Comment by drivenfaroff** [comment] 2016-07-26 21:54
`// Hash tab

var link_tab = window.location.hash.substr(1);

if (link_tab) {

    $('[data-tabs]').eq(0).foundation('selectTab', $('#'+link_tab));

}
`

This works for opening/jumping to first instance of [data-tabs] on my page, however it doesn't recognize the hash for tabs in another [data-tabs] section. Any help or suggestions to get it to work with multiple tab areas on one page?

**Comment by ahebrank** [comment] 2016-08-05 18:16
Here's a jQuery solution that should handle multiple tabsets on a page, open and jump to the proper tab at load (and adjust the scroll position of the page a little to show the tab header), and push the hash to the browser URL when a tab is clicked:

```
function tabDeepLink(selector) {
	$(selector).each(function() {
		var $tabs = $(this);

		// match page load anchor
		var anchor = window.location.hash;
		if (anchor.length > 0 && $tabs.find('[href="'+anchor+'"]').length) {
			$tabs.foundation('selectTab', $(anchor));
			// roll up a little to show the header
			var offset = $tabs.offset();
			$(window).load(function() {
				$('html, body').animate({ scrollTop: offset.top }, 300);
			});
		}

		// append the hash on click
		$tabs.on('change.zf.tabs', function() {
			var anchor = $tabs.find('.tabs-title.is-active a').attr('href');
			history.pushState({}, "", anchor);
		});
	});
}

// turn this on for all the tabs or a subset
tabDeepLink('.tabs');
```

**Comment by andycochran** [comment] 2016-10-06 19:26
@ahebrank This is a great solution. Thanks. Would be even better if it worked with the back button. Any thoughts on implementing that?

**Comment by kball** [comment] 2016-10-06 20:40
I'd like to get this in to 6.3. @ahebrank do you want to submit a pull request?

**Comment by jaysonbrown** [comment] 2016-10-06 20:46
We need both the hash options, deep linking and tab callbacks ASAP.

It was in version 5 but was removed in version 6. I almost lost a client over this, my only resolution was to load both 5 & 6 together as a super hack.

This is why I can't have nice things.

**Comment by ahebrank** [comment] 2016-10-06 21:32
The above was intended more as a workaround, but I'll take a look and see about a PR that fits into the framework.

**Comment by kball** [comment] 2016-11-08 18:57
#9242 has been merged addressing this.  Great work @ahebrank!

**Closed by kball** 2016-11-08 18:57 UTC
Labels: feature, help wanted, javascript
