### ISSUE TITLE
What-Input - Foundation 6.5.3 is using out-dated version

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#11798] opened 2019-08-02 01:09 UTC
In 6.5.1
/**
 * what-input - A global utility for tracking the current input method (mouse, keyboard or touch).
 * @version v4.2.0
 * @link https://github.com/ten1seven/what-input
 * @license MIT
 */

But there is a  newer version

https://ten1seven.github.io/what-input/scripts/what-input.js

/**
 * what-input - A global utility for tracking the current input method (mouse, keyboard or touch).
 *** @version v5.2.1**
 * @link https://github.com/ten1seven/what-input
 * @license MIT
 */

A. In the current Github 6.5.3 Dist I can not find the what-input file. Is it no longer in use / needed in 6.5.3 ?

B. it is present in 6.5.1 in the everything Download ??????
https://foundation.zurb.com/sites.html

**What-Input 5.2.1 IS working in my build  of Foundation 6.5.3.
with this demo
https://ten1seven.github.io/what-input/**

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Self-explanatory

 See this by Ncoden 2018
https://github.com/zurb/foundation-sites/issues/11290

 Your Environment

Not applicable - dependencies should be updated

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2019-08-02 04:17
Hi @blynnc,

Thanks for letting us know.
We may have to update some dependencies and we do the updates for every release.

See https://github.com/zurb/foundation-sites/blob/develop/package.json#L104 and the lockfiles.

We will take care of this when we do the next release.

I'll close this issue as it's not a bug but just a reminder (we will check the dependencies then as always and bump their versions).

**Closed by DanielRuf** 2019-08-02 04:17 UTC
