### ISSUE TITLE
[Equalizer] inside a container [Tab] is not working properly

### ISSUE THREAD

**Issue by madhanan** [zurb/foundation-sites#8867] opened 2016-05-30 23:16 UTC
# 

## **How can we reproduce this bug?**
1. Create a Tabs panel "tab1" and "tab2"- inside each tab create 2 or more callout panel with data equalizer
2. Adjust Screen size while "tab2" is selected and then click "tab1" - Data Equalizer doesn't work
3. and Now Adjust screen size while "tab1" selected and Click "tab2" - Data Equalizer doesn't work

## **What did you expect to happen?**
I Expected the data equalizer to work

## **What happened instead?**
Data Equalizer didn't work properly, When it is not working.. try to adjust screen size it works immediately

## Link to CodePen - [Foundation 6] : (https://codepen.io/madhanan/pen/wWvQNY)
1- In this Example Tab-1(named as 'Education') and Tab-2 (named as 'Certification') (by default Tab-1 is active)
2- Select Tab-2(Certification) and  adjust screen size slightly while Tab-2 is active, Now Click "Tab-1" and see the Error as shown below

![3](https://cloud.githubusercontent.com/assets/19624958/15659515/abef301e-26e9-11e6-81a8-fa8b69dfa9a6.png)
## Error
![4](https://cloud.githubusercontent.com/assets/19624958/15659516/abf04b7a-26e9-11e6-84d6-e9bcb27427e4.png)

3- Select Tab-1(Education) and  adjust screen size slightly while Tab-1 is active, Now Click "Tab-2 " and see the Error as shown below

![1](https://cloud.githubusercontent.com/assets/19624958/15659517/abf10c5e-26e9-11e6-829f-008022a0eda7.png)
## Error
![2](https://cloud.githubusercontent.com/assets/19624958/15659514/abee1148-26e9-11e6-8fa0-fe2ed237add5.png)

**Comment by designerno1** [comment] 2016-05-31 11:30
have you tried this #8556

**Comment by madhanan** [comment] 2016-06-20 03:55
yes, but Foundation 6 is supposed to work out of the box. Instead of user intervention :(

**Comment by andycochran** [comment] 2016-07-01 18:50
Agreed. Foundation 6 should work out of the box. I think `display:none` is the wrong approach for Tabs. I'm going to close this, as it *is* a duplicate of #8556. But I'll also assign myself to that issue and make sure a fix happens.

**Closed by andycochran** 2016-07-01 18:50 UTC
