### ISSUE TITLE
foundation-everything breaks CSS on iOS 10 in portrait mode

### ISSUE THREAD

**Issue by NicolayD** [zurb/foundation-sites#11427] opened 2018-07-31 14:47 UTC
## What should happen?

CSS should load properly.

## What happens instead?

CSS doesn't load at all in portrait mode on iOS 10 in Safari. (only in production)

## Possible Solution

It might be because of a width setting, but I don't have any good guesses.

## Context

I am working on a Phoenix 1.3 web application with React 16.3.1 and Foundation as a front-end framework.
The application displays fine both in development and in production except for one case - on iOS 10 in portrait mode in production. Phoenix uses Brunch to compile assets.

## Your Environment

- Foundation version(s) used: ^6.4.4-rc1, also tried 6.5.0-rc.1 and 6.5.0-rc.2
- Browser(s) name and version(s): Safari 10
- Operating System and version (desktop or mobile): iOS 10, iPhone

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment] 2018-07-31 15:10
Can you either share the code or a screenshot of the issue?

In general: that's probably not an issue with Foundation or the mixin in general.

**Comment by NicolayD** [comment] 2018-07-31 15:26
It's just that none of the css loads at all.
I'm using the XCode simulator to replicate it locally, however it was confirmed from an iOS 10 device.
This is how it looks in landscape mode (after I stripped everything except foundation-everything and a css class that should hide some of the divs, so it's not how it should look but still):
<img width="628" alt="screen shot 2018-07-31 at 6 19 43 pm" src="https://user-images.githubusercontent.com/21177240/43469313-8c47c710-94ee-11e8-8bb4-925821016558.png">

And this is how it looks in portrait mode (the css class that should hide some of the components also doesn't work):
<img width="322" alt="screen shot 2018-07-31 at 6 19 59 pm" src="https://user-images.githubusercontent.com/21177240/43469362-aab28654-94ee-11e8-81e9-23a8c3fdf455.png">

The weird thing is that it works fine in other any other OS and browser that we have tried. But it is also fine locally on that specific OS and device, as far as the simulator goes.

**Comment by NicolayD** [comment] 2018-07-31 15:29
It's just that none of the css applies at all and I get a page with just html. I'm using the XCode simulator to replicate it locally, however it was confirmed from an iOS 10 device.

In landscape mode, after I stripped everything except foundation-everything and a css class that should hide some of the divs, it works fine.

In portrait mode neither the foundation classes nor the custom css class that should hide some of the components work.

The weird thing is that it works fine in other any other OS and browser that we have tried. But it is also fine locally on that specific OS and device, as far as the simulator goes.

**Comment by ncoden** [comment] 2018-08-01 18:55
I am not able to reproduce it with on iOS Safari 10 (iPhone 7) with:
```scss
@include foundation-everything();
```

<img width="981" alt="screen shot 2018-08-01 at 20 50 50" src="https://user-images.githubusercontent.com/9939075/43542183-a19162a0-95cc-11e8-9b4f-f3846866b881.png">

I think it comes from your CSS minification in production. If you use `cssnano`, make sure it is up-to-date.

**Comment by NicolayD** [comment] 2018-08-01 19:04
Thanks for the feedback!
I'm using Brunch in production. 

I solved the problem by using the CDN link for foundation-float (minified, to be precise, although it shouldn't matter I believe).

I might try using the standard foundation.min.css version to see if it would change things. I'll write if anything else pops up.

**Comment by ncoden** [comment] 2018-08-01 19:17
I'm closing this issue as this seems to come from your build process. We'll reopen it if your investiguation show that there's anything we can do on our side to prevent this minification bug. Thank you for your report!

**Closed by ncoden** 2018-08-01 19:17 UTC
