### ISSUE TITLE
[Sticky] Errors in Sticky Plugin Documentation

### ISSUE THREAD

**Issue by HGeist** [zurb/foundation-sites#8639] opened 2016-04-20 10:06 UTC
Hello ZURB Team,

i got stuck on a little error in your documentation for the Sticky plugin. In the Javascript Event Reference the names of the events in the left column of the table are turned around. It is "unstuckfrom.zf.sticky" instead of "sticky.zf.unstuckfrom.zf" and "stuckto.zf.sticky" instead of "sticky.zf.stuckto".

Also, it was hard to get that you have to add a namespace in order to make it work. I would propose that you add all 4 variants in the left column of the table.

![image](https://cloud.githubusercontent.com/assets/1826771/14671080/4108a38e-06f0-11e6-837e-33330d7e0d2a.png)

Best regards

Hannes Geist

**Comment by JeremyEnglert** [comment] 2016-04-28 23:47
Thanks for the heads up! This is a duplicate of https://github.com/zurb/foundation-sites/issues/7914.

So I'm going to close for now.

**Closed by JeremyEnglert** 2016-04-28 23:47 UTC
Labels: bug, docs
