### ISSUE TITLE
[Dropdown Menus] dropdown arrow is not responsive

### ISSUE THREAD

**Issue by briantan888** [zurb/foundation-sites#7739] opened 2016-01-02 14:51 UTC
```
<ul class="vertical medium-horizontal dropdown menu" data-dropdown-menu>
```

Arrow is always pointing right regardless of media size.

**Comment by colin-marshall** [comment] 2016-01-03 23:56
Just ran into this same issue. Looks like if the `.vertical` class is present, it always adds the `.is-right-arrow` class to the menu. The dropdown component should check and see if horizontal classes are also present on the dropdown menu.

**Comment by briantan888** [comment] 2016-01-04 01:58
Probably an easy fix.

**Comment by gakimball** [comment] 2016-01-27 17:49
Closing in favor of #7978. Both problems are caused by the same issue.

**Closed by gakimball** 2016-01-27 17:49 UTC
Labels: bug, scss
