### ISSUE TITLE
[Normalize] Move to global styles?

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#7363] opened 2015-12-03 12:08 UTC
Would it be possible to move the normalize import to the global styles mixin? On a few projects I'd really like to output normalize at a specific place but I can't unless I put the main foundation import there (but then settings needs to move too which messes up my main stylesheet layout).

It would be a great help if that would be possible!

**Comment by gakimball** [comment] 2015-12-03 17:58
Duplicate of #7159. But yep, definitely want to do this. Only bummer is you can't put an `@import` inside of a mixin, but also Normalize hasn't had a new version in over a year, so it's not like updating it will be too much of a hassle.

**Closed by gakimball** 2015-12-03 17:58 UTC
Labels: scss
