### ISSUE TITLE
failed to @extend "%reveal-centered"

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#9821] opened 2017-03-01 05:15 UTC
When using just this in 6.3.1:
```scss
.gu-modal {
	@include reveal-modal-base;
	@include reveal-modal-width(75%);
}
```
I get this error:
```
Error: ".gu-modal" failed to @extend "%reveal-centered".
       The selector "%reveal-centered" was not found.
       Use "@extend %reveal-centered !optional" if the extend should be able to fail.
        on line 94 of node_modules/foundation-sites/scss/components/_reveal.scss
>>     @extend %reveal-centered;
   ----^
```

It only doesn't complain when I add this after it:
```scss
@include breakpoint(medium) {
      %reveal-centered {
        right: auto;
        left: auto;
        margin: 0 auto;
      }
    }
```

```scss
.gu-modal {
	@include reveal-modal-base;
	@include reveal-modal-width(75%);
	
	@include breakpoint(medium) {
      %reveal-centered {
        right: auto;
        left: auto;
        margin: 0 auto;
      }
    }
}
```

**Comment by rafibomb** [comment] 2017-04-03 22:54
It's not clear what you're trying to accomplish but using a Sass placeholder without @extend would not work.

I would expect this works better

```
.custom-modal {
  @include reveal-modal-base;
  @include reveal-modal-width(75%);
  @extend %reveal-centered;
}
```
but i have success doing this

```
.custom-modal {
  @include reveal-modal-base;
  @include reveal-modal-width(75%);
  @include horizontal-center;
}
```

**Comment by kball** [comment] 2017-04-17 20:48
Interesting... so if I'm understanding correctly the issue is that the @reveal-modal-width mixin does not work.  We should fix this. Lets take a look for 6.4

**Comment by kball** [comment] 2017-04-18 23:47
Ah interesting. I think the issue is that the placeholder is actually only *defined* within the foundation-reveal mixin... and within a breakpoint check at that...  that's clearly a bug, it makes any mixin referencing it only usable within that mixin...

I think the fix is probably as simple as moving the placeholder out into global scope in `scss/components/_reveal.scss`. @Knight-Yoshi would you like to take a pass on this?

**Comment by kball** [comment] 2017-06-01 00:13
Unable to reproduce this with recent builds... I'm wondering if this is a difference in node-sass version... a little googling shows the interactions of %placeholders% and media queries to be a _hot_ topic.  I don't have anything more specific at this point, but as we're updating the dependencies in the next release and we can't seem to repro, going to close.  Feel free to reopen if still seeing the issue in new builds.

**Comment by kball** [comment] 2017-06-01 17:37
It appears to be build specific... just got another report of this from someone using webpack's sass-loader... have a potential fix that appears to be working for them. Reopening and will submit that fix.

**Comment by ncoden** [comment] 2018-01-08 21:39
I'm closing this since the issue should have been resolved in https://github.com/zurb/foundation-sites/pull/10101

**Closed by ncoden** 2018-01-08 21:39 UTC
Labels: Difficulty - Beginner, Sass Mixins, bug, scss
