### ISSUE TITLE
Tabs with deep linking, back button breaks in firefox

### ISSUE THREAD

**Issue by harshabonthu** [zurb/foundation-sites#6644] opened 2015-06-22 18:47 UTC
Hi,

We have seen this issue in safari before (https://github.com/zurb/foundation/issues/6102), now its fixed in safari but breaks in firefox. 

I am testing on Firefox 38.0.5 and OSX 10.10.3, here is the screencast -> http://recordit.co/Q5Ojtfxtyl

**Comment by ggn06awu** [comment] 2015-07-22 14:21
+1

**Comment by TW80000** [comment] 2015-08-24 15:24
This may be a duplicate of #6310.

**Comment by hackley2** [comment] 2015-11-12 17:53
I'm using Firefox 42.0 on OSX 10.9.5 and I can confirm that this is a Firefox only issue. The back button works perfect in Chrome, Opera, and Safari. I used foundation's own documentation page http://foundation.zurb.com/docs/components/tabs.html to test it. I'd love to see a fix for this too as this prevents us from being able to deep linking tabs on any production websites.

**Comment by hackley2** [comment] 2015-11-12 17:59
@zurbrandon, I just noticed your post in #6310 about pinging you if the issue wasn't fully resolved. Not sure if this ticket needs to be merged into #6310 or not, but here's your ping. Thanks!

**Comment by hackley2** [comment] 2015-11-12 19:04
For those people who need a quick fix (it's not best practice to modify library files), until something official is decided upon, Here's how I modified foundation.min.js to fix the issue. 

Commenting out the below code stops Foundation from auto applying a hash tag to the page upon page load, but still preserves the deep linking feature when a tab is clicked on. 

From the foundation.tabs.js file, I found where foundation was adding a hashtag to the URL upon page load (i.e. turning http://foo.com into http://foo.com#fndtn-tab-name). It's about line 118 just above where the toggle_active_tab function is defined. Commenting out the entire for loop did the trick, so then I found that same place in foundation.min.js. Do a search for the following code in foundation.min.js:
```
else for(var l=0;l<e.default_tab_hashes.length;l++)e.toggle_active_tab(t("["+e.attr_name()+"] > * > a[href="+e.default_tab_hashes[l]+"]").parent())
```
And then just comment out exactly that code. You should end up with the following code (which will be surrounded by more non-commented-out minified code):
```
/*else for(var l=0;l<e.default_tab_hashes.length;l++)e.toggle_active_tab(t("["+e.attr_name()+"] > * > a[href="+e.default_tab_hashes[l]+"]").parent())*/
```

Again, this isn't best practice. If you decide to use this fix, be careful because updating to a newer version of foundation will obviously break the fix. But, hopefully we'll have an official fix for it by then!

**Comment by rafibomb** [comment] 2017-10-03 21:37
A PR would be merged for this. We'll close this here - thanks!

**Closed by rafibomb** 2017-10-03 21:37 UTC
Labels: Foundation 5
