### ISSUE TITLE
6.4.1 - Menu component - Icon top no longer renders on top

### ISSUE THREAD

**Issue by adamj88** [zurb/foundation-sites#10450] opened 2017-07-22 12:52 UTC
#### How to reproduce this bug:

Using foundation-sites@6.4.1 and the following markup from the documentation:

```
<ul class="menu icon-top">
  <li><a href="#"><i class="fi-list"></i> <span>One</span></a></li>
  <li><a href="#"><i class="fi-list"></i> <span>Two</span></a></li>
  <li><a href="#"><i class="fi-list"></i> <span>Three</span></a></li>
  <li><a href="#"><i class="fi-list"></i> <span>Four</span></a></li>
</ul>
```

#### What should happen:

Icons appear above menu links

#### What happened instead:

Icons appear to the left of menu links

#### Browser(s) and Device(s) tested on:

Chrome/Macbook Pro

#### Foundation Version(s) you are using:

6.4.1

#### Test case link:

http://foundation.zurb.com/sites/docs/menu.html#icons

**Comment by IamManchanda** [comment] 2017-07-22 16:50
Duplicate of #10290 and fixed in #10331 

Will be released in **6.4.2** (expect it soon)
Gonna close this but feel free to reply if you still facing any issues buddy ??

**Closed by IamManchanda** 2017-07-22 16:50 UTC
