### ISSUE TITLE
rounding error in grid column width calculation in Firefox?

### ISSUE THREAD

**Issue by beda42** [zurb/foundation-sites#10779] opened 2017-11-20 09:05 UTC
#### How to reproduce this bug:

1. Create a .grid-x with grid-margin-x with 4 columns
2. Open it in Firefox (tested with FF 56 and 57 under Linux)
3. Set default font size to 14.

#### What should happen:
4 columns should be displayed side by side

#### What happened instead:
3 columns are in one row, the last one wraps under the first one

#### Browser(s) and Device(s) tested on:
FF 56 and 57, Linux, two different Linux PCs.

#### Foundation Version(s) you are using:
6.4.3

#### Test case link:
[simple demo](https://codepen.io/beda42/pen/zPRvQJ)

#### Notes:
* Changing the default browser font size to 13 or 15 or zooming in and out leads to the columns realigning properly.
* In Chrome, it works OK all the time.
* When looking at the CSS in the Inspector, the width is calculated like this: `width: calc(25% - 1.875rem);`. If I change the 1.875rem to 1.876rem, the problem goes away. This is why I think this might be a rounding error.
* The same occurs with 5 columns, not with 3.
* Screenshot attached.
![screenshot at 2017-11-20 10-04-29](https://user-images.githubusercontent.com/1674433/33010276-3b28f60a-cdda-11e7-9539-052660ac970e.png)

**Comment by DanielRuf** [comment] 2018-04-06 20:50
Related https://github.com/zurb/foundation-sites/issues/10808

**Comment by DanielRuf** [comment] 2018-04-07 19:10
Did you mean https://github.com/zurb/foundation-sites/pull/10978?

**Comment by ncoden** [comment] 2018-04-10 21:47
Duplicate of https://github.com/zurb/foundation-sites/issues/10808 yes.

**Closed by ncoden** 2018-04-10 21:47 UTC
Labels: browser bug
