### ISSUE TITLE
Star button looks blurry in Chrome

### ISSUE THREAD

**Issue by wesinator** [zurb/foundation-sites#10954] opened 2018-02-19 03:12 UTC
#### How to reproduce this bug:

1. Visit https://foundation.zurb.com/sites/docs/ in Chrome and Firefox.
Look at the Github star button

#### What should happen:
Github Star button should be clear on both 

#### What happened instead:
Star button appears blurred on the page in Chrome.

#### Browser(s) and Device(s) tested on:
Chromium 64 and Firefox 58
1366x768px screen

#### Foundation Version(s) you are using:
6.4.3

**Comment by DanielRuf** [comment] 2018-02-19 05:26
Seems to be fine here on mobile. Will check it in about 2 hours on desktop.

**Comment by ncoden** [comment] 2018-02-19 06:21
@wesinator Could you provide a screenshot ?
What is your OS ?

**Comment by DanielRuf** [comment] 2018-02-19 06:53
Chrome 64 latest stable:
macOS 10.12: crisp
Windows 10 in Browserstack: crisp
Windows 8.1 in Browserstack: crisp

**Comment by DanielRuf** [comment] 2018-02-19 06:55
We also have no direct control of the buttons as these are iframes which load the styles directly from GitHub.

Maybe you have locally installed some font of the used fontstack like Roboto?

<img width="311" alt="bildschirmfoto 2018-02-19 um 07 54 34" src="https://user-images.githubusercontent.com/827205/36365512-30f5642c-154a-11e8-9203-a4256cecba91.png">
<img width="731" alt="bildschirmfoto 2018-02-19 um 07 54 01" src="https://user-images.githubusercontent.com/827205/36365513-3119c0f6-154a-11e8-8900-add5ee382e88.png">

**Comment by DanielRuf** [comment] 2018-02-19 06:59
At least I have none of them installed on my system so the OS specific fonts are used and if a font-face is loaded the external files are preferred (some fontfacekits prefer `local` fonts before loading external fonts).
![bildschirmfoto 2018-02-19 um 07 57 44](https://user-images.githubusercontent.com/827205/36365646-bfa1992a-154a-11e8-9469-682d968f6bcb.png)

**Comment by wesinator** [comment] 2018-02-19 14:39
@ncoden this is on Linux (Ubuntu).

Chrome:
![starbutton_blur_chrome](https://user-images.githubusercontent.com/5124946/36382756-0ffdcd0a-1558-11e8-9a4c-84c5e0c47298.png)

![chrome](https://user-images.githubusercontent.com/5124946/36382897-8083dfe2-1558-11e8-90e3-e38978dfeac0.png)


Firefox:
![star_button_ff](https://user-images.githubusercontent.com/5124946/36382762-156de978-1558-11e8-8887-eb6630a13b3f.png)

![ff](https://user-images.githubusercontent.com/5124946/36382911-8cb307e8-1558-11e8-82c2-efa2097b1d06.png)

The button itself isn't blurry when viewing the iframe url, but on the page it looks blurry in Chrome, probably a CSS setting on the page.

**Comment by DanielRuf** [comment] 2018-02-19 14:42
> The button itself isn't blurry when viewing the iframe url, but on the page it looks blurry in Chrome, probably a CSS setting on the page.

I still cannot reproduce this. It looks sharp on my end on the normal page.

Normally the iframe can not be changed by CSS around it as it is another context and the content is loaded from GitHub directly.

Can anyone else reproduce it?

**Comment by DanielRuf** [comment] 2018-02-19 14:44
Can you check it on another computer or account where the fonts of the system are untouched?

**Comment by wesinator** [comment] 2018-02-19 14:55
So toggling `line-height: 1.5;` https://github.com/zurb/foundation-sites/blob/2ceb09eb1d5226ce635e55278df52f4b530d815c/scss/_global.scss#L163 fixes the blur in Chrome:
![chrome_lineheight](https://user-images.githubusercontent.com/5124946/36383727-09be3f94-155b-11e8-9f83-99930ce97d44.png)

**Comment by DanielRuf** [comment] 2018-02-19 15:20
I guess this is only related to one of the fonts `"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif`.

Did you check your installed fonts? Because I can not reproduce it on any device.

**Comment by DanielRuf** [comment] 2018-02-19 18:26
Ok found the issue, an invisible space is the issue due to the positioning. Typical float / position issue. `font-size:0` fixes it.

**Comment by DanielRuf** [comment] 2018-02-19 18:30
Sorry, the initial question was not quite clear at the beginning. For docs there is also https://github.com/zurb/foundation-docs

**Comment by DanielRuf** [comment] 2018-02-19 19:18
See https://github.com/zurb/foundation-docs/pull/26

![image](https://user-images.githubusercontent.com/827205/36393896-e43f2f74-15b1-11e8-8db7-c1630d3a5297.png)

**Comment by DanielRuf** [comment] 2018-03-06 05:15
Closing as this should be fixed by https://github.com/zurb/foundation-docs/pull/26
Feel free to reopen if this is not the case.

**Closed by DanielRuf** 2018-03-06 05:15 UTC
Labels: PR open, docs
