### ISSUE TITLE
Off canvas left menu top li bug

### ISSUE THREAD

**Issue by zey91** [zurb/foundation-sites#10120] opened 2017-06-02 19:20 UTC
Hi, I'm newbie here. Whenever I opened the left off canvas menu and i hover outside of the top 'About' Iink, a bottom border line appears. I was just wondering if its a bug or its just how it works. I would like to remove the line if its possible though. Could you help me with this please? Thanks! #Foundation4life :)

<img width="385" alt="screen shot 2017-06-03 at 3 30 52 am" src="https://cloud.githubusercontent.com/assets/24209572/26741734/37b4346a-480d-11e7-9d29-f973f2a4a03f.png">

**Comment by IamManchanda** [comment] 2017-06-02 19:41
@zey91 Can you share code .... Fork one of the below codepen, add your code and we will love to help you resolve the issue even if its not a bug incase :wink:

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by IamManchanda** [comment] 2017-06-02 19:47
> Thanks! #Foundation4life :)

:+1:

**Comment by zey91** [comment] 2017-06-02 22:09
I not really sure if I've forked on your codepen but i think i did. haha Let me know if you've got it! Cheers

**Comment by zey91** [comment] 2017-06-03 04:51
Hey man, its fixed! I styled the outline: none; 
Thanks though :)

**Comment by IamManchanda** [comment] 2017-06-03 04:59
I am glad it was resolved... Closing this but feel free to have your say if you need more help :)

**Closed by IamManchanda** 2017-06-03 04:59 UTC
