### ISSUE TITLE
Print styles prevent SVGs from printing well

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#11717] opened 2019-03-06 21:36 UTC
By default you just get solid black SVGs, regardless of print settings. In my apps where I want to print SVGs, I've had to override the `foundation-print-styles()` mixin changing the CSS universal selector here… 

https://github.com/zurb/foundation-sites/blob/ff60ab247e9e3995d8a004c1aaae126ce7bb9b46/scss/typography/_print.scss#L20-L21

to this…  
```
 @media print { 
   *:not(svg) { 
```

**Comment by DanielRuf** [comment] 2019-03-06 22:25
Hi @andycochran,

It seems you have deleted our issue template.

Please fill it out and provide all details.

**Comment by DanielRuf** [comment] 2019-03-06 22:26
PS: Why not use `fill` instead of `currentColor`?

**Comment by DanielRuf** [comment] 2019-03-06 22:28
I would say it is not a bug (black is better for printing).

**Comment by DanielRuf** [comment] 2019-08-03 22:42
Closing as this might be the wished behavior by default and it can be overwritten in projects.

**Closed by DanielRuf** 2019-08-03 22:42 UTC

**Comment by andycochran** [comment] 2019-08-04 02:39
> black is better for printing 

🤔 

When I said "you just get solid black SVGs" I didn't mean e.g. that a red icon prints black. I meant that Foundation's print styles cause the entire SVG view box to be black (not just what's drawn in it). It's not that it's the wrong color. You cannot see the SVG's content at all; it's just a solid black box.

**Comment by DanielRuf** [comment] 2019-08-04 09:12
It probably depends on the svg. We could still see the icon shapes but with black fills in projects afaik. `color` should only affect shapes which have `currentColor` in an attribute.

**Comment by DanielRuf** [comment] 2019-08-04 09:12
If this is not the case please provide a reproducible testcase.
