### ISSUE TITLE
Can't start new email project - foundation new --framework emails

### ISSUE THREAD

**Issue by Jonesdl-2785** [zurb/foundation-sites#11756] opened 2019-05-22 18:51 UTC
## What should happen?
Foundation project queries should start in order to build project
...

## What happens instead?
Received an error

## Possible Solution

Update gulp and its dependencies.  Per gulp github issues support, there are outdated dependencies being used:
"We don't ship the graceful-fs that includes the natives module with gulp 4 - that version of graceful-fs is extremely old and you shouldn't be using it."
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. `sudo npm install --global foundation-cli`
2. `foundation new --framework emails`
3. 
`
[exec]fs.js:27
[exec]const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
   at fs.js:27:35
   at req_ (.../node_modules/natives/index.js:143:24)
   at Object.req [as require] (.../node_modules/natives/index.js:55:10)
   at Object.<anonymous> (.../node_modules/gulp-require-tasks/node_modules/graceful-fs/fs.js:1:37)
   at Module._compile (internal/modules/cjs/loader.js:759:30)
   at Module._compile (.../node_modules/pirates/lib/index.js:99:24)
   at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
   at Object.newLoader [as .js] (.../node_modules/pirates/lib/index.js:104:7)
   at Module.load (internal/modules/cjs/loader.js:628:32)
   at Function.Module._load (internal/modules/cjs/loader.js:555:12)
`

## Context

It has hinder my ability to use foundation to build email projects/templates.
...

## Your Environment

- Foundation version(s) used: 6
- Browser(s) name and version(s): chrome
- Device, Operating System and version: Windows 10, using Ubuntu 18.04
- Link to your project: N/A
 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2019-05-22 19:14
Hi @Jonesdl-2785,

this is a duplicate of https://github.com/zurb/foundation-sites/issues/11755

Please read https://github.com/zurb/foundation-sites/issues/11755#issuecomment-494736844

**Closed by DanielRuf** 2019-05-22 19:14 UTC

**Comment by DanielRuf** [comment] 2019-05-22 19:28
> 2\. --framework emails

Also this is https://github.com/zurb/foundation-emails
