### ISSUE TITLE
stacked button groups are always expanded

### ISSUE THREAD

**Issue by fvanderwielen** [zurb/foundation-sites#10693] opened 2017-10-04 12:15 UTC
#### How to reproduce this bug:

given a button group with 2 buttons, to stack on medium down breakpoints but are not expanded:
```HTML
<div class="button-group stacked-for-medium">
    <button type="button" class="button">button1</button>
    <button type="button" class="button">button2</button>
</div>
```
when I view this on a wider than medium breakpoint
then I expect the buttons to not use full width available to them and size normally, as they are not `.expanded`.

In other words, I would expect the following CSS:
```CSS
@media print, screen and (min-width: 64em) {
  .button-group.stacked-for-medium .button {
	flex: 0 0 auto;
	margin-bottom: 0;
  }
}

@media print, screen and (min-width: 64em) {
  .button-group.stacked-for-medium.expanded .button {
	flex: 1 1 auto;
	margin-bottom: 0;
  }
}
```
The above 

see also : https://codepen.io/ZURBFoundation/pen/bWMemL?editors=1000
related issue: https://github.com/zurb/foundation-sites/issues/7393

#### What should happen:
button group does not take full width

#### What happened instead:
button group does take full width, as if it were expanded

#### Browser(s) and Device(s) tested on:
Firefox 55.0.3 (32-bit)

#### Foundation Version(s) you are using:
 * Foundation for Sites by ZURB
 * Version 6.4.3

#### Test case link:
https://codepen.io/ZURBFoundation/pen/bWMemL?editors=1000

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by rafibomb** [comment] 2017-10-04 23:26
In other words - stacked is inheriting the expanded behavior. While this is expected when stacked, each button should be auto width otherwise.

**Comment by fvanderwielen** [comment] 2017-10-05 07:08
Is this inheriting intentional? It is not mentioned in the docs, nor are they conceptually in the same direction, stacked-for-small can be behavior that works on a button group with auto width as well...

**Comment by rafibomb** [comment] 2017-10-05 21:33
Not intentional, should not be this way - I just opened a PR #10703. Can you checkout the PR and let me know it works as expected?

**Comment by fvanderwielen** [comment] 2017-10-06 12:20
I checked out the PR / branch fix10693 on HEAD and it now works as expected, thanks!

My compliments also for the speed of fixing this, I am impressed!

**Comment by CirrusThink** [comment] 2017-10-13 15:13
Not sure what would or should not be but it is important that expanded and stack-for-x work together. Many cases where we want a button group to be expanded and then stacked when small. So far if i use expanded and stack-for-small together the buttons always stays stacked

**Comment by ncoden** [comment] 2017-12-24 23:18
@fvanderwielen Sorry for the late reply. I cannot reproduce your bug for `expanded` _and_ `stacked` buttons. I tried with BrowserStack on `Firefox v48 for Windows 7`.

Could you test again, or give me your precise version of Windows and Firefox ?

**Comment by ncoden** [comment] 2017-12-24 23:22
I merged https://github.com/zurb/foundation-sites/pull/10703, but I do not close this issue. I'll wait for the reply of @fvanderwielen.

**Comment by fvanderwielen** [comment] 2018-01-02 10:03
@ncoden I have the behavior as in the above screenshot in firefox 57.0.3 (64-bit) and Chrome 63.0.3239.84 (Official Build) (64-bit), both on Windows 7.

My test setup is using the following checkout of Foundation:
```
D:\dev\temp\foundation-sites-fix\foundation\foundation-sites>git log -n 1
commit 566989c3de27e3dba0b5b53c227820c5f893f862
Author: RafiBomb <rafi@zurb.com>
Date:   Thu Oct 5 14:46:54 2017 -0700
    adds use case for medium down and adds a visual test
```
(which is the last commit of pull request 10693)

What I find strange/unexpected is that, on screens smaller than medium, a div.button-group.stacked-for-medium.expanded does not have its stacked buttons expanded, like shown in the screenshot above. I would expect the buttongroup to be expanded also in this case.

I tried to wrap this all in a glitch example, but installing the demo app was too large for a glitch app.

**Comment by DanielRuf** [comment] 2018-04-06 20:54
https://github.com/zurb/foundation-sites/pull/10703#event-1400744147

It was merged in December and the PR number was higher.

**Closed** 2018-04-07 18:06 UTC
Labels: Button Group, awaiting reply, bug, scss
