### ISSUE TITLE
block-grid flex-grid

### ISSUE THREAD

**Issue by mmjaeger** [zurb/foundation-sites#8312] opened 2016-03-01 23:23 UTC
while playing around with block-grid and flex-grid I was wondering why there are still floats and clears - I don't think they are necessary, aren't they?

**Comment by gakimball** [comment] 2016-03-02 01:45
Duplicate of #8310, fixed via 4d6a363951029f1d75ed0e710fcd70572c2886a3

It'll be in the next patch release.

**Closed by gakimball** 2016-03-02 01:45 UTC
Labels: bug, scss
