### ISSUE TITLE
Customizer generates XY-grid example HTML when Flex grid chosen

### ISSUE THREAD

**Issue by simshaun** [zurb/foundation-sites#10934] opened 2018-02-13 00:26 UTC
Was trying to reproduce #9343 on a more recent version of Foundation and found this issue.

#### How to reproduce this bug:

1. https://foundation.zurb.com/sites/download/
2. De-select all components
3. Choose Flex Grid
4. Download

#### What should happen:

Example HTML should use Flex grid.

#### What happened instead:

Example HTML uses XY grid (which isn't included in the generated download).

#### Foundation Version(s) you are using:

6.4.2

**Comment by ncoden** [comment] 2018-02-13 00:36
Duplicate of https://github.com/zurb/foundation-sites/issues/10934

**Closed by ncoden** 2018-02-13 00:36 UTC
Labels: customizer, duplicate

**Comment by simshaun** [comment] 2018-02-13 00:45
@ncoden Did you mean to close both this one and #10449?

**Comment by ncoden** [comment] 2018-02-13 00:55
I meant https://github.com/zurb/foundation-sites/issues/10636 sorry.
