### ISSUE TITLE
change event for sliders

### ISSUE THREAD

**Issue by n0o0bSina** [zurb/foundation-sites#8264] opened 2016-02-27 20:58 UTC
How can i handle foundation sliders changes not moves?
I need this for ajax calls.

**Comment by Deckluhm** [comment] 2016-02-27 22:27
I'm not sure I understood your question but this might be what you are looking for: http://foundation.zurb.com/sites/docs/slider.html#js-events

**Comment by n0o0bSina** [comment] 2016-02-28 08:54
@Deckluhm You'r right but in that page there is only `moved.zf.slider` event i need `changed.zf.slider`.
`moved.zf.slider` is equal of http://api.jqueryui.com/slider/#event-slide
but i need http://api.jqueryui.com/slider/#event-change
this event is very important if you need sliders value for ajax calls.

**Comment by gakimball** [comment] 2016-02-29 19:57
Merged #8286 which implements this. Thanks @Owlbertz!

**Closed by gakimball** 2016-02-29 19:57 UTC
Labels: feature, javascript, PR open

**Comment by ZeeAzmat-qbx** [comment] 2016-03-30 10:33
I have the same problem. I need **changed** event instead of **moved**, and tried using **changed** but it doesn't work. Can you please help me on this?

**Comment by Owlbertz** [comment] 2016-03-30 10:41
What version of Foundation are you using? PR #8268 should add the changed event. This is not in 6.2 yet I believe, but 6.2.1 will come up later this week iirc, which should have this implemented.

**Comment by ZeeAzmat-qbx** [comment] 2016-03-30 10:43
I am using version 6, and what i am looking for is the somewhat RELEASE
method for slider. So instead of "moved" method i can use "released"
method, whenever i release the slider event gets triggered and i can make
the AJAX request on that value.

**Comment by Owlbertz** [comment] 2016-03-30 10:45
The idea of what was merged with the PR mentioned is an event that will trigger when the slider has not been moved for a given time, by default 500ms. Would that fit your needs?

**Comment by ZeeAzmat-qbx** [comment] 2016-03-30 10:47
Yeah exactly i was looking for something like this. But that didn't fulfill
my needs.

**Comment by ZeeAzmat-qbx** [comment] 2016-03-30 10:48
The code i am using is:

$('#dropdown--price-slider').on('changed.zf.slider', function(e, handle) {
console.log ("changed"); });

  $('#dropdown--price-slider').on('moved.zf.slider', function(e, handle) {
    var currentAttribute = handle.attr('aria-valuenow');
    var parentValueLabel =
$(this).parent('.dropdown-pane').find('.slider-value');

    parentValueLabel.each( function() {
      $(this).text(currentAttribute);
    });
    console.log (currentAttribute);
  });

In second function i am updating the values as per the slider moves,  and
in the first function i am looking to get the value of slider when it stops
and make the AJAX request.

**Comment by Owlbertz** [comment] 2016-03-30 19:38
I guess I don't get your requirements correctly.... From what I understood you don't need your second function, but you could use [data binding with slider](http://foundation.zurb.com/sites/docs/slider.html#data-binding) and in your first function you could then either check the value of the input or the `aria-valuenow` attribute of the `handle` passed as an argument to the function (as you correctly stated in your code).

Maybe you could give me some real-life code on a actual website?

**Comment by ZeeAzmat-qbx** [comment] 2016-03-31 02:00
Value of input doesn't get updated as the slider moves, that's why the
second function is there. But the problem is I can't make my request in
second function becuase it gets called everytime the value is changed, so
if i move the slider from left to right and the range is let's say 1-1000
so the second function will be called for 1000 times. That's the main
issue, i need a function/event which gets called when the value is not
updated for some time.

I don't have any actual website to show you, as the project is still in
development.

**Comment by whokilledtheelectricmonk** [comment] 2016-04-01 07:00
It would be useful if this could be set up to fire a change event on any bound inputs after a few ms. Then @ZeeAzmat-qbx could just use a hidden input and listen on that for changes. Right now the value changes but no event fires unless you manually enter something the number field.
