### ISSUE TITLE
Split dropdown doesn't work with <button> tag, it only works with <a> tag

### ISSUE THREAD

**Issue by prahladyeri** [zurb/foundation-sites#6998] opened 2015-11-12 00:24 UTC
I've recently started working on Zurb Foundation (superb framework, btw). I'm currently facing one minor issue in version 5.5.3. The [Split Dropdown](http://foundation.zurb.com/docs/components/split_buttons.html) functionality is not working with `<button>` tags, however, it does work with hyperlinks or `<a>` tags. To reproduce the issue, I've created the following jsfiddle with an example:

https://jsfiddle.net/fb66L6gd/

I'm running Firefox 41 on Ubuntu 14.04 LTS if that helps.

**Comment by prahladyeri** [comment] 2015-12-24 00:56
Over one month and still no response! Didn't expect this from Zurb Foundation.

**Comment by zurbchris** [comment] 2016-01-18 22:12
@prahladyeri sorry homie, we were swamped with Foundation 6 launching at the time. I'm a little fuzzy on what isn't working on your fiddle, it *seems* to be working as intended? I'll leave this open for a few days just in case you're still in need assistance.

**Comment by prahladyeri** [comment] 2016-01-19 13:02
@zurbchris What isn't working in my scenario is a very specific thing: the `split dropdown` feature. When I originally created this bug, I was try to add this feature in one of my apps. If you go to my fiddle, and click the problematic button labeled "Not Working", the split-dropdown is not opening. Please note that I've created this button using the `<a>` tag. So with `<a>` tags having the `button split` button split classes:

**Expected Behavior:** The split-dropdown should open when clicked.
**Actual Behavior:** The split-dropdown is not opening when clicked.

Hope that makes sense.

**Comment by IAmEddieDean** [comment] 2016-01-19 15:31
From your fiddle: 
![image](https://cloud.githubusercontent.com/assets/11634585/12423061/93629988-be7e-11e5-886e-a6b6702ca1d1.png)
Seems to be working?

**Comment by prahladyeri** [comment] 2016-01-19 15:47
Well, that's abysmally strange as that very link is still not working for me :astonished: Are you linking to this same foundation resources that I'm linking?

`https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/foundation.min.css`
`https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/foundation.min.js`

I'm trying it from Ubuntu instead of a smart device, is that the difference?

**Comment by IAmEddieDean** [comment] 2016-01-19 15:49
That's your fiddle, unedited. I tested this on my laptop yesterday as well,
so it's not just my phone. Sounds like there's something more difficult
here.

**Comment by zurbchris** [comment] 2016-01-20 00:54
Checked in on firefox, something broke there. We'll have to take a deeper look at this to see what the issue is. Please let me know if you have any JS errors in your console.

**Comment by prahladyeri** [comment] 2016-01-20 07:27
Nope, the browser console is empty.

**Comment by rafibomb** [comment] 2017-10-03 21:36
A PR would be merged for this. We'll close this here - thanks!

**Closed by rafibomb** 2017-10-03 21:36 UTC
Labels: Foundation 5
