### ISSUE TITLE
Topbar + Sticky == Behavioural bug

### ISSUE THREAD

**Issue by ricardo-lewis** [zurb/foundation-sites#5614] opened 2014-08-14 04:43 UTC
I'm running a Sticky Top Bar.

Here's what I can do to trigger a bug in Chrome:

1. With no Stickiness active, activate the mobile Top Bar with a narrow widow width.
2. Scroll down to trigger the sticky/fixed behaviour.
3. Widen the window past the breakpoint to trigger the full non-mobile Top Bar.
4. Scroll back up in vain as both the **f-topbar-fixed** and **fixed** CSS classes are not removed when you reach the top of the window.

A similar behaviour can be observed on the Docs page if your browser window is just less than 1024px (inside the medium breakpoint) http://foundation.zurb.com/docs/components/topbar.html

Notice how you must scroll **far above** the original Y position of the Sticky Menu in order to un-sticky it. Now imagine if the Top Bar was actually at the top of the screen: you wouldn't be able to scroll above it at all and it would remain forever sticky because the CSS classes are not removed.

**Comment by rafibomb** [comment] 2015-10-09 05:36
I did confirm this. I don't know what the issue is just yet. Have you been able to work around it or find a solution? We'd love to hear an ideas you have on it

**Comment by rafibomb** [comment] 2015-10-09 23:03
Looks like there is a window resize event in top-bar it's just not doing anything. If anyone else experiencing this and found a solution?

**Comment by zurbchris** [comment] 2016-01-20 01:13
Closing due to staleness.

**Closed by zurbchris** 2016-01-20 01:13 UTC
Labels: Foundation 5
