### ISSUE TITLE
Dropdown submenus close on touch scroll gesture

### ISSUE THREAD

**Issue by jitens** [zurb/foundation-sites#9823] opened 2017-03-01 14:33 UTC
#### How to reproduce this bug:

1. Trigger Item 1 menu dropdown
2. Move down / touch gesture down the page

Bug occurs in both 6.3.0 and 6.3.1 Foundation versions 

#### What should happen:
The submenu should stay open, otherwise if the submenu is larger than the viewport the submenu items aren’t reachable.

#### What happened instead:
The submenu closes after moving down / touch gesture down the page.
#### Test case:

- [Test Dropdown Menu with Foundation 6.3.0]( http://documentation.knowledgekube.co.uk/test-foundation/dropdown-6-3-0/)
- [Test Dropdown Menu with Foundation 6.3.1]( http://documentation.knowledgekube.co.uk/test-foundation/dropdown-6-3-1/)

**Comment by IamManchanda** [comment] 2017-03-01 14:41
Sorry i am unable to reproduce ...can you specify which device your are using!

**Comment by jitens** [comment] 2017-03-01 14:48
Hi I have tested it on iPad Pro iOS 10 using BrowseStack.

**Comment by kball** [comment] 2017-05-31 23:41
OK, so the issue here is that dropdown is closing on a click outside the dropdown itself, and the dropdown event listener doesn't seem to be distinguishing between a touch drag and a simple touch.

Unfortunately with the current touch event handling it is not at all obvious to me how to fix this...

This is a point in favor of replacing the current touch handling with Hammer.js or a similar.

For now going to move this out to 6.5 milestone.

**Comment by jitens** [comment] 2017-07-20 13:58
Thanks, hopefully this resolves the issue in the future.

**Closed** 2018-03-30 19:47 UTC
Labels: Dropdown Menu, PR open, bug
