### ISSUE TITLE
F6 - Topbar&Drilldown width mis-calculation

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#7774] opened 2016-01-06 07:48 UTC
When resizing the browser the inline width of the ".is-drilldown" class doesn't change, which means an overflow. Is this a bug?

http://i64.tinypic.com/3509ny0.png

Ps: Overriding the inline style by adding "width: 100%!important" to the ".is-drilldown" class will fix this issue.

**Comment by zurbchris** [comment] 2016-01-21 17:43
So this is a bit of a tricky issue. If you're *not* using a responsive menu plugin, we recommend using a container div and applying your sizing styles directly to that. In our own documentation, we're applying an inline style to the root `<ul>` element for the menu, which is where the size is drawn from there, and a defined width of that value is applied to the container the drilldown is wrapped in. I'm all for hearing options on how best to manage this. When I was developing it initially, I needed to manage the width of the container for showing/hiding purposes.

**Comment by Silvester20** [comment] 2016-01-22 11:08
The only thing I know is to remove the inline style width, then it will work for responsive and not responsive when it is inside a container.

**Comment by colin-marshall** [comment] 2016-04-29 17:24
@Silvester20 I'm closing this issue because we don’t have a reproducible case to test against. If this is still an issue, please reopen with the info requested here:
https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

**Closed by colin-marshall** 2016-04-29 17:24 UTC
Labels: bug, javascript
