### ISSUE TITLE
input-group, height of button and input differs

### ISSUE THREAD

**Issue by ModulaShop** [zurb/foundation-sites#7422] opened 2015-12-06 12:57 UTC
input has height of 39px, buttons are 40px 

can see it here in the examples, too:
http://foundation.zurb.com/sites/docs/forms.html#inline-labels-and-buttons

Chrome 48 on OSX

**Comment by TvrtkoM** [comment] 2015-12-06 18:09
seems like setting button *padding: 0.8em 1em;* decreases the height of it to height of the text input. It's also possible to decrease font-size to get similar result. Also if apply button size class (tiny, small, default ...) is applied only button changes size and looks bigger or smaller than text input.

Maybe add separate styling for buttons inside forms or inline-group elements?

**Comment by gakimball** [comment] 2015-12-07 17:06
Duplicate of #7373

**Closed by gakimball** 2015-12-07 17:06 UTC
