### ISSUE TITLE
[Orbit] locked after a few slide on iPad only

### ISSUE THREAD

**Issue by stephane-r** [zurb/foundation-sites#9914] opened 2017-03-29 09:45 UTC
Hi community,

I see a bug on Orbit slider, only on **iPad (iOS 10.0.2 (14A456))**, Safari and Chrome browser latest version.

When i slide to the last item and i back to left, the carousel is hide and locked.

I've get a bug screenshot from Orbit Foundation Doc  :

![img_0010](https://cloud.githubusercontent.com/assets/4712791/24448429/712ee392-1474-11e7-88b9-1e6a285c0e2c.jpg)

#### How to reproduce this bug:

It's specific :D

1. You need to slide on the last item
2. And test left/right slide, and you see the item become 'hide'

#### Test case:

Directly from Orbit Foundation Doc with iPad.

**Comment by IamManchanda** [comment] 2017-03-29 17:02
@LeG3nDz 
Seems like that this is a,
 
Dupe of #9788,
PR open at #9881

**Comment by JeremyEnglert** [comment] 2018-02-10 01:55
Looks like the fix for this was merged. Closing.

**Closed by JeremyEnglert** 2018-02-10 01:55 UTC
