### ISSUE TITLE
[Reveal] Reveal doesn't work on iOS Safari

### ISSUE THREAD

**Issue by martinpesout** [zurb/foundation-sites#8008] opened 2016-01-26 08:29 UTC
**How can we reproduce this bug?**

1. Open http://foundation.zurb.com/sites/docs/reveal.html on iPad Safari
2. Try fullscreen example http://foundation.zurb.com/sites/docs/reveal.html#full-screen
3. Try to scroll when you have open fullscreen modal window

**What did you expect to happen?**

I expect that I will be scrolling only inside modal window.

**What happened instead?**

I scroll with content behind and modal window disappear.

**How to solve it**

I've found that solution can be adding `overflow: hidden;` to `<html>` tag when you open modal window. And remove this property when you close modal window.

**Comment by gakimball** [comment] 2016-01-26 17:27
Duplicate of #7548

**Closed by gakimball** 2016-01-26 17:27 UTC
Labels: bug, scss
