### ISSUE TITLE
[Top Bar] the default link styling is illegible

### ISSUE THREAD

**Issue by pmeissner** [zurb/foundation-sites#7399] opened 2015-12-04 16:09 UTC
**How can we reproduce this bug?**

Check out the sample here: http://foundation.zurb.com/sites/docs/top-bar.html#basics

**What did you expect to happen?**

The links to be legible.

**What happened instead?**

They are white in the navbar with a light grey background. And even worse the dropdowns have a white background rendering them invisible.

**Test case**

Sample on this page: http://foundation.zurb.com/sites/docs/top-bar.html#basics

![screen shot 2015-12-04 at 11 02 29 am](https://cloud.githubusercontent.com/assets/392386/11594289/24ffd38c-9a77-11e5-9f91-8fc704e916f0.png)

**Comment by rafibomb** [comment] 2015-12-04 16:39
Hmmm, we can trace this back to something in the last release 6.0.5

**Comment by gakimball** [comment] 2015-12-04 21:53
Issue was caused by 85a977bae630109e97a9971160221e4d0f85096a

Fixed via 9bf0552ef5f737c1e209e9efd5c2e76b05afbdbe

**Closed** 2015-12-04 21:53 UTC
Labels: bug, scss
