### ISSUE TITLE
Reveal modal not being positioned correctly

### ISSUE THREAD

**Issue by andreasgoth** [zurb/foundation-sites#7333] opened 2015-12-01 14:44 UTC
It seems like without  `html, body { height: 100%; }` the reveal modals won't position centered correctly. However that bit of CSS is included in _off-canvas.scss:46, so everything works fine if off-canvas is included in the SCSS.

**Comment by twd3** [comment] 2015-12-01 17:55
Where are you seeing them positioned? I was using the full download from the site and they were all positioned at the bottom of the page. After I downloaded the full from github (6.04) the positioning was fixed.

If you're talking about how the body jumps a bit to the right when the modal is clicked that is happening because of: body.is-reveal-open {overflow: hidden;}

What I want to know is why can't I get a modal to animate like in the docs?

**Comment by andreasgoth** [comment] 2015-12-01 18:52
Here is what i mean, using 6.0.4 with @include foundation-off-canvas; commented out: http://jsfiddle.net/hzp2jvv6/

**Comment by twd3** [comment] 2015-12-01 19:49
That example centered for me. Are you talking about the vertical center?

BTW I forgot that I needed to include the motion ui css for reveal to animate, I thought it was included since the motion ui js was.

**Comment by andreasgoth** [comment] 2015-12-01 21:27
Hm, weird. Yes, vertical center.

**Comment by zzplab** [comment] 2015-12-03 18:09
I can confirm the issue @andreasgoth described when using v6.0.5. I had the same problem and can confirm the solution mentioned in this first post.

**Comment by zurbrandon** [comment] 2015-12-11 22:00
I'm seeing this as fixed in 6.0.5, are you guys still having issues

http://codepen.io/zurbrandon/pen/EPVPQv

Everything seems to be centering fine both horizontal and vertical.

**Comment by andreasgoth** [comment] 2015-12-13 16:35
That is with all styles. My issue was without _off-canvas.scss. Looks like it is not fixed in 6.0.5.

**Comment by zurbrandon** [comment] 2015-12-17 22:02
Ah so something we're doing to the body with offcanvas makes this work correctly. I'll need to check it out with and without.

**Comment by pbent** [comment] 2015-12-20 17:50
For me it works with _off-canvas.scss included and scrolls to weird locations without it. Appears to be related to the calculation of "top" by "Foundation.Box.GetOffsets".

**Comment by ngt500** [comment] 2016-01-05 22:02
Version 6.1.1 I am still seeing this issue.
If I add: var elem = new Foundation.Reveal($('#targetModal'));
  elem.open();
The modal will open up centered and function as normal.
If I use the data-open with an anchor tag it pushes it down the page in to an unscrollable region. Also after clicking the close box the transparent overlay does not go away.

**Comment by danielck** [comment] 2016-01-11 09:32
I can confirm this with 6.0.5 and 6.1.1. Only the scrolling issue though, not the "transparent overlay not going away" issue. Just adding `html, body { height: 100%; }`  seems to be enough to fix the scrolling.

**Comment by zurbchris** [comment] 2016-01-29 18:26
Hello everyone, if you have a moment, please checkout [this branch](https://github.com/zurb/foundation-sites/tree/update-reveal) and see if this solves (most of) your issues. The positioning is much more reliable, though currently set to position vertically based on a pixel value from the top of the viewport, I also have the fn tucked away to position absolute center (x, y). If you can take a look before it goes into the 6.2 branch, that would be awesome!

**Comment by christianmagill** [comment] 2016-02-02 14:14
When I switch to that branch via " bower install foundation-sites#update-reveal --save" my modal no longer executes via the trigger link. No errors, just no results and other Foundation Javascript is running executing fine.

I'm also having another issue with the regular 6.1.2 release where a fullscreen modal doesn't compensate for space where the scroll bar was on Chrome. So you click for full screen modal, the modal covers everywhere but the space previously occupied by the scrollbar.

**Comment by christianmagill** [comment] 2016-02-02 14:35
My fullscreen modal issue seems to be solved by adding 

`html{ overflow-y: scroll;}`

**Comment by gakimball** [comment] 2016-02-05 23:03
Fixed via 330018d577bfbdaf30dad96fa6a05e4a074419e6

**Closed by gakimball** 2016-02-05 23:03 UTC
Labels: bug, scss
