### ISSUE TITLE
Textarea has border while inputs have not

### ISSUE THREAD

**Issue by riksoft** [zurb/foundation-sites#11026] opened 2018-03-08 18:01 UTC
#### How to reproduce this bug:

1. Foundation custom with float grid only.
2. Put an input + textarea in an html page
3. The textarea has a border (3d appearance)

#### What should happen:
The textarea should stay plain as the input box

#### What happened instead:
The texarea is turned into 3d

#### Browser(s) and Device(s) tested on:
Firefox 58-60 on PC with Linux

#### Foundation Version(s) you are using:
6.4.2 (the only that comes in Custom mode)

The problem is in line 457
```
textarea {
  height: auto;
  min-height: 50px;
  border-radius: 3px; }  <--- THIS IS THE PROBLEM
```

**Comment by DanielRuf** [comment] 2018-03-08 18:07
3d?

I guess you mean the input-radius.

https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_text.scss

**Comment by colin-marshall** [comment] 2018-03-08 18:25
`$input-radius` uses the `$global-radius` setting which defaults to 3 in the customizer. Change that to 0 before you download your custom Foundation.

<img width="644" alt="screen shot 2018-03-08 at 11 16 06 am" src="https://user-images.githubusercontent.com/4453733/37168453-2ab1474a-22c2-11e8-9f1c-3feb0ac20be4.png">

**Comment by DanielRuf** [comment] 2018-03-08 18:28
Ah, saw your answer now @colin-marshall. Right, this should reset it.

**Comment by colin-marshall** [comment] 2018-03-08 18:32
I wonder why the global-radius defaults to 3 on the customizer, but defaults to 0 in the default settings file. Seems like there should be parity between default customizer settings and the default settings file.

**Comment by DanielRuf** [comment] 2018-03-08 19:06
The inputs have 3px border-radius, so this is correct.

![_c__users_daniel_desktop_foundation-6 4 2-custom_index html](https://user-images.githubusercontent.com/827205/37170814-37a10784-230c-11e8-8453-ff5aabcf09c9.png)

**Comment by DanielRuf** [comment] 2018-03-08 19:10
With a setting of 0:

![_c__users_daniel_desktop_foundation-6 4 2-custom 20 1 _index html](https://user-images.githubusercontent.com/827205/37170991-ba45a8e8-230c-11e8-8224-2d8f06ccd806.png)

**Comment by colin-marshall** [comment] 2018-03-08 19:13
I was referring to this:
https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L92

**Comment by DanielRuf** [comment] 2018-03-08 19:17
> I was referring to this:
> https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L92

I know. I just wanted to show that changing the value to 0 "fixes" the "issue" of @riksoft

**Comment by colin-marshall** [comment] 2018-03-08 19:18
Ahhh. My bad, I misunderstood.

**Comment by riksoft** [comment] 2018-03-08 19:34
With border-radius:3px or 0px the problem is the same: the textarea get the 3d aspect. The only way to avoid it is not writing border-radius at all, because there is no way to override the behaviour (e.g. border-radius:0px or initial doesn't work).
As soon as Firefox find a mention of textarea{border-radius: <anything>}, even border-radius:0,  the old fashion 3d aspect comes out and there is not way to get rid of it.
That's why I have to delete the declaration manually from the custom download of Foundation.

**Comment by riksoft** [comment] 2018-03-08 19:41
To be more clear what I mean with "Old fashion 3D stryle/aspect"...
This is what I get with foundation.
![screenshot at 2018-03-08 17-08-52](https://user-images.githubusercontent.com/5039496/37172226-1710274c-2308-11e8-94a1-162bf140ccc5.png)

This is what I want and what I get after removing textarea{border-radius:3px} from the Foundation css.
![screenshot at 2018-03-08 19-36-20](https://user-images.githubusercontent.com/5039496/37172287-47f19b34-2308-11e8-9e1f-df21f0ed9c27.png)

setting border-radius:0px doesn't solve the problem for Firefox, must be completely absent. Probably there is a workaround to override it? Let me know. It's quite inconvenient to remember to modify Foundation every time.

**Comment by DanielRuf** [comment] 2018-03-08 19:52
> With border-radius:3px or 0px the problem is the same: the textarea get the 3d aspect. The only way to avoid it is not writing border-radius at all, because there is no way to override the behaviour (e.g. border-radius:0px or initial doesn't work).

Do you mean the box-shadow?

**Comment by DanielRuf** [comment] 2018-03-08 19:53
Which exact browser do you use?

**Comment by DanielRuf** [comment] 2018-03-08 19:57
This is Firefox 55:

![image](https://user-images.githubusercontent.com/827205/37173238-4cc358ea-2313-11e8-8f91-ab2ab7bd0536.png)

**Comment by DanielRuf** [comment] 2018-03-08 20:02
And this is Firefox 58:
![image](https://user-images.githubusercontent.com/827205/37173487-04a35910-2314-11e8-9a5c-db7439889913.png)

**Comment by DanielRuf** [comment] 2018-03-08 20:05
See https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance#Browser_compatibility and https://foundation.zurb.com/sites/docs/compatibility.html

**Comment by riksoft** [comment] 2018-03-09 11:40
Please, concentrate :-)
As I said: Firefox from 58 to 60 and custom download of float grid **ONLY**

**Comment by DanielRuf** [comment] 2018-03-09 11:51
Did you enable the forms component in the customizer?

**Comment by DanielRuf** [comment] 2018-03-09 11:52
See https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_text.scss#L128

**Comment by DanielRuf** [comment] 2018-03-09 11:56
Using the form component with using the form styles make snot much sense ;-)

Left with the form component enabled in the customizer, right without:
![bildschirmfoto 2018-03-09 um 12 55 17](https://user-images.githubusercontent.com/827205/37206527-3d3000a0-2399-11e8-91ac-9283642c66bb.png)

**Comment by DanielRuf** [comment] 2018-03-09 11:58
And also see https://codepen.io/DanielRuf/pen/eMYaxJ

**Comment by riksoft** [comment] 2018-03-09 12:04
Make sens to me because I only want a grid, not form components. On the customizer I've deselected anything and selected float grid only.

I've tested also on Windows:
Same problem on Windows with FF 58.
Same problem on Windows 10 with edge and FF 58.
No problem instead on Windows Chrome 63 - 65.
No problem on Windows Opera 51.

**Comment by DanielRuf** [comment] 2018-03-09 12:18
> I've tested also on Windows:
> Same problem on Windows with FF 58.
> Same problem on Windows 10 with edge and FF 58.
> No problem instead on Windows Chrome 63 - 65.
> No problem on Windows Opera 51.

This is Firefox specific and their default styling for the textarea and their behavior for its appearance by default.

Not a bug in Foundation Sites per se so I'm closing this here.

Chrome / Chromium (Opera also uses Chromium) has other appearance styles on form elements. Microsoft too. Only using the form component adds the resets and styles for form elements.

**Closed by DanielRuf** 2018-03-09 12:18 UTC
Labels: customizer, question

**Comment by riksoft** [comment] 2018-03-09 12:33
I've solved in a better way:
since I only want the float grid and the Fondation customizer wrongly insert also unwanted form modifications, I've removed the lines from the end of normalize to line 522
basically from
.foundation-mq {
to the line before
.row {

Now the pages keep my style and at the same time I have the grid.
What is the reason why the Fondation customizer adds half form component style when selecting a grid only?

**Comment by riksoft** [comment] 2018-03-09 12:42
By the way...
> This is Mozilla Firefox (and MS) specific and their default styling for the textarea and their behavior for its appearance by default.

It's not true because the default style is runied only by foundation. That's why removing the unwanted lines from foundation, everything is fine now. The problem would be nicely solved, if the customizer didn't modify the form components when I select to download the grid only. This is the real bug.

**Comment by DanielRuf** [comment] 2018-03-09 13:11
> since I only want the float grid and the Foundation customizer wrongly insert also unwanted form modifications

There is nothing form related added. Just the global styles from normalize I guess.

**Comment by DanielRuf** [comment] 2018-03-09 13:12
> What is the reason why the Fondation customizer adds half form component style when selecting a grid only?

You mean the border-radius in general? Is is a global style and not tied to the form component as it seems. This might be the only issue here. Not the appearance of the vendors.

**Comment by DanielRuf** [comment] 2018-03-09 13:13
> It's not true because the default style is runied only by foundation.

No, see my codepen, there is just that what you see in the html and css tab, nothing more.

**Comment by DanielRuf** [comment] 2018-03-09 13:14
> It's not true because the default style is runied only by foundation. That's why removing the unwanted lines from foundation, everything is fine now.

Just set the border-radius to 0. This should "fix" it.

**Comment by DanielRuf** [comment] 2018-03-09 13:17
https://github.com/zurb/foundation-sites/blob/31a199666b13daacf317f1b96e098015e7615626/scss/_global.scss#L189

**Comment by DanielRuf** [comment] 2018-03-09 13:18
https://github.com/zurb/foundation-sites/commit/615d90ba5920879e6428727f9f95ab83a34e37da

**Comment by DanielRuf** [comment] 2018-03-09 13:20
@colin-marshall should we move this to the form component? But it seems the global styles set some styles for form elements so there are definitely more changes and not only the grid or something else.

**Comment by DanielRuf** [comment] 2018-03-09 13:25
In your case I would suggest the sass version where you can include just the grid without the global styles which are always included in the customizer and default import.

**Comment by riksoft** [comment] 2018-03-09 13:38
> There is nothing form related added. Just the global styles from normalize I guess.

This is the part of Foundation CSS that is after Normalize and before the grid itself.

```
.foundation-mq {
  font-family: "small=0em&medium=40em&large=64em&xlarge=75em&xxlarge=90em"; }

html {
  box-sizing: border-box;
  font-size: 100%; }

*,
*::before,
*::after {
  box-sizing: inherit; }

body {
  margin: 0;
  padding: 0;
  background: #fefefe;
  font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
  font-weight: normal;
  line-height: 1.5;
  color: #0a0a0a;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale; }

img {
  display: inline-block;
  vertical-align: middle;
  max-width: 100%;
  height: auto;
  -ms-interpolation-mode: bicubic; }

textarea {
  height: auto;
  min-height: 50px;
  border-radius: 3px; }

select {
  box-sizing: border-box;
  width: 100%;
  border-radius: 3px; }

.map_canvas img,
.map_canvas embed,
.map_canvas object,
.mqa-display img,
.mqa-display embed,
.mqa-display object {
  max-width: none !important; }

button {
  padding: 0;
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
  border: 0;
  border-radius: 3px;
  background: transparent;
  line-height: 1;
  cursor: auto; }
  [data-whatinput='mouse'] button {
    outline: 0; }

pre {
  overflow: auto; }

button,
input,
optgroup,
select,
textarea {
  font-family: inherit; }

.is-visible {
  display: block !important; }

.is-hidden {
  display: none !important; }

```


> Just set the border-radius to 0. This should "fix" it.

That's the first thing I tried, but as I said in my 2nd post, **it's impossibile to ovverride**. It works in codepen because there is no foundation involved, but not in real case scenario because there is something else that influences such behaviour and I can't check the entire fondation css.  **Removing the statement** (textarea{border-radius}) is the only way to solve the problem. I haven't found any way to override it.

> should we move this to the form component?

Should be nice.

> In your case I would suggest the sass version

For me it's not a big problem to change the CSS manually, but for the sake of others, styling the world should be avoided when one choose only a grid, otherwise we loose the scope of choosing a single component.

**Comment by DanielRuf** [comment] 2018-03-09 14:04
> That's the first thing I tried, but as I said in my 2nd post, it's impossibile to ovverride.

Huh? I set it to 0 in the customizer and I got the following in Firefox 58:

![bildschirmfoto 2018-03-09 um 15 03 22](https://user-images.githubusercontent.com/827205/37211087-1ab3ead4-23ab-11e8-8507-a897b2f64acc.png)

**Comment by DanielRuf** [comment] 2018-03-09 14:06
Removing the border-radius rule on this single textarea makes no difference in Firefox.

**Comment by DanielRuf** [comment] 2018-03-09 14:09
Weird, Firefox adds the shadow when it is also set to 0. When we remove the rule it does not add the shadow. For me it is a Firefox rendering bug in the normal appearance of the textarea element.

**Comment by DanielRuf** [comment] 2018-03-09 14:11
Adding `border: 1px solid;` fixes it.

**Comment by DanielRuf** [comment] 2018-03-09 14:48
There you go: https://bugzilla.mozilla.org/show_bug.cgi?id=1444396

We can not set `none` in the customizer. Even `0` produces this issue in Firefox.

**Comment by riksoft** [comment] 2018-03-09 15:46
I know, that's why I was saying there is no way to override the border-radius:3px you've set in Foundation.
However, I've just found a workaround:
border:1px solid
border-color: initial

**but it only works without Foundation.**
Probably there is something else that influence the behaviour of FF.

**Comment by riksoft** [comment] 2018-03-09 15:59
Uhm... no... I was wrong its a bug FF+Codepen: when I change something, codepen or FF remember the previous setting and that change the behaviour in the real world (that is, the first load of the page).
In other words, on codepen what you is IS NOT what you get in the first load of the page. In other words, a sequence of modification in the editor is not the same as the same code executed at page load. Bug of codepen or firefox... I don't know but it's a bug.
So my workaround is not working, was only a positive effect of the bug of codepen/FF.

**Comment by DanielRuf** [comment] 2018-03-09 16:11
Try the debug mode then: https://codepen.io/DanielRuf/debug/xWbxva

**Comment by riksoft** [comment] 2018-03-09 16:44
I must say that every browser is s..t!
Apart from my problem with border-radius, try to find a way to revert
textarea{border-style:inset}
I've tried everything. No way.

e.g.
textarea{
	-webkit-border-radius: initial;
	-moz-border-radius: initial;
	-o-border-radius: initial;
	border-radius: initial;
	border: initial
Not working

Same with "unset" attribute: not working
Not on Firefox nor on Chrome (both latest versions).
On Chrome, border-style:initial remove the border completely.

Same for the border-color: there is not way to revert a change because initial turns to black both on FF and Chrome. Same usding unset instead of initial.

Chrome has the only advantage that border-radius:0 can revert border-radius:1px, but same problem for all other attributes of the border.

**Comment by DanielRuf** [comment] 2018-03-09 16:59
> I must say that every browser is s..t!

Well, that is why we apply `appearance: none` in the forms component.

**Comment by riksoft** [comment] 2018-03-09 17:12
Yeah, in fact using the entire framework is not a problem. The problem arises in the half way, just like my case where I downloaded only the grid but the css also brings in some setting that I think should be in the form module only.

Basically the only 2 ways to go are:
1) Not touching the defaults because the attribute "initial" is useless on every browser on planet. Even the simple use of textarea{border: 1px solid} implicity add border-color:black both on Chrome and FF instead of keeping the initial value and cannot be reverted. It's a mess. 

2) Setting everything to be sure of every value, just like BS, Foundation, and many other frameworks. The problem is that not eveyone want do that because there is already a project with it's own style.

In my case I need point 1, so I would benefit of a better separation of code in Foundation components.

**Comment by riksoft** [comment] 2018-03-09 17:33
In the customizer I've checked float grid + Forms. "Forms" remove the border so it solves the problem of the inset 3D, however introduces more complex problems to me. E.g. 
1) I've lost the responsiveness: everything stay on "small" setting.
column small-12 medium-3 doesn't work anymore.

2) A <form> that was OK, centered in the page, is now has:
a) micro labels
b) the labels are still centered as they should
c) but the input are on the contrary all the way left

so I'd better to stick to my solution of downloading the grid and removing manually the code that damage the textarea.

**Comment by DanielRuf** [comment] 2018-03-09 17:49
> I've lost the responsiveness: everything stay on "small" setting.
column small-12 medium-3 doesn't work anymore.

That should not be. Please open a new issue for this with a codepen.

**Comment by DanielRuf** [comment] 2018-03-09 17:51
Same for the other.

**Comment by DanielRuf** [comment] 2018-03-09 17:52
@colin-marshall what do you think should we do with the cudtomizer issue (`border-radius: none` not possible?

**Comment by riksoft** [comment] 2018-03-09 18:51
> That should not be. Please open a new issue for this with a codepen.

About the point 1 (the loss of responsiveness)
probably is because the float grid is not included in the "Complete" download.

About the problem 2 (inputs that go on the left and micro labels that stays on the center)
it's only a matter of making the html form specific for Foundation in the first place. Adding "Forms" to the custom download now, for pages not specifically designed for Foundation, generates problems at every inputs.

**Comment by DanielRuf** [comment] 2018-03-09 18:55
> probably is because the float grid is not included in the "Complete" download.

xy-grid is the new default grid. Was not clear enough that you used the normal download.

**Comment by DanielRuf** [comment] 2018-03-09 18:56
Well, forms should have the recommended and supported markup / structure.

**Comment by riksoft** [comment] 2018-03-09 19:28
> xy-grid is the new default grid. Was not clear enough that you used the normal download.

There were 2 different problems. I tried the full download just to be sure the problem to the form was not due to the lack of something else.

However, in the end, I'm using the float-grid for maxi compatibility backwards and from the CSS I;ve removed the line about border-radius, and that's perfect for my need.

Thanks for your patience :-)
PS: this is the most interactive assistance I've ever seen! :+1:
