### ISSUE TITLE
Breakpoint (down) error

### ISSUE THREAD

**Issue by vedran-milic** [zurb/foundation-sites#10006] opened 2017-05-04 07:57 UTC
When setting up custom media queries in settings file, I've changed medium media query from 640px to 480px.
Now when I use <code>@include breakpoint(medium down)</code> i expect it to be <code>@media screen and (max-width: 479px) or 29.9375em</code>, but instead I <code>get @media screen and (max-width: 639px) or 39.9375em</code>.
Should this work this way?

**Comment by brettsmason** [comment] 2017-05-04 10:59
I can confirm this. I just tried changing any of the breakpoint defaults using the `down` keyword, but they appear to default to the values in `_breakpoint.scss`.

**Comment by DanielRuf** [comment] 2018-03-10 23:04
Tested with current develop branch (6.4.4)

`small down` by default is `max-width: 39.9375em`
`small down (800px)` is `max-width: 49.9375em`

**Comment by DanielRuf** [comment] 2018-04-06 21:04
Does the issue still exist (in `develop`)?

**Comment by ncoden** [comment] 2018-04-07 18:04
TL:DR Not a bug

> `[breakpoint] down` means "for this breakpoint and below". `breakpoint(large down)` must generate a breakpoint for large and below, which mean that the maximum width must be _just before the next breakpoint_.

> ```js
> ├─ xlarge max
> │
> ├─ xlarge min
> ├─ large max    ┓
> │               │
> ├─ large min    │
> ├─ medium max   │
> │               │   "xlarge down" Breakpoint
> ├─ medium min   │
> ├─ small max    │
> │               │
> ...
> ```
> 
> So it's not a bug. It is consistent with `breakpoint(large)` meaning "for this breakpoint and above".
> 
> If you don't want the large breakpoint to be included, use `breakpoint(medium down);`.

See https://github.com/zurb/foundation-sites/issues/11050#issuecomment-372720035
Duplicate of https://github.com/zurb/foundation-sites/issues/11050

**Closed by ncoden** 2018-04-07 18:04 UTC
Labels: bug, good first issue, scss
