### ISSUE TITLE
Cannot type spaces into input within dropdown menu

### ISSUE THREAD

**Issue by dcpomfret** [zurb/foundation-sites#8011] opened 2016-01-26 12:18 UTC
When placing an input within the top-bar element you can no longer type spaces into it.

For example: "hello world" is not possible, instead it would format as "helloworld"

Using latest version of Foundation 6.

**Comment by gakimball** [comment] 2016-01-26 17:21
Can't recreate with a basic top bar example—can you post the HTML you're using?

**Comment by dcpomfret** [comment] 2016-01-26 21:31
Managed to recreate it fine using this F6 codepen as you can see on this post

http://foundation.zurb.com/forum/posts/37908-input-inside-top-bar-doesnt-allow-spaces

**Comment by gakimball** [comment] 2016-01-27 17:27
Ah okay, this is actually happening from am `<input>` being inside a dropdown menu, not a top bar. (Top bar has no JavaScript.)

I think this is happening because the dropdown menu uses the space bar to handle manipulating the menu.

**Comment by jordan314** [comment] 2016-02-19 23:53
I found two workarounds for this:
Disable keydown events on li.menu-text:
`$('li.menu-text').off('keydown');`
Or disable foundation keyboard events completely:
`Foundation.Keyboard.handleKey = function(){};`

**Comment by Owlbertz** [comment] 2016-09-23 06:25
This issue was caused by the keyboard navigation part of the Dropdown Menu. It should be fixed by now as shown in [this pen I updated to Foundation 6.2.3](http://codepen.io/Owlbertz/pen/XjpQRB).

**Closed by Owlbertz** 2016-09-23 06:25 UTC
Labels: bug, javascript

**Comment by RevolutionTech** [comment] 2016-09-26 06:29
Does this fix come after the tag [v6.2.3](https://github.com/zurb/foundation-sites/tree/v6.2.3)? I'm still seeing the issue in the latest `dist/foundation.min.js`.

**Comment by Owlbertz** [comment] 2016-09-26 06:34
Does it still occur in the Pen I linked above for you? It is using version 6.2.3 and it works for me there.

**Comment by RevolutionTech** [comment] 2016-09-26 06:57
Oops, nevermind. It is indeed definitely working in 6.2.3. My bad!
