### ISSUE TITLE
ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by lhadjadj** [zurb/foundation-sites#11642] opened 2019-01-01 20:19 UTC
## What should happen?
The foundation.js is load with no error, so all ZF Javascript is working.
...

## What happens instead?

ReferenceError: __webpack_require__ is not defined.
Is the error message in the browser in debug mode. No ZF javascript is load.
 Only foundation css works
...

## Possible Solution

* The ZF 6.4.2 complete package for site works. 
* The foundation.js download from github works (c712acf)
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 
if you need i can deploy a test environnement.

How to reproduce:
1. load jquery first
2. load foundation.js
3. use any objet using ZF javascript like close button, modal windows,...

__It's the PHP Symfony declaration with Assetic__
{% javascripts filter='?jsqueeze'
    '@PortailBundle/Resources/public/js/vendor/jquery.js'
    '@PortailBundle/Resources/public/js/foundation/what-input.js'
    '@PortailBundle/Resources/public/js/foundation/foundation.js'
    '@PortailBundle/Resources/public/js/app.js'
     output='js/foundation.js' %}
  <script type="text/javascript"  src="{{ asset_url }}"></script>
{% endjavascripts %}

Only the js/foundation.js. 

__It's an example of code works with 6.42 and the 6.5.1 (c712acf) but not with the complete package. 
<div class="grid-container grid-container-padded">
 <div class="grid-x annonce cell" id="boite-annonce" data-closable="slide-out-right" style="margin-top: 1rem;">
   <fieldset class="cell" style="margin-top:0.8rem;">
     <div class="info" style="padding:1rem;">    
         {{ message| raw }}
    </div>
   </fieldset>  
 </div>     
</div> 

## Context

The foundation.js from the complete package works in developpement environnement, but not in production. 
when we rolled out the new version of our application in production with the Zurb Foundation 6.5.1 update, we quickly detected the problem on the mobile because the "close" functions did not work. We identified very quickly the origin of the problem and we looked for a solution (in forums, on stackoverflow, ...) we spent a day to perform tests before finding a workaround. In this case the use of the library available in the sources to replace that present in the download bundle on your site.
...

## Your Environment

- Foundation version(s) used: 6.5.1 (for site, complete bundle)
- Browser(s) name and version(s): chrome 71, chrome dev 72, firefox 64, safari IOS 9.3, chrome mobile, edge 42.17...
- Device, Operating System and version: 
     samsung Galaxy core prime,  Samsung J6, xiaomi me8, ipad 3 (2012), ipad pro (2018), Lenovo T540p 
     Android 5.1.1, Android 7.1.1, Android 9 pk1, iOS 9.3, iOS 12.1.2, Windows 10

- Link to your project: 
In production and working now with the workarround : https://lilmod-lelmad.fr
If you need an access to the dev server with the foundation.js that not working, ask me in PV.

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2019-01-01 20:42
Please fill out the complete issue template so we can reproduce it. My guess is that something optimizes the require function if webpack away.

**Comment by DanielRuf** [comment] 2019-02-27 20:51
I've closed this issue because we do not have the needed information to reproduce this. Feel free to reopen when you have updated the issue description with the relevant details.

**Closed by DanielRuf** 2019-02-27 20:51 UTC
