### ISSUE TITLE
[Sticky] bug in documentation

### ISSUE THREAD

**Issue by anselmdk** [zurb/foundation-sites#9673] opened 2017-01-18 23:01 UTC
See attached, this is 6.3 on Safari.
Check the link: http://foundation.zurb.com/sites/docs/sticky.html

I'm pretty sure this was introduced in 6.3.

<img width="1090" alt="screenshot 2017-01-18 23 58 15" src="https://cloud.githubusercontent.com/assets/1316533/22086706/47ddab5c-ddda-11e6-909a-7475471831ce.png">

**Comment by colin-marshall** [comment] 2017-01-31 18:28
@anselmdk I can't reproduce. Did the page load like that or did you have to do some scrolling or window resizing in order to make it happen?

**Comment by anselmdk** [comment] 2017-01-31 18:48
It happens as soon as you scroll down. I'm on Safari 9.0.3 on El Capitan. Maybe that's the issue.

**Comment by IamManchanda** [comment] 2017-01-31 18:54
Me also was unable to reproduce the bug! Seems like a **YAII** unless there is something to do with the browser support

**Comment by anselmdk** [comment] 2017-01-31 19:12
Okay, I just checked on Browserstack in MacOS Sierra, which comes bundled with Safari 10, and I can't reproduce there, so it seems to be specific to Safari 9. Maybe it's time for me to upgrade.

**Comment by colin-marshall** [comment] 2017-01-31 19:16
@anselmdk thanks for checking! I'm on 10.0.3 on El Capitan. So ya, Safari 9 it is.

@kball should we just close this and chalk it up as a Safari bug? Not sure what protocol is for this kind of situation.

**Comment by IamManchanda** [comment] 2017-01-31 19:18
Foundation ( specially JS ) is only supported for last two versions of safari so this should be closed!!

**Comment by anselmdk** [comment] 2017-01-31 19:22
Well 9 is the second newest version of Safari (see [here](https://en.wikipedia.org/wiki/Safari_version_history), but I agree that given that it works on latest Safari I'd not spend too much time on it.

**Comment by IamManchanda** [comment] 2017-01-31 19:23
Yeah just checked it .... sorry i use linux ...... and got confused a bit .... sorry about that !

**Comment by colin-marshall** [comment] 2017-01-31 19:28
@anselmdk is it possible for you to upgrade to 9.1.3 and test it? Not sure if the app store will make you jump to 10 or allow you to update to the latest version of 9. If that's a hassle or it doesn't work from the app store, don't worry about it.

**Comment by anselmdk** [comment] 2017-01-31 22:25
@colin-marshall I checked, I'll need to run a system update for the safari upgrade, I think. I'll do that when I've got a free moment.

**Comment by anselmdk** [comment] 2017-02-12 21:09
Just upgraded to Safari `9.1.2` and the bug persists. No idea why I had no option of upgrading to `9.1.3`. Next option is `10.0.3` which I'll run now. It'll probably make the bug disappear.

**Comment by anselmdk** [comment] 2017-02-12 21:19
Back up. As expected the bug doesn't persist on Safari `10.0.3`.

**Comment by colin-marshall** [comment] 2017-02-14 21:51
Thanks for the updates @anselmdk. We're actually rewriting sticky for 6.4 so I think we'll probably just end up closing this issue but I'll wait for @kballl to weigh in on it first.

**Comment by kball** [comment] 2017-02-28 21:22
Let's not close in case until we have the 6.4 rewritten in case someone wants to submit a patch fix for this.

**Comment by DanielRuf** [comment] 2019-08-03 17:52
Closing as Safari 12.1.2 is the latest version now.

**Closed by DanielRuf** 2019-08-03 17:52 UTC
Labels: Sticky, 🐛bug
