### ISSUE TITLE
javascript error on brand new foundation 6.4.0 stack template

### ISSUE THREAD

**Issue by norman-pixelkings** [zurb/foundation-sites#10293] opened 2017-06-29 10:26 UTC
After installing the full stack I run `foundation watch`. But pages giving me this error in the browser

app.js:123 Uncaught TypeError: (0 , _jquery2.default)(...).foundation is not a function
    at Object._typeof (app.js:123)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:10356)
    at __webpack_require__ (app.js:20)
    at module.exports.module.deprecate (app.js:66)
    at app.js:69

Javascript stops working after that.

Platform: MAC OSX
Browsers: Google Chrome, Safari, Firefox
Version: Foundation 6.4.0 full stack.

![image](https://user-images.githubusercontent.com/8957296/27683393-11b39a4e-5cc6-11e7-9460-26f9025dab3a.png)

**Comment by kball** [comment] 2017-06-29 16:27
Thanks for the bug report... @norman-pixelkings 

A couple quick questions for you, as I'm currently unable to reproduce...

How did you install the full stack? Were you using the cli?

What versions of node and npm are you using?

Thanks!

**Comment by norman-pixelkings** [comment] 2017-06-29 16:42
Hi kball, thanks for your reply. I did a cli install `foundation new --framework sites --template zurb`
I just updated npm to 3.10.10. Error still exist. But then I did a complete new cli install and all errors are gone! 
Thanks you sir! 👍

**Comment by kball** [comment] 2017-06-29 16:51
ok interesting... I'm about 90% certain this has to do with the way npm pre v3 installed things nested instead of flat. Gonna run down that road and see if I can get the template working for npm 2 series

**Comment by kball** [comment] 2017-06-29 17:07
Hmm... I'm not able to reproduce this with npm 2 series... I'm wondering if this was related to https://github.com/zurb/foundation-zurb-template/commit/dbb54764b20bec3ca2c666de51318c7ea656f8c4

@norman-pixelkings do you happen to know when you did the install above that showed the error? Was it right around when you filed the issue, or earlier in the day and potentially before the referenced change went into place?

**Comment by kball** [comment] 2017-06-30 22:36
Closing this as it was resolved for @norman-pixelkings. If someone else is experiencing and can give me steps to reproduce please reopen so I can dig in more.

**Closed by kball** 2017-06-30 22:36 UTC
