### ISSUE TITLE
[Tooltips] Tooltip `pip` bug

### ISSUE THREAD

**Issue by proov** [zurb/foundation-sites#8434] opened 2016-03-20 12:12 UTC
**How can we reproduce this bug?**
1. Step one : pen created here : http://codepen.io/proov/pen/JXWEKZ
2. Step two : hover the tooltip

**What did you expect to happen?**
Tip pip displaying correcly :D

**What happened instead?**
the pip is a strange grey square. Btw it works with `top` and `right` class variations.

**Test case**
http://codepen.io/proov/pen/JXWEKZ

Thanks for your work :)

**Comment by Owlbertz** [comment] 2016-03-20 13:21
If you resize the window so that the trigger is on the outer left then it works as intended. There seems to be some issue with the positioning fallback. Seems to be related to #8144. If you agree, please post in the other issue so this one can be closed to prevent duplicates.
@gakimball I suggest adding this bug to #8413.

**Comment by QsmaPL** [comment] 2016-03-29 21:35
@proov u can use my [snippet](https://github.com/QsmaPL/Foundation-6-Tooltip-design) to change tooltips :)

**Comment by DanielRuf** [comment] 2018-03-06 22:18
Not reproducible in the latest releases https://codepen.io/DanielRuf/pen/MQNJLq so I'll close this.

Feel free to reopen if this still occurs.

**Closed by DanielRuf** 2018-03-06 22:18 UTC
Labels: Tooltip, bug, javascript
