### ISSUE TITLE
Hamburger icon of the Foundation website is not clickable on Firefox

### ISSUE THREAD

**Issue by diek** [zurb/foundation-sites#11429] opened 2018-07-31 21:50 UTC
## What should happen?
When page size is reduced the toggle menu on your main site pages should display a menu. It does so in Google Chrome

## What happens instead?
The link to the menu for your website, for toggle, does not work in Firefox. See comparison, https://imgur.com/a/IuYYkpv

## Test Case and/or Steps to Reproduce

Test Case:
Go to any of your pages using firefox https://foundation.zurb.com/, minimize the screen until the mobile responsive menu appears

How to reproduce:
1. As above
2. Reduce Screen until menu toggle appears
3. Select Menu

## Context

I am not going to use Foundation if it not working on Firefox. I want to move away from Bootstrap so I hope this is something relatively straightforward for you to resolve.

## Your Environment

- Foundation version(s) used: Whatever version your main site uses
- Browser(s) name and version(s): Firefox 61.0.1 (64-bit)
- Operating System and version (desktop or mobile): Mac OSX 10.13.6

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one. I searched and could not find any.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by SassNinja** [comment] 2018-08-01 08:05
Thank you @diek for reporting this!

Seems FireFox doesn't like the 0 width of the button.

@ncoden do you know where to find the sources of that page or rather how to adjust it?
It's not part of this repo.

**Comment by ncoden** [comment] 2018-08-01 18:37
Hmmm I don't think we can label it as a browser bug: the button has no width due to its content being absolute. There's nothing to click even if the hamburger icon is visually there. I would expect it not to be clickable.

Beside that, I do not have access to the "marketing website" now but I'm on it. This comes from specific styles used in it and is not a bug in Foundation itself.

**Comment by SassNinja** [comment] 2018-08-02 15:11
I labeled it as browser bug since it's working in chrome (which seems to be less strict). But right, the whole CSS of this part is not good.

Shall we close this issue then as it's not related to Foundation itself?

**Comment by ncoden** [comment] 2018-08-02 20:54
Well for now there is no other place to host issues like this one. It's not the `foundation-sites` package but it should be resolved anyway, probably by us.

**Comment by diek** [comment] 2018-08-03 17:01
I hope you guys resolve it, I look forward to using foundation

**Comment by DanielRuf** [comment] 2019-08-12 19:56
Closing as it works in Firefox 67 so it seems this was fixe by Mozilla.

**Closed by DanielRuf** 2019-08-12 19:56 UTC
Labels: 📖 website
