### ISSUE TITLE
spotSwipe is not registered as a function

### ISSUE THREAD

**Issue by gforcada** [zurb/foundation-sites#11490] opened 2018-09-04 13:34 UTC
## What should happen?
That the snippet provided on the documentation as an example should work, but it `does not for me`:tm: :
```
$('selector').spotSwipe().on('swipeleft', handleLeftSwipe);
```

## What happens instead?
A traceback is thrown and, of course, the element does not react on any swipe movement.

## Possible Solution
I really have no idea, sorry, on a superficial level it feels like the registration is *wrong* (i.e. is not using the usual `$.fn.spotSwipe = function ()` constructor that is used for example on `addTouch`) but I'm far from an expert in JS to make that claim.

## Test Case and/or Steps to Reproduce (for bugs)
I created a github repository to reproduce it: https://github.com/gforcada/foundation-touch-example

## Context
I'm creating an app-like newspaper reader and I want my users to be able to swipe an article to reach the next/previous one.

## Your Environment
- Foundation version(s) used: 6.5.0.rc-2
- Browser(s) name and version(s): Firefox 61 and Chrome 67
- Device, Operating System and version: Laptop with Linux (Fedora 28)
- Link to your project: 

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by SassNinja** [comment] 2018-09-05 07:12
@gforcada thanks for reporting this and for the repo to reproduce!

To be honest I haven't used that util yet.
But your code looks just like the example in the docs
https://foundation.zurb.com/sites/docs/javascript-utilities.html#touch

So I was curious why it's not working and checked the util's source in detail.
It seems to me the docs are erroneous because it can't work as described imo since a jQuery event extension is done here and therefore it has to be used as `$('.example').on()` and **not** as `$('.example').spotSwipe().on()`.

I've been able to get your example working by changing it into

```javascript
import $ from 'jquery';

import {Foundation} from 'foundation-sites/js/foundation.core';
import {Touch} from 'foundation-sites/js/foundation.util.touch';

Touch.init($);

function handleRightSwipe () {
  alert('swipe right');
}

function handleLeftSwipe () {
  alert('swipe left');
}

$(document).ready(() => {
  $('body').append('<div class="example">Hi there can you swipe me?</div>');
  $('.example').on('swipeleft', handleLeftSwipe);
  $('.example').on('swiperight', handleRightSwipe);
});
```

@ncoden @kball are you more familiar with this util and can confirm if the docs are wrong here?

**Comment by gforcada** [comment] 2018-09-05 09:31
@SassNinja thanks for the answer! I could get to start without an error, but whenever I try to do a swipe it fails with another traceback:

```
TypeError: jquery__WEBPACK_IMPORTED_MODULE_0___default.a.spotSwipe is undefined
onTouchMove
foundation.util.touch.js:24
```

So this line:

https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.touch.js#L24

What I'm quite puzzled is that I can do swipe gestures on galleries powered by the orbit module :confused:

**Comment by SassNinja** [comment] 2018-09-05 11:34
@gforcada have you used the default jquery import in your `example.js`?

```javascript
import $ from 'jquery'; // GOOD

import $ from 'jquery/src/jquery'; // BAD
```

> What I'm quite puzzled is that I can do swipe gestures on galleries powered by the orbit module

Because it uses the event listener similar to how I've done it
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.orbit.js#L197

**Comment by gforcada** [comment] 2018-09-06 07:07
@SassNinja oh, I see, indeed, that works, I totally missed that small change!

**Comment by DanielRuf** [comment] 2018-09-07 07:56
> @SassNinja oh, I see, indeed, that works, I totally missed that small change!

Thanks for letting us now. I'll close this issue.

**Closed by DanielRuf** 2018-09-07 07:56 UTC
Labels: 📖 documentation

**Comment by gforcada** [comment] 2018-09-07 19:50
Well, the doc are still wrong though... may I send a pull request for it?

**Comment by ncoden** [comment] 2018-09-07 21:56
Thank you @SassNinja and @DanielRuf for taking care of this issue. It is now fixed in https://github.com/zurb/foundation-sites/pull/11495 (@gforcada).
