### ISSUE TITLE
Problems with build pipeline and Middleman due to foundation-sites.scss

### ISSUE THREAD

**Issue by jonlay** [zurb/foundation-sites#7419] opened 2015-12-06 02:52 UTC
I'm wondering if there is a specific reason that the [`foundation-sites.scss`](https://github.com/zurb/foundation-sites/blob/develop/foundation-sites.scss) file tries to `@import 'foundation';`, which doesn't exist in that directory.

The asset build pipeline I'm in Middleman tries to compile the Sass and chokes on this `@import`.

Would it not make more sense for the line to be `@import scss/foundation` instead of just `@import foundation`.

Perhaps there's a deliberate reason for this, but it seems a little bit odd to me that you'd have an `scss` file available in the bower_component which can't actually be run.

For now, I've worked around this by telling my build script to `ignore '/bower_components/foundation-sites/foundation-sites.*'` but I thought this was worth mentioning in case it was an unexpected oversight.

Absolutely loving F6 so far, by the way. Thanks to all of you for your effort building it.

**Comment by gakimball** [comment] 2015-12-08 18:37
I would ignore that top-level file. It's better to add the Foundation Sass path (`bower_components/foundation-sites/scss`) to your compiler's list of import paths, and then `@import 'foundation'` in your own Sass entry file.

**Comment by timsvoice** [comment] 2015-12-08 18:46
I've added the import paths and everything is hooked up and going through the Middleman asset pipeline, however no Foundation sass functions or mixins are being processed. Which means no Foundation 6 because everything is a function/mixin. Has anyone else experienced this?

Also +1 for the big upgrade. The whole philosophy behind the changes is really compelling.

**Comment by iAmMezie** [comment] 2015-12-09 11:45
Also experiencing this issue of no Foundation 6 been complied. I only got normalize to compiled.

**Comment by ozzywadd** [comment] 2015-12-09 16:31
I'm getting the same issue as iAmMezie. Foundation 6 doesn't seem to compile. I only get part of the normalize css from the npm install and just the first comment if I use the download from here.

**Comment by richipargo** [comment] 2015-12-16 02:29
+1

**Comment by gakimball** [comment] 2015-12-16 18:20
@timsvoice @iAmMezie @ozzywadd Are you adding the CSS export mixins after the `@import` statement? Check out our [blank template's app.scss file](https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss) for an example.

**Comment by gakimball** [comment] 2016-01-06 22:45
Going to close this as I'm positive the issue is that you're missing the CSS export mixins. `@import 'foundation'` on its own doesn't print any CSS, which is intentional.

@jonlay As for your initial issue, your Sass compiler needs to be configured with import paths. The `foundation-sites.scss` file (which has since been moved to `assets/foundation.scss`) doesn't use relative paths—it assumes you have an import path to the Foundation SCSS files set up.

If any of you still have problems with the CSS missing, let us know :)

**Closed by gakimball** 2016-01-06 22:45 UTC
Labels: question, scss
