### ISSUE TITLE
Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by devanflaherty** [zurb/foundation-sites#10301] opened 2017-06-30 03:08 UTC
Just upgraded my rails project to use Foundation 6.4.
It was a new project I hadn't modified any code so replacing the settings.scss was easy and I was previously only selecting what components  I wanted to load in.

I thought it would be seamless but I'm getting this :
`Base-level rules cannot contain the parent-selector-referencing character '&'.`

It's showing me this error for `@include foundation-button-group;`

I have foundation-sites installed via yarn, but I'm compiling the scss through rails asset pipeline.

Any help please, I'm dead in the water here.

**Comment by BernhardWebstudio** [comment] 2017-06-30 05:59
Possible duplicate: [Issue 10279](https://github.com/zurb/foundation-sites/issues/10279)

**Comment by IamManchanda** [comment] 2017-06-30 06:23
Yup duplicate but different code and this need to fix too

**Comment by kball** [comment] 2017-06-30 16:47
@IamManchanda can you find where in `foundation-button-group` might be triggering this? I'm not seeing anywhere in the code for button group where we have `&` outside of a selector

**Comment by kball** [comment] 2017-06-30 16:53
I just tested with ruby sass against develop and am not seeing errors in the main compile (including button group, as well as menu/xy where we were seeing some ruby sass problems before).

I am seeing an error with rubysass if I include the prototype classes:

```
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend h1" on line 15 of scss/prototype/_typescale.scss.
        on line 105 of _vendor/normalize-scss/sass/normalize/_normalize-mixin.scss
```

@IamManchanda do you have time to look into that? If not I'll get it after some teaching but before I package up 6.4.1 today

**Comment by devanflaherty** [comment] 2017-06-30 17:29
Hey guys, more info on my bug.

For some testing I removed button group and then the error moved to the
following included component.

So for some reason it's just showing me the error starting at button group.
But I can't be sure that's where it's originating.

It's real weird.

**Comment by IamManchanda** [comment] 2017-06-30 17:45
@kball @devanflaherty

> I am seeing an error with rubysass if I include the prototype classes:

Oh Jesus, Seems like the problem is here 
https://github.com/zurb/foundation-sites/blob/develop/scss/prototype/_typescale.scss#L9-L20

http://foundation.zurb.com/sites/docs/prototyping-utilities.html#typescale

**Comment by kball** [comment] 2017-06-30 22:38
@devanflaherty I've just published 6.4.1, which resolved the known issues associated with this outside of the opt-in prototyping helpers, so for a base install should "just work".  Can you try it out and verify this is resolved for you?

**Comment by devanflaherty** [comment] 2017-07-02 01:31
Working great!

**Comment by Lunatig** [comment] 2017-07-04 19:20
@include foundation-prototype-typescale;

 You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend h1" on line 15 of node_modules/foundation-sites/scss/prototype/_typescale.scss

**Comment by kball** [comment] 2017-07-05 19:11
@IamManchanda any thoughts on resolving this prototyping scss issue?

**Comment by IamManchanda** [comment] 2017-07-05 20:08
@kball Can we just move typescale from prototyping helpers to typography part but still keep it disabled by default??

**Comment by kball** [comment] 2017-07-05 20:15
We can move it, but does that resolve the @extend/@media issue?

**Comment by IamManchanda** [comment] 2017-07-05 20:16
Yes if we move it here... this will most probably resolve the issue 
See https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_base.scss#L332

**Comment by kball** [comment] 2017-07-05 20:17
@IamManchanda lets try it - move it over and then test with ruby sass once you have (or if you prefer I can test it)

**Comment by IamManchanda** [comment] 2017-07-05 20:19
Yeah doing it now ... you test it as i dont use/know ruby(Me and my love of Php) ... so you test it ... doing a PR shortly :wink:

**Closed** 2017-07-05 21:18 UTC
