### ISSUE TITLE
select icon in chrome

### ISSUE THREAD

**Issue by captain-xu** [zurb/foundation-sites#9968] opened 2017-04-20 10:29 UTC
There two icons in chrome  , the select should add -webkit-apperance: none

**Comment by Deckluhm** [comment] 2017-04-20 12:40
As stated [here](http://foundation.zurb.com/sites/docs/sass.html#autoprefixer-required), vendor prefixes aren't included in Sass sources.

**Comment by kball** [comment] 2017-04-20 16:04
We can if necessary to fix a bug... can you put in a reproduction codepen?

**Comment by Deckluhm** [comment] 2017-04-20 17:21
> We can if necessary to fix a bug... can you put in a reproduction codepen?

The bug is only visible if you use the Sass version of Foundation (since there is no vendor prefixes in sources) and as far as I know, there is no easy way to import a full Sass project in CodePen.

I reproduced the bug @captain-xu is talking about by using Foundation CSS version and by setting `select` `-webkit-appearance` to the default WebKit value (`menulist`):

https://codepen.io/anon/pen/EmKZgW?editors=1100

**Comment by captain-xu** [comment] 2017-04-21 01:55
@Deckluhm that's right,   there are no problems if use the css. And I think, the select -webkit-appearance show be 'none'

**Comment by kball** [comment] 2017-04-21 16:18
@IamManchanda I think this is similar to the fix you did in https://github.com/zurb/foundation-sites/pull/9868 - do you want to take a pass on it?

**Comment by IamManchanda** [comment] 2017-04-21 16:22
Ohk @kball will take a look!

**Comment by IamManchanda** [comment] 2017-05-22 08:07
@captain-xu @Deckluhm 
I couldn't reproduce in the sass build codepen! 
https://codepen.io/IamManchanda/pen/wdQVoB

Apart from that i have added test case here (where also i cant see the bug)
https://github.com/zurb/foundation-sites/pull/10063 
Can you pull it and let me know with screenshot and browser details ??

**Comment by rafibomb** [comment] 2017-05-22 17:26
@Deckluhm Hmm, as far as I know, Autoprefixer is running on the ZURB Stack and Basic Template. You can see it here,
https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L84
https://github.com/zurb/foundation-sites-template/blob/master/gulpfile.js#L17

If you are not auto-prefixing, then manually adding the vendor prefixes would be good.

I am also seeing the correct declarations in my 6.3.1 project:
<img width="971" alt="screen shot 2017-05-22 at 10 22 42 am" src="https://cloud.githubusercontent.com/assets/5652085/26320703/b55a1ed6-3ed8-11e7-9040-fb774c542098.png">

Unless I'm missing something, let me know - we'll close this.

**Closed by rafibomb** 2017-05-22 17:26 UTC
Labels: bug

**Comment by Deckluhm** [comment] 2017-05-22 18:06
> Hmm, as far as I know, Autoprefixer is running on the ZURB Stack and Basic Template.

Sorry if I wasn't clear enough, here are my thoughts about the issue reported:
- It's not a bug
- It only appears on Sass version without Autoprefixer, basically anything except ZURB Stack (e.g. `foundation-rails` gem)
- As [stated in the docs](http://foundation.zurb.com/sites/docs/sass.html#autoprefixer-required), unless you are using the ZURB Stack (that already includes Autoprefixer), you must use Autoprefixer to get vendor prefixes

That is probably a good idea to add a small note in the docs about that. I already faced that "double icon" issue and it wasn't obvious that it was a prefixes issue.

**Comment by IamManchanda** [comment] 2017-05-22 18:13
> That is probably a good idea to add a small note in the docs about that. I already faced that "double icon" issue and it wasn't obvious that it was a prefixes issue.

@Deckluhm you are correct ..... Go ahead and add a PR :)
