### ISSUE TITLE
[Reveal] Scroll reveal on chrome Android

### ISSUE THREAD

**Issue by Tralgar** [zurb/foundation-sites#8127] opened 2016-02-10 09:48 UTC
Hello,
I found a bug on chrome android for reveal component. The problem is that you can't scroll up or down the page till a reveal is open, so if the reveal is higher than the screen size, you can't scroll to see the whole content.

**Comment by gakimball** [comment] 2016-02-10 16:55
Can we recreate this in the documentation?

**Comment by samcpt** [comment] 2016-02-11 04:37
```
@include breakpoint(small only) {
  .reveal {
    height: 100vh !important;
    overflow-y: scroll !important;
    
    -webkit-overflow-scrolling: touch;
  }
}
```

Add this code to your stylesheet

**Comment by Tralgar** [comment] 2016-02-11 09:51
Recreate where ? I don't understand sorry. 

That's not so bad but it's not what i'm searching for. If the reveal has only 100px height, now it takes the page height and for example we have a reveal of 800px with 700px of white... and we still can't scroll the page like reveal should let us do !
We have to fix it properly. I'm working on it btw...

Thanks !

**Comment by samcpt** [comment] 2016-02-11 14:17
You can change the class name to something like
modal-tall-mobile
Now every time you know that the content of the modal will be bigger than the viewport you can apply this class.
Make this detection dynamically based on the content will be very hard without JavaScript

**Comment by gakimball** [comment] 2016-03-08 22:57
Reveal got a lot of bug fixes in 6.2, I'll be testing this issue again soon.

**Comment by DanielRuf** [comment] 2018-02-17 12:42
I can not reproduce it anymore with the latest release https://codepen.io/DanielRuf/pen/mXpMVb

**Comment by DanielRuf** [comment] 2019-02-27 21:07
I have closed this issue as we could not reproduce this and there is no further feedback.

**Closed by DanielRuf** 2019-02-27 21:07 UTC
Labels: Reveal, javascript, 🐛bug
