### ISSUE TITLE
Responsive navigation doesn't make responsive links !

### ISSUE THREAD

**Issue by udf2457** [zurb/foundation-sites#10638] opened 2017-09-11 17:53 UTC
Zurb 6.4.2 

Lets say I've got a menu:

```
<ul class="dropdown vertical medium-horizontal menu"  data-responsive-menu="drilldown medium-dropdown"  data-auto-height  data-animate-height >
	<li class="menu-text">
	<img class=“foobar-logo foobar-hidesmall"  src="/templates/img/foobar.jpg” >
	</li>
	<li><a href="/index.php">Home</a>
	<ul class="menu vertical" ><li>
		<a href="/index.php">Alice</a>
	<ul class="menu vertical" >
		<li><a href="/index.php/home/bob/test">Bob</a></li>
	</ul>
	</li></ul>
</li>
</ul>
```

In dropdown style, this works great, all three links (Home, Alice & Bob) are clickable.

The problem then comes with responsive.....

Zurb automagically switches to drilldown, ok, that's cool and the magic works perfectly.
but, and its a big BUT ....
Suddenly the user is unable to access Home or Alice via the menu.  Only leaf node Bob.

Not cool.  ;-(

We need more intelligence in the responsiveness.

**Comment by mattbag** [comment] 2017-09-12 00:47
Seems to be working here
https://codepen.io/mattbag/pen/GMKBQQ?editors=1000

**Comment by udf2457** [comment] 2017-09-12 08:10
@mattbag 

Huh ?!?  That codepen demonstrates exactly the problem !

Please re-read my post, or allow me to spell it out another way:

1) The above code works perfectly on >= medium.
2) When you shrink the screen, the menu changes to drill down
3) The **_links_** for "home" and "alice" do not work.

Note that I have highlighted the word _**links**_.

I am _**NOT**_ saying that the drilldown does not work.   Sure, if you hit "Home" you get the next menu down.

My problem is the responsiveness breaks the menu itself.

The responsiveness does not provide an alternate means to access the underlying content after the menu transitions from dropdown to drilldown.

**Comment by mattbag** [comment] 2017-09-12 11:20
I get it now!
Well what I would do (as in I always do it in every project) is doing 2 different and separated menus for desktop and mobile. 
This way you could manage and structure the mobile drilldown as you want.

I have never used the drilldown or the switch, but I'm sure there must be a combination... but I don't have time to tinker atm ;)

**Comment by udf2457** [comment] 2017-09-12 11:27
Yeah, I think I might follow your lead and go down the 2 different menus route.  Should be easy enough to do with visibility classes I guess.

A pity. Because I quite liked the magic of the responsive menus.  But I guess they are still a bit immature for real production.

**Comment by udf2457** [comment] 2017-09-12 11:28
P.S. You might want to update the docs to reflect this as a "watch out", since other people might not necessarily notice what I spotted.

**Comment by kball** [comment] 2017-09-12 15:58
Correct me if I'm wrong, but I believe this is roughly the same as https://github.com/zurb/foundation-sites/issues/10611 which is what this PR was intended to address: https://github.com/zurb/foundation-sites/pull/10616

This will be included in 6.4.4, should be packaged up in the next couple weeks.

**Comment by udf2457** [comment] 2017-09-12 18:30
@kball That sounds along the right lines yes, its a discussion about accordions rather than drilldowns, but I suspect the solution probably applies to both.

Bring on 6.4.4 I guess !  ;)

**Comment by kball** [comment] 2017-09-12 19:37
For drilldowns I think parent link should already work - can you try adding `data-parent-link="true"` to your responsive menu?

**Comment by udf2457** [comment] 2017-09-12 20:40
@kball 

I think bad netiquette all-caps are permitted here.....

**_AWESOME !_**

;)

**Comment by kball** [comment] 2017-09-12 21:15
Great, going to close this issue then. :)

**Closed by kball** 2017-09-12 21:15 UTC
