### ISSUE TITLE
Button Group for rtl html

### ISSUE THREAD

**Issue by sassanh** [zurb/foundation-sites#8585] opened 2016-04-12 13:00 UTC
This is written in documentation for button groups:
// Sets the margin for the right side by default, and the left margin if right-to-left direction is used
However I checked the source code of "foundation-sites/scss/components/_button-group.scss" and saw that "margin-right" is hardcoded and there's no "margin-left" at all, it leads to last button in button-group not having any margin.

**How can we reproduce this bug?**
1. Make a button group in foundation
2. Set global direction to "$global-text-direction: rtl;"
3. Load it in browser.

**What did you expect to happen?**
Margin for all buttons.

**What happened instead?**
Last button didn't have margin, all others had.

**Test case:**

It needs rtl foundation so can't make a codepen for it.

**Comment by colin-marshall** [comment] 2016-04-12 20:22
@andycochran is it cool if I assign you all button group related issues?

**Comment by andycochran** [comment] 2017-01-04 22:05
This issue should be considered in the full menu rework #9421.

**Comment by colin-marshall** [comment] 2018-02-13 18:14
@sassanh was this resolved somewhere?

**Comment by sassanh** [comment] 2018-02-13 18:18
@colin-marshall Unfortunately I'm not using foundation anymore, it's been 2 years so I guess this issue is stale. I bet lots of things related to this has changed in foundation.

**Comment by DanielRuf** [comment] 2018-03-06 22:34
This should not be the case in the latest release(s) anymore.

**Comment by ncoden** [comment] 2018-03-06 23:04
@colin-marshall What's the status of this ?

**Comment by DanielRuf** [comment] 2018-03-06 23:05
Tested it and it seems ok when chaning the global-text-direction + dir attribute on the html tag.

**Comment by ncoden** [comment] 2018-03-06 23:27
@DanielRuf Is this issue caused by the missing `dir` attribute ?

**Comment by colin-marshall** [comment] 2018-03-07 20:00
@ncoden I haven't had a chance to look into this. I just was keeping it open because I wasn't sure if it was still an issue.

**Comment by DanielRuf** [comment] 2018-03-08 20:54
Without `dir="rtl"`: https://codepen.io/DanielRuf/pen/BraZae

With `dir="rtl"`: https://codepen.io/DanielRuf/pen/OvJgPG

So this is working in the latest release.

**Comment by ncoden** [comment] 2018-03-08 21:27
Sadly you cannot add `dir=rtl` in the codepen ^^. Tested by adding it manually and it works. So I'm closing this issue.

**Closed by ncoden** 2018-03-08 21:27 UTC
Labels: Button Group, bug, scss

**Comment by DanielRuf** [comment] 2018-03-08 21:33
> Sadly you cannot add dir=rtl in the codepen ^^.

Huh? I did and it worked?

**Comment by DanielRuf** [comment] 2018-03-08 21:34
Compare it with https://codepen.io/DanielRuf/pen/LdYjEv

**Comment by DanielRuf** [comment] 2018-03-09 05:40
> It's weird: the rtl version is alright, but ltr version doesn't have margin between Two and Three. It should be unrelated to this issue though.

You have to use the ltr version of Foundation Sites then and remove the dir attribute probably. The ltr and rtl versions look right, see the demo in the docs and my codepens.

**Comment by sassanh** [comment] 2018-03-09 05:42
OK, it's fixed then.
