### ISSUE TITLE
Button Sass reference typo in docs

### ISSUE THREAD

**Issue by craigward** [zurb/foundation-sites#10858] opened 2018-01-12 13:01 UTC
I would have corrected it but I can't find where the Sass references are, and it is not on `foundation-sites/docs/pages/button.md` 

But on https://foundation.zurb.com/sites/docs/button.html Sass Reference 

`@include button-disable);` should be `@include button-disabled();`

**Comment by ncoden** [comment] 2018-01-12 14:01
Duplicate of https://github.com/zurb/foundation-sites/issues/10783
Fixed in https://github.com/zurb/foundation-sites/pull/10830.

Fixed in `develop`, my bad. So the change will be visible on the release of `v6.4.4`, in 2-4 weeks I hope.

**Closed** 2018-01-12 14:01 UTC
Labels: duplicate
