### ISSUE TITLE
[Responsive Navigation] [6.1.1 vs 6.1.2] top-bar + responsive menu issue

### ISSUE THREAD

**Issue by zzplab** [zurb/foundation-sites#7978] opened 2016-01-23 16:15 UTC
**How can we reproduce this bug?**
See [jsfiddle.net+6.1.1](https://jsfiddle.net/ZZPdev/h7gpwby1/)
and
See [jsfiddle.net+6.1.2](https://jsfiddle.net/ZZPdev/h7gpwby1/1/)

I've made a top-bar with responsive menu. In 6.1.1 this works fine as expected. After updating foundation to 6.1.2 it doesn't work as expected anymore. The dropdown menu on medium up screens appears right next to the top menu instead of below.
The basic code of the menu is:
```
<ul class="vertical medium-horizontal menu" data-responsive-menu="accordion medium-dropdown">
			  <li>
			    <a href="#">Item 1</a>
			    <ul class="vertical menu">
	          <li><a href="#">Item 1A</a></li>
	          <li><a href="#">Item 1B</a></li>
	          <li><a href="#">Item 1C</a></li>
	          <li><a href="#">Item 1D</a></li>
	          <li><a href="#">Item 1E</a></li>
			    </ul>
			  </li>
```
**What did you expect to happen?**
The desired result with F6.1.1:
![schermafbeelding 2016-01-23 om 17 03 23](https://cloud.githubusercontent.com/assets/7559497/12531118/926dbbe8-c1f3-11e5-9626-2d6607e92c8f.png)
**What happened instead?**
This after updating to with F6.1.2:
![schermafbeelding 2016-01-23 om 17 03 32](https://cloud.githubusercontent.com/assets/7559497/12531123/99f56d20-c1f3-11e5-9679-fb1ff81e82d2.png)
Is this a bug?
Or do I need to change my code?
And if so how? I've already tried many options without succes.

**Test case**

See [jsfiddle.net+6.1.1](https://jsfiddle.net/ZZPdev/h7gpwby1/)
and
See [jsfiddle.net+6.1.2](https://jsfiddle.net/ZZPdev/h7gpwby1/1/)

**Comment by richpeers** [comment] 2016-01-23 19:50
can confirm im getting the same

**Comment by natewiebe13** [comment] 2016-01-23 20:50
On a side note, the arrow isn't pointing in the right direction in 6.1.1 as well.

**Comment by JeremyEnglert** [comment] 2016-01-25 21:19
Definitely noticed this as well.

**Comment by tsquez** [comment] 2016-01-25 22:19
Yep, updated and menu went BOOM!!!....lol

**Comment by gakimball** [comment] 2016-01-25 23:30
This is happening because the dropdown plugin is seeing the `.vertical` class and assuming the menu is vertical, ignoring the `*-horizontal` classes.

We're going to try and get a fix out for that this week since it's fairly pressing.

**Comment by darkwoods-** [comment] 2016-01-26 21:48
omg i have been struggling with this for the whole day I wish i came here earlier

**Comment by marchewkaj** [comment] 2016-01-26 21:51
same here @darkwoods-

**Comment by colin-marshall** [comment] 2016-01-26 22:35
@gakimball looking forward to the fix! I put in an hour or so trying to fix it myself but couldn't figure out how.

BTW #7739 is the same/related, if you wanted to close that one in favor of this issue.

**Comment by rocketwebco** [comment] 2016-01-29 20:54
any progress on this yet? i'm stalled on a project until i can get this resolved. i'm pretty excited to see a fix

**Comment by marchewkaj** [comment] 2016-01-29 20:56
Yep, it works well now. The only issue is the drop-down arrows are still 'vertical', but I can live with that until I can put a fix in place for it.

**Comment by Jaaann** [comment] 2016-01-30 13:14
In case it would help anyone, I fixed the wrong position of the dropdown menu in my scss with:

```
 @include breakpoint(medium){
  .nested{
   top: 100%;
   left: 0
 }
}
```

But looking forward to the real fix

**Comment by rocketwebco** [comment] 2016-01-30 16:31
Thanks. How do I access the fix? Do I re-download the js or css? Or link to a cdn? Please excuse my ignorance

**Comment by Jaaann** [comment] 2016-01-30 17:12
Rocketwebco, do you mean my little ugly overwriting of css? If yes and I guess you use the css version, just put this at the end of your css file:

```
@media screen and (min-width: 40em) {
  .nested {
    top: 100%;
    left: 0px; }
}
```
But this is only a little help, till someone fixes this bug for real.

**Comment by rocketwebco** [comment] 2016-01-31 14:44
THANK you Jaaann, you are the bomb!

**Comment by Jaaann** [comment] 2016-01-31 19:06
You are welcome - I updated the code once more, to correct the menus if they close to the right side (the dropdown menu is showing too much on the right (` right:100% instead of right: 0` )

**Comment by isaac-webb** [comment] 2016-02-09 16:15
Did anyone else have issues with the background color of the dropdown? My dropdown menu was in the topbar and had the same background color as that rather than the white that was specified in the `_settings.scss` file. Not sure if this was intentional or not.

**Comment by gakimball** [comment] 2016-02-15 22:59
We have an idea for how to fix this, which involves reading the CSS off of the menu when the breakpoint changes. The dropdown plugin needs to know if the top-level menu is horizontal or vertical, which it can tell by seeing if the `<li>`s of the menu are `display: block` or `display: table-cell`. The former indicates it's vertical, while the latter horizontal.

**Comment by gakimball** [comment] 2016-02-23 19:36
Fixed via #8200. 6.2 will be out on Friday!

**Closed by gakimball** 2016-02-23 19:36 UTC
Labels: bug, javascript

**Comment by SalahAdDin** [comment] 2016-02-23 19:58
Really?

**Comment by zzplab** [comment] 2016-02-23 20:02
Great! Thanks 2 all.

**Comment by colin-marshall** [comment] 2016-02-25 00:03
@gakimball I'm trying to test this fix and it's not working for me on `6.2-stable` or `develop`. I am getting this on the visual tests:

![screen shot 2016-02-24 at 4 47 27 pm](https://cloud.githubusercontent.com/assets/4453733/13305445/7c64a576-db18-11e5-9f71-8464c6ff963a.png)
![screen shot 2016-02-24 at 4 47 13 pm](https://cloud.githubusercontent.com/assets/4453733/13305449/800c22a8-db18-11e5-83a2-cf7c7e6eea3e.png)

Am I doing something wrong here?

**Comment by gakimball** [comment] 2016-02-25 00:54
@colin-marshall Pinging @kball, any ideas?

**Comment by kball** [comment] 2016-02-25 01:09
Thats awkward, and definitely changed from what it was doing pre-merge.  I can reproduce though...  I'll take a look.

**Comment by kball** [comment] 2016-02-25 01:18
It looks like 265f08470337bc70db43d71bffc0625e1ad9cdf2 broke a slew of different positioning things on menus... all of the responsive visual tests are wonky, and if I revert it they appear to be better... I'm going to revert that for now, @gakimball please take a look and redo it

**Comment by colin-marshall** [comment] 2016-02-25 05:06
Yup, no longer messed up. Super glad this major issue is now resolved. Thanks guys, good work!

**Comment by JeremyEnglert** [comment] 2016-02-25 06:51
Did we lose edge detection?

Also, the arrow appears to turn white on hover, which makes it essentially invisible against the default dropdown background color.

![screen shot 2016-02-24 at 11 48 33 pm](https://cloud.githubusercontent.com/assets/6110968/13312144/83a83148-db51-11e5-8b33-67c224cac160.png)

**Comment by kball** [comment] 2016-02-25 16:59
Hmm... the edge detection should be working, I'll dig into that... the arrows I think is tied in with @gakimball 's change that I reverted... it was related to arrows, but appeared to mess up the alignment.  @gakimball can you take a look?

**Comment by kball** [comment] 2016-02-25 17:07
@JeremyEnglert I'm not currently reproducing either of your issues on 6.2-stable... can you give me a code sample to reproduce?  Thanks!

**Comment by JeremyEnglert** [comment] 2016-02-25 18:28
@kball - Edge detection appears to work fine for the menu item against the edge, however, if it's not the last menu item, it becomes an issue.

Works great with last menu item:
![screen shot 2016-02-25 at 11 23 27 am](https://cloud.githubusercontent.com/assets/6110968/13329672/8a2a4e0a-dbb2-11e5-8cea-99d148476051.png)

Becomes an issue when it is not the last menu item.
![screen shot 2016-02-25 at 11 23 18 am](https://cloud.githubusercontent.com/assets/6110968/13329740/e1ce9f62-dbb2-11e5-94ba-f50c1f84244d.png)

Demo Link: http://jointswp.staging.wpengine.com/demo/

**Comment by gakimball** [comment] 2016-02-25 20:50
Made some final tweaks to arrow positioning: e9cf3483af734ac8ed925617da9476c8d3a6c333

There's probably more streamlining we can do with this CSS, but for this release, it's solid.
