### ISSUE TITLE
Foundation 5.3.3 - Reveal modal doesn't work with jquery 2.2.0

### ISSUE THREAD

**Issue by roundge** [zurb/foundation-sites#7884] opened 2016-01-15 08:52 UTC
Hi there,

As mentioned here : http://foundation.zurb.com/forum/posts/37579-reveal-stopped-working
Reveal modal doesn't work anymore with the jquery update (2.2.0)

Firebug in firefox shows this message : 
`TypeError: g.on(...).trigger is not a function`

it works if you downgrade to jquery 2.1.4

**Comment by wneessen** [comment] 2016-01-15 15:43
Confirmed. Same issue for me as well.

**Comment by gakimball** [comment] 2016-01-16 00:06
Merged #7859 which resolves this.

**Closed by gakimball** 2016-01-16 00:06 UTC
Labels: bug, scss

**Comment by timaschew** [comment] 2016-01-26 22:15
Why this issue is closed? The issue is not fixed!
There is no foundation 5.3.4 or something else, installing version 5.* via bower is still broken!

**Comment by wneessen** [comment] 2016-01-26 22:19
Agreed. Though, you can fix it by manually applying the patch as described in https://github.com/sjhewitt/foundation/commit/2e33179ad78b7d677610c50656f51f4b703034d5

**Comment by gakimball** [comment] 2016-01-27 17:51
@timaschew The fix is in the codebase, so we close the issue. We'll try to get a patch out for Foundation 5 soon.

**Comment by mpasternak** [comment] 2016-09-03 20:10
This is NOT fixed in 5.5.3, 

please release 5.5.4 legacy version that fixes that,

5.5.3 still needs downgrade of jQuery to 2.1.4
