### ISSUE TITLE
Error running SASS

### ISSUE THREAD

**Issue by cliveeastgate** [zurb/foundation-sites#7108] opened 2015-11-21 12:27 UTC
When saving a change to _settings.scss,  frequently sass will fail with the following error

[BS] Serving files from: dist
[12:04:47] Starting 'sass'...
Error in plugin 'sass'
Message:
    src\assets\scss\app.scss
Error: File to import not found or unreadable: settings
       Parent style sheet: stdin
        on line 3 of stdin
>> @import 'settings';

Resaving the file without making any changes runs without any errors.

**Comment by andycochran** [comment] 2015-11-23 19:06
Fixed in #7153.

**Comment by gakimball** [comment] 2015-11-30 23:28
Are you using one of our blank project templates, or your own files?

**Comment by zurbrandon** [comment] 2015-12-02 00:06
This seems to be working everywhere we're trying it. I'll close this for now, but feel free to come back and update us and reopen the issue if it's still causing you trouble.

**Closed by zurbrandon** 2015-12-02 00:06 UTC

**Comment by cliveeastgate** [comment] 2015-12-02 20:58
Have not seen the problem since updating to 6.0.4

**Comment by therealbenhogan** [comment] 2015-12-11 15:43
Hi,

Using 6.0.5 - getting the same error

    Error in plugin 'sass'
    Message:
        scss\app.scss
    Error: File to import not found or unreadable: settings
           Parent style sheet: stdin
            on line 3 of stdin
    >> @import 'settings';
       ^
This wasn't happening previously - not sure what's caused it !

**Comment by gakimball** [comment] 2015-12-11 17:43
@therealbenhogan Do you have a file `_settings.scss` in the same folder as `app.scss`?

**Comment by therealbenhogan** [comment] 2015-12-11 17:47
Yes - same folder .... it's behaving at the moment !!

**Comment by gakimball** [comment] 2015-12-16 23:35
@therealbenhogan So it started working again?

**Comment by therealbenhogan** [comment] 2015-12-17 07:55
Hi Geoff, just opened up the project and made a few changes - seems ok at the moment!

**Comment by gakimball** [comment] 2015-12-17 19:39
@therealbenhogan Awesome, good to hear :) If you run into any other issues let us know.

**Comment by therealbenhogan** [comment] 2015-12-18 15:44
Hi Geoff,

On a completely unrelated issue – are you planning to write Angular directives for Foundation 6 ? Have looked at https://pineconellc.github.io/angular-foundation/ in the past, but was wondering if there are any plans for Foundation 6?

Cheers,

Paul

[image001]

Paul Sawyer
Web Preference Ltd
14 Oakdale Road
Weybridge
Surrey KT13 8EJ

Telephone: 01932 424242
Mobile: 07968 164104
Web: http://web-preference.co.uk<http://web-preference.co.uk/>

Registered in England & Wales No. 5426254 VAT registration no. GB 860 5011 58

**Comment by gakimball** [comment] 2015-12-18 17:00
@therealbenhogan We don't have any plans for *us* to do it, but we want to engage our community and encourage them to work on that stuff.

**Comment by therealbenhogan** [comment] 2015-12-18 17:03
Hi Geoff,

No problem – just thought worth asking before trying it myself ;-)

Cheers,

Paul

[image001]

Paul Sawyer
Web Preference Ltd
14 Oakdale Road
Weybridge
Surrey KT13 8EJ

Telephone: 01932 424242
Mobile: 07968 164104
Web: http://web-preference.co.uk<http://web-preference.co.uk/>

Registered in England & Wales No. 5426254 VAT registration no. GB 860 5011 58

**Comment by phifa** [comment] 2016-02-03 21:37
Hi, I just got the same bug. I work with foundation everyday, never had it before until now. Here is how to reproduce it (or at least what i did). I am on a Windows 10 machine, nodejs v4.2.6, 32bit: 

1. npm update
2. foundation update 
3. foundation install (website/handlebar setup) 
4. foundation watch in the project directory
5. change a variable in settings.scss 


Here is a screenshot: 

![sass bug](https://cloud.githubusercontent.com/assets/3061129/12797432/35651340-cac4-11e5-9b9c-f059168cf8ed.JPG)

**Comment by gakimball** [comment] 2016-02-04 17:44
@phifa Hard to say what's causing this issue, assuming there is a `_settings.scss` file in the same folder as `app.scss`. Might be an issue with your dev environment, but it's not an issue with Foundation.

When you say the file gets compiled eventually, do you mean the `sass` task eventually finishes without errors?

**Comment by surashu** [comment] 2016-02-09 15:19
I'm having the same issue on Windows 10.

![](http://i.imgur.com/mFNYRdf.jpg)

And yes, there's `_settings.scss`. But compared to @phifa, I can't seem to make it work no matter what I do.

**Comment by phifa** [comment] 2016-02-09 15:24
@gakimball @surashu so what I could not resolve this. I think it has to do with Windows user rights stuff. When I create a new project on my system drive it works. Weird. This might be related to the problem that Windwos has with node_modules long file names. I don't know.

**Comment by surashu** [comment] 2016-02-09 15:33
@phifa I think you may be on to something here. I tried deleting my project folder since I haven't really been able to do anything about it because of the failing compile but it gave me this error.

![](http://i.imgur.com/CDZv0Z3.jpg)

And not to mention, my project folder is even in the root of a drive partition I specifically dedicated to source codes. And basing off of your comment about Windows rights stuff, I tried running `foundation watch` in an elevated command prompt window with similar problems.

Hopefully there's a resolution for us Windows users. I can use a distro of Linux but it's really a pain to keep switching OS every time. Virtualization may also be an option but I'd prefer if it just worked natively.

**Comment by surashu** [comment] 2016-02-09 16:12
Following up on my previous post. I moved all my stuff out of my dedicated partition and then formatted it to ReFS instead of NTFS and for some reason, the problem isn't happening now. I don't know if this is just coincidental or anything but so far it seems to work. If anyone wants to try this for themselves and are in Windows 10 too, I just used [this guide](http://www.tenforums.com/tutorials/29897-refs-file-system-enable-disable-windows-8-1-windows-10-a.html) to enable ReFS.

Again, I don't know if this is just coincidental that it works now after I formatted but so far so good. I'll report back if it  happens to just be a fluke and acts up again later.
