### ISSUE TITLE
Strange dropdown-behaver - bug

### ISSUE THREAD

**Issue by bergschrat** [zurb/foundation-sites#8532] opened 2016-04-05 18:11 UTC
**How can we reproduce this bug?**
Foundation 6.2, Top-Bar
1. Step one: Pick up the Menu-Code from here:
[http://codepen.io/rafibomb/pen/bpgMRM](url)
everything is fine
2. Step two: Change the partent-linknames "Two", "One", "Three" in longer names, for example "Oberlink1", "Oberlink2", "Oberlink3".

**What did you expect to happen?** The same as before

**What happened instead?** The submenu opens in the wrong direction

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by brettsmason** [comment] 2016-04-07 08:59
@bergschrat the CodePen link doesn't seem to work, could you add a new one?
Based on what you described I setup a [CodePen](http://codepen.io/brettsmason/pen/GZyZPo) using the standard top bar markup in the docs, and changed the titles to what you described - all seems OK.

Could you confirm this is still an issue?

**Comment by brettsmason** [comment] 2016-04-07 09:58
Just noticed this seems to be a duplicate of [8480](https://github.com/zurb/foundation-sites/issues/8480) so I'm going to close this one (the other issue has a working CodePen example). If this is a separate issue then please reopen this.

**Closed by brettsmason** 2016-04-07 09:58 UTC
