### ISSUE TITLE
Issue with cells wrapping in Firefox, maybe because off rounding errors

### ISSUE THREAD

**Issue by PEZ** [zurb/foundation-sites#11135] opened 2018-04-06 09:05 UTC
Using the XY-grid, I have a case where three `medium-4` cells don't fit side by side in Firefox on desktop screens. Shown here: https://foundation-xy-ff.netlify.com/

Each cell gets a tiny bit wider on Firefox than on other browsers.

#### How to reproduce this bug:

I am not exactly sure how to reproduce it, except for using the exact paddings/margins/gutters that my example has. But if you do, then put three `medium-4` cells in a `grid-x.grid-margin-x`.

#### What should happen:

The three cells should fit side by side.

#### What happened instead:

The third cell wraps below the first cell in Firefox. (But fits side by side in Chrome and Safari).

#### Browser(s) and Device(s) tested on:

Firefox 59.0.2 (64 Bit), MacOS High Sierra.

#### Foundation Version(s) you are using:

Foundation sites 6.4.1 (Not sure how to check which version exactly, but it's what I get when I run `foundation new`.

#### Test case link:

I can't figure out how to reproduce it in a Codepen, since there are computed values from my Foundation settings involved.  But the issue can be seen in effect here: https://foundation-xy-ff.netlify.com/

Github repo: https://github.com/PEZ/foundation-sites-6-xy-ff-bug

**Comment by PEZ** [comment] 2018-04-06 09:08
Seems to be a dup of #10779.

**Comment by ncoden** [comment] 2018-04-10 21:48
Duplicate of https://github.com/zurb/foundation-sites/issues/10808

**Closed by ncoden** 2018-04-10 21:48 UTC
Labels: XY Grid

**Comment by ncoden** [comment] 2018-04-10 21:55
Actually a duplicate of https://github.com/zurb/foundation-sites/issues/10779, sorry. I got confused by the grid breaking with a standard browser font-size, but it's because you set `font-size: 62.5%` manually.

**Comment by PEZ** [comment] 2018-04-11 06:07
Thanks! That font setting is something we’ve inherited from before we switched to Foundation. I will now try find a way to set it properly.

**Comment by DanielRuf** [comment] 2018-04-11 06:53
`$global-font-size` in the settings.scss might be what you are looking for.

**Comment by PEZ** [comment] 2018-04-16 23:00
Thanks again for looking at it even though it was a dup and not even a bug proper. I got it working using `$global-font-size`.
