### ISSUE TITLE
[Off-canvas] Example Code in Documentation has FOUC problems - not usable

### ISSUE THREAD

**Issue by COLABORATI** [zurb/foundation-sites#8660] opened 2016-04-23 15:16 UTC
Searching for the solution for #8659 I am going through everything from zero. 

The [example](http://zurb.com/building-blocks/top-bar-with-off-canvas) linked from the off-canvas documentation comes with a FOUC problem. This is not acceptable. 

You just can not publish an example with such a heavy FOUC problems and say "people, look, this is how it is done!". This is a serious problem, not an aside, somebody in your house is missing this. 

You just can not publish unusable amateurish examples and keep on writing about "world class" and "enterprise" and stuff like that. You are generating a reputation problem not only for your company, but for everybody who uses zurb foundation.

Please update that example to a production grade quality or just remove it.

**Comment by colin-marshall** [comment] 2016-04-23 20:38
What browser and OS are you using? I see no FOUC. Only the small nav shows on the small breakpoint, and only the desktop nav shows from medium and up.

The only thing that doesn't load right away for me is the placeholder image below the navigation bar, but that is normal and has nothing to do with FOUC.

**Comment by gehasia** [comment] 2016-04-24 08:07
What an agressive bug report !!!!!
I'm pretty sure you're seing a FOUC where it's a normal behavior:
Small size -> drilldown menu
Widen the window, reaching the medium breakpoint and replace with a dropdown menu
Continue to widen, and the ZURB left toolbar will appear, toolbar wich is "off example" but which will size down the main content thus resizing it under small breakpoint -> It will fire the small breakpoint and the drilldown will replace the dropdown. It's normal, because of the left toolbar appearence resizing the content...
Continue to enlarge and the dropdown will fire after medium-breakpoint.

To polish things a bit, the solution would be force to force breakpoints of the example to lower values, so the ZURB left toolbar would not fire the small breakpoint.

Am I right ?

**Comment by colin-marshall** [comment] 2016-04-24 17:39
@gehasia that's the only thing that I can see that looks "off" with this example, but I'm not sure if that's even what @COLABORATI is referring to. I wouldn't consider that FOUC.

**Comment by colin-marshall** [comment] 2016-04-25 16:38
@COLABORATI I'm going to close this issue, assuming the FOUC you are referring to has to do with the iframe width changing between breakpoints (not to be confused with Foundation's breakpoints inside the iframe) on the building blocks site. As @gehasia mentioned, this is because the left toolbar changes widths, which makes the iframe width change.

**Comment by COLABORATI** [comment] 2016-04-25 21:07
Well, of course you should copy the code that is shown on that example page an test it in its own html file - there is a very clearly visible FOUC in all browsers I tested (Linux, Apple, Windows). This is not visible on the "Zurb University" Page where this example is presented.

**Comment by COLABORATI** [comment] 2016-04-25 21:44
@gehasia: yes, I am really frustrated with Foundation 6, since it was released I stumble from one bug or problem to another, this would have been absolutely no problem at all if it was still in alpha or beta status - but releasing this as "production ready" is the thing here that makes me feel bad. Wasted many, many hours with pre-alpha quality code. Hopefully F 6.5 will be on a good way to release quality, but until then much pain.

**Comment by colin-marshall** [comment] 2016-04-25 22:07
@COLABORATI thank you for clarifying. Not sure why this doesn't happen on the Building Blocks site, but I was able to reproduce locally. The same code that is recommended for preventing FOUC of the responsive navigation will work here:

#### SCSS
```scss
/* To prevent FOUC */
.no-js {
  @include breakpoint(small only) {
    .top-bar {
      display: none;
    }
  }

  @include breakpoint(medium) {
    .title-bar {
      display: none;
    }
  }
}
```

#### CSS
```css
/* To prevent FOUC */
.no-js .top-bar {
  display: none;
}

@media screen and (min-width: 40em) {
  .no-js .top-bar {
    display: block;
  }

  .no-js .title-bar {
    display: none;
  }
}
```

@kball @rafibomb please add the above SCSS & CSS to building block: http://zurb.com/building-blocks/top-bar-with-off-canvas

We should add this to the docs too.

**Comment by COLABORATI** [comment] 2016-06-25 13:37
Thanks, Colin, for the professional handling of this issue. 
However, the Zurb University example still has not been changed and has this problem - please fix that example or _remove it_, thanks!

**Comment by DanielRuf** [comment] 2018-03-13 21:36
I can not find it [here](https://foundation.zurb.com/building-blocks/)

**Comment by colin-marshall** [comment] 2018-03-14 16:33
@DanielRuf the building block is probably gone now. Between the time this issue was active and now, the building blocks were revamped and off-canvas was rewritten.

@brettsmason do you know of any FOUC issues with the newer off-canvas? Is this still something we should consider adding to the off-canvas docs?

**Comment by DanielRuf** [comment] 2019-08-03 17:05
Closing as this may not be relevant anymore.

**Closed by DanielRuf** 2019-08-03 17:05 UTC
Labels: Off-Canvas, building blocks, scss, 📖 documentation
