### ISSUE TITLE
Toggler - Toggle Two Different IDs at one time

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#7953] opened 2016-01-21 02:20 UTC
This is a feature request as I don't believe it's currently possible. 

The concept is to allow one button that controls two different ids. 

For example:

    <div id="front" class="front" data-toggler data-animate="hinge-in-from-middle-y hinge-out-from-middle-y">
      
    </div>

    <div id="back" class="back" data-toggler data-animate="hinge-in-from-middle-y hinge-out-from-middle-y">
      
    </div>

Then have one button that controls both divs: 

    <button data-toggle="back" data-toggle2="front">Click Me</button>

This is a the idea. Hopefully, it's something that wouldn't be too difficult to add. :)

**Comment by gakimball** [comment] 2016-01-21 07:50
Duplicate of #7806. We've found an increasing number of use cases for it in our own work, so we'll definitely add it at some point. :)

**Closed by gakimball** 2016-01-21 07:50 UTC
Labels: feature, javascript
