### ISSUE TITLE
IE11 Jitter when using sticky.zf

### ISSUE THREAD

**Issue by Camdor** [zurb/foundation-sites#11509] opened 2018-09-20 08:48 UTC
## What should happen?

Top menu should toggle between stuck and unstuck without making the page jitter

## What happens instead?

Top menu toggles between stuck and unstuck, along with making the page jitter up and down for a few seconds in the browser IE11

## Test Case and/or Steps to Reproduce (for bugs)

https://www.molnlycke.com

How to reproduce:
(In IE11)
1. Start at top of page
2. Scroll down to make the navbar unstick
3. Watch the site jiggle up and down for a while

## Your Environment

- Foundation version(s) used: 6.2.5
- Browser(s) name and version(s): Internet Explorer 11
- Device, Operating System and version: All tested Laptops and Desktops, Windows 8, 10

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment] 2018-09-20 21:28
Hi @Camdor :wave:,

This issue is a duplicate of #10846 and was already resolved in #10889. This will be availaible in `v6.6.0`. I'm closing this issue, feel free to reopen it if you think that the new upcoming feature does not match your needs.

**Closed by ncoden** 2018-09-20 21:28 UTC
