### ISSUE TITLE
Setting columns on grid-row is affecting all rows on the site

### ISSUE THREAD

**Issue by rogercoathup** [zurb/foundation-sites#9198] opened 2016-09-21 14:22 UTC
We are applying the grid-row mixin with a number of columns to selectively override a single row:

.content-inner {
  @include grid-row(24);
}

However we are finding that the column count is being to all rows on the site, not just the selected one.

**Comment by Deckluhm** [comment] 2016-09-21 15:17
The `grid-row` mixin accepts no parameters.

What you are looking for is the `grid-column` mixin (which works as expected).

Next time please try to reproduce your bug using a CodePen (as described in the issue template).
You may find that this is not a Foundation issue but something wrong in your code (and if it's really a bug it is super helpful for anyone who wants identify / fix the bug).

**Comment by rogercoathup** [comment] 2016-09-21 15:22
Check the documentation: http://foundation.zurb.com/sites/docs/grid.html#grid-row

The grid row mixin accepts quite a few parameters.  The columns one is used to increase the number of columns in a row... and no, it doesn't appear to be working.

p.s. I tried creating a CodePen, but it wouldn't accept SCSS mixins.

**Comment by kball** [comment] 2016-09-27 22:24
@zurbrandon can you take a look at this?

**Comment by rogercoathup** [comment] 2016-09-27 22:27
Thanks @kball -- looks like another user deleted their comment, which is why my second post seems odd.

**Comment by jarrydfillmore** [comment] 2016-10-16 23:25
great

**Comment by Deckluhm** [comment] 2016-10-17 11:58
@rogercoathup my bad, I replied too quickly with incorrect statements and I thought it was better to remove my comment (since it wasn't helping with your issue and no one replied in the meantime). I thought that you will have done the same thing!

**Comment by kball** [comment] 2016-10-24 21:32
@rogercoathup as per your comment in #8866, can you verify this was fixed in 6.2.4? Thanks!

**Comment by brettsmason** [comment] 2018-01-31 15:28
Looks like this was actually fixed in 6.2.4 so closing this.

**Closed by brettsmason** 2018-01-31 15:28 UTC
