### ISSUE TITLE
[Media Queries] Can't add xsmall

### ISSUE THREAD

**Issue by DusanMilko** [zurb/foundation-sites#8329] opened 2016-03-03 21:20 UTC
When I add a "xsmall" to the breakpoints in settings.scss I get an error because of the added checks in breakpoints.scss:

@else if map-get($breakpoints, small) != 0 {
  @error 'Your "small" breakpoint (defined in $breakpoints) must be set to "0".';
}

There should not be a force with small....

using with foundation scss

**Comment by andycochran** [comment] 2016-03-04 16:42
There are valid reasons `small` is required. But there's a solution in the works. See #8318.

**Comment by DaSchTour** [comment] 2016-03-04 16:46
Duplicate of #8257

**Comment by gakimball** [comment] 2016-03-04 16:56
@DaSchTour Yep yep

**Closed by gakimball** 2016-03-04 16:56 UTC
Labels: scss
