### ISSUE TITLE
6.2.4 Drilldown menu display bug

### ISSUE THREAD

**Issue by zerogeebers** [zurb/foundation-sites#9497] opened 2016-12-13 15:23 UTC
In Foundation 6.2.4, if a sub-menu in a drilldown menu has less slots than the previous menu, part of the previous menu will still be displayed (the part that doesn't get over-written by the sub-menu), i.e. the menu is not properly cleared when the next level is shown.

So let's say the first level of the drilldown menu has 4 slots, the second level has 2 slots, and the third level has 1 slot, as illustrated in [this codepen](http://codepen.io/zerogeebers/pen/bBmeLP). Drilling down into this menu will leave you with items from ALL three levels being displayed at the same time.

If I reference the CSS from 6.2.3 instead, then it works as intended with no remnants from previous levels being shown, just one level at a time as expected.

**Comment by ncoden** [comment] 2016-12-13 15:41
This is a duplicate of #9368 and have been fixed in #9473 for `v6.3.0-RC3`.

**Comment by kball** [comment] 2016-12-15 23:45
Fixed in the 6.3.0 release out TODAY :)

**Closed by kball** 2016-12-15 23:45 UTC
Labels: drilldown menu, duplicate
