### ISSUE TITLE
Zurb Template: 'ENOENT no bower.json present' documentation issue?

### ISSUE THREAD

**Issue by matthewhegarty** [zurb/foundation-sites#10280] opened 2017-06-28 13:10 UTC
If you follow the [instructions to install the Zurb Template](http://foundation.zurb.com/sites/docs/installation.html) then the `bower install` step fails.

The Foundation Sites installation documented on the same page works ok.

#### How to reproduce this bug:

1. Step one

Create a Zurb Template project following the steps [here](http://foundation.zurb.com/sites/docs/installation.html)

2. Step two

Following the instructions, run the following:

```
cd projectname
npm install
bower install
```
#### What should happen:

Either bower install should complete, or the `bower install` step should not be documented

#### What happened instead:
```
bower                           ENOENT No bower.json present
```

#### Browser(s) and Device(s) tested on:

- Linux (bash 4.3.11) 
- npm 3.10.10
- node 6.9.5

#### Foundation Version(s) you are using:

6.4.0

**Comment by Moonbase59** [comment] 2017-06-28 13:32
Duplicate of #10273 ?

**Comment by IamManchanda** [comment] 2017-06-28 17:26
Thanks @matthewhegarty but seems like this is already been requested.. i am gonna close it but feel free to reply with any concerns!

**Closed by IamManchanda** 2017-06-28 17:26 UTC

**Comment by yogeshwar143** [comment] 2017-11-03 12:51
bower install

bower                           ENOENT No bower.json present
