### ISSUE TITLE
[Slider] Two handle mode not initializing properly when data-start is not zero

### ISSUE THREAD

**Issue by sujayjaju** [zurb/foundation-sites#8846] opened 2016-05-25 13:51 UTC
**How can we reproduce this bug?**
1. Set the data-start and data-end to 50 and 150
2. Set the initial data to these values as well

**What did you expect to happen?**
The gray fill bar is supposed to stretch till the end

**What happened instead?**
The gray fill bar stops mid way

**Test case:**
Checkout the code pen: http://codepen.io/sujayjaju/pen/EyYNZM

**Comment by Silvester20** [comment] 2016-05-31 21:48
Also a single slider has this problem. 
In example: data-start="0" && data-end="100" && data-step="1" && data-initial-start=="50"

Probably @Owlbertz knows a fix for this?

**Comment by Owlbertz** [comment] 2016-06-03 12:06
Not yet, but I will dig around.

**Comment by hillmark** [comment] 2016-06-28 09:43
A quick look at the mark-up shows that: style="left: 0.50%;" is not applied initially, but only after the slider handle is moved, or bound input field value is changed.

**Comment by Owlbertz** [comment] 2016-07-04 08:32
I think what @hillmark pointed out may not be the root cause, but seems to be a workaround at least. Applying ```style="left: 0.50%;"``` to the first handle ```span``` fixes the initial behavior for me.

**Comment by kball** [comment] 2016-10-21 20:25
Just checked and this is still an issue in 6.2.4.  Looking into it.

**Closed** 2016-11-09 23:58 UTC
Labels: bug, javascript
