### ISSUE TITLE
Form error message doesn't work properly with inline label

### ISSUE THREAD

**Issue by marcusconnor** [zurb/foundation-sites#7802] opened 2016-01-07 18:06 UTC
Due to the way the form inline label is styled (using table display) the error message does not display properly. Here are three possible approaches to a fix:
1. Add extra HTML/CSS around the label (example linked)
2. Update javascript to look outside the parent for error message
3. Change the CSS for inline labels/inputs to not use table layout

I don't know what the best solution is, but I got number 1 working. The issue, and that fix may be seen [on this pen I made.](http://codepen.io/marcusconnor/pen/adpMrV)

**Comment by gakimball** [comment] 2016-01-08 17:46
The second solution seems ideal if we can make it work. As I recall, Abide tries to just magically find the error element that goes with the input, but we should have a way to manually associate them. Maybe by putting `aria-describedby` on the error?

**Comment by andycochran** [comment] 2016-01-08 21:35
Currently, inline labels don't actually use actual `<label>` tags. We could require a label wrap the whole thing and put the error inside it. 
```html
<label class="is-invalid-label">
  Money <!-- optional label text -->
  <div class="input-group">
    <span class="input-group-label">$</span>
    <input class="input-group-field is-invalid-input" type="number" required aria-invalid aria-describedby="foo">
  </div>
  <span class="form-error is-visible" id="foo">This field is required.</span>
</label>
```

**Comment by RLHawk1** [comment] 2017-03-17 18:43
Any update on this?

**Comment by SammyB** [comment] 2017-04-04 01:51
+1

**Comment by kball** [comment] 2017-04-17 20:50
I think the right answer here is probably to make Abide more specific... you should be able to point each element to its' error label, with fallback to the "default" magic finding.

**Comment by Quisp** [comment] 2017-04-24 02:13
Not sure if this is a proper fix, but keeping the span inside the label but adding data-abide-error attribute to it seems to fix the issue?

`                    <label>Email Address<sup class="required">*</sup>
                        <div class="input-group">
                            <span class="input-group-label"><i class="fi-mail"></i></span>
                            <input	class="input-group-field"
                                    id="signInEmail"
                                    name="signInEmail"
                                    value=""
                                    type="email"
                                    aria-describedby="formEmailHelpText1"
                                    placeholder="Email Address"
                                    required
                                    pattern="email">
                        <span data-abide-error class="form-error">
                            Email address is missing or not complete.
                        </span>
                    </label>

                    <p class="help-text"
                        id="formEmailHelpText1">
                        Please enter your email address.
                    </p>`

Perhaps someone else can check this?

**Comment by benjaminkohl** [comment] 2017-06-21 16:01
I'd definitely like to see a fix for this where we can do something like this on the input:
`data-abide-form-error="#myFieldFormErrorContainer"`

**Comment by zzplab** [comment] 2017-08-25 18:06
+1

**Comment by kball** [comment] 2017-08-29 23:11
@IamManchanda want to take a look at this as a part of your JS practice?

**Comment by svenkle** [comment] 2017-09-06 08:35
+1

**Comment by ahoefling** [comment] 2017-12-18 02:47
The markup recommended by @Quisp worked for me. I needed to add `data-abide-error` into my span outside of the group and it started working

**Comment by JeremyEnglert** [comment] 2018-01-27 05:38
@ncoden - should this be fixed in the upcoming version, or should be just update the docs? It seems like the work around listed above works.

**Comment by ncoden** [comment] 2018-01-28 08:28
@JeremyEnglert You're right. I'll update the docs.

**Comment by ncoden** [comment] 2018-01-28 18:15
I looked further and I can confirm that this is not a bug. Foundation automatically detect form errors in the same parent than the `<input>`, but we cannot extends this behavior without creating conflicts between fields.

Globally, this is always a good thing to explicitely declare relations between elements. So the recommanded usage is to use `data-abide-error="inputId"` to declare this relation without depending on the form error and field positions.

**Closed** 2018-02-10 20:11 UTC
Labels: Abide, bug, feedback wanted, forms, help wanted, javascript, scss
