### ISSUE TITLE
Magellan `.is-active` class not being applied.

### ISSUE THREAD

**Issue by denisahac** [zurb/foundation-sites#11651] opened 2019-01-15 05:45 UTC
When using `Magellan` as an individual module along with the required dependencies as per documentation suggested:

```
import { Magellan } from 'foundation-sites';

var $menu = $('#main-menu');
new Magellan($menu, options);
```

or

```
<script src="foundation-sites/dist/js/plugins/foundation.core.js"></script>
<script src="foundation-sites/dist/js/plugins/foundation.smoothScroll.js"></script>
<script src="foundation-sites/dist/js/plugins/foundation.magellan.js"></script>

<script>
  var $menu = $('#main-menu');
  new Foundation.Magellan($menu, options);
</script>
```
## What should happen?

`.is-active` class should be applied.

## What happens instead?

`.is-active` class not being applied.

## Possible Solution

The documentation doesn't state that `Triggers` is required when it fact, the module listens for custom event [`scrollme.zf.trigger`](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.magellan.js#L101)

The fix for the former, is to include the `Triggers` class on import

```
import { Triggers, Magellan } from 'foundation-sites';
```

For the later:

```
<script src="foundation-sites/dist/js/plugins/foundation.core.js"></script>
<script src="foundation-sites/dist/js/plugins/foundation.util.triggers.js"></script>
<script src="foundation-sites/dist/js/plugins/foundation.smoothScroll.js"></script>
<script src="foundation-sites/dist/js/plugins/foundation.magellan.js"></script>
```

## Solution

`Magellan` should work without explicitly importing `Triggers` for the framework users.

On `foundation-sites/js/foundation.magellan.js` explicitly define `import { Triggers } from './foundation.util.triggers';`

And for the later, modify the `Magellan` documentation page and state that `foundation.util.triggers.js` is required when using the module.

**Comment by DanielRuf** [comment] 2019-01-15 06:08
Duplicate of https://github.com/zurb/foundation-sites/issues/11645

**Closed by DanielRuf** 2019-01-15 06:08 UTC
