### ISSUE TITLE
[Top Bar] Link color not changing

### ISSUE THREAD

**Issue by misterjackjones** [zurb/foundation-sites#7690] opened 2015-12-25 22:16 UTC
**How can we reproduce this bug?**

1. Create a new site from Yeti Launch
2. Edit index.html so you've a topbar in it
3. Edit $topbar-link-color

**What did you expect to happen?**
Color is supposed to change I guess

**What happened instead?**
Color doesn't change

**Comment by gakimball** [comment] 2016-01-06 18:59
Might be an issue with Yeti Launch, not with the codebase specifically—looking into it!

**Comment by smth** [comment] 2016-01-06 19:05
I just created a site with Yeti Launch and found the same issue. Though it's not that is doesn't change, rather that it is being ignored from the start (otherwise you'd have `#fff` links on a light grey background). A project wide search for `$topbar-link-color` only finds one instance (in _settings.scss).

**Comment by gakimball** [comment] 2016-01-06 21:03
The issue is with Yeti Launch downloading an older version of Foundation—this bug was fixed in the latest version. We have a bug filed in our internal tracker for Yeti Launch, and we're working on it.

If you have a dev environment set up on your computer, you can update Foundation to the newest version (6.1.1) by running in your command line `bower install foundation-sites#6.1.1 --save` in the project folder.

**Closed by gakimball** 2016-01-06 21:03 UTC
Labels: awaiting reply, bug, scss

**Comment by misterjackjones** [comment] 2016-01-09 12:26
Thanks for the answer, it works fine
