### ISSUE TITLE
mixin css-triangle() up and down is oppsed

### ISSUE THREAD

**Issue by simongcc** [zurb/foundation-sites#8732] opened 2016-05-04 09:39 UTC
Foundation 6.2.1 SASS source

When I use
`@include css-triangle(rem-calc(8), $text-color, up);`
It generate downward arrow.
Expected: upward arrow

while I use
`@include css-triangle(rem-calc(8), $text-color, down);`
It generate upward arrow.
Expected: downward arrow

Left and Right is working as expected.
Many thanks.

**Comment by brettsmason** [comment] 2016-05-05 13:56
@simongcc I've just downloaded a fresh copy of 6.2.1 and up/down are working correctly for me.
Can you try with a fresh copy of 6.2.1 and see if it works?

**Comment by AdamBarnwell** [comment] 2016-06-26 00:56
@brettsmason, this appears to work for me also and this is a month old. Are we to assume it's not a bug? Should the issue be closed?

**Comment by andycochran** [comment] 2016-07-03 02:29
Works for me too. Closing. @simongcc, if this is still a problem for you with v6.2.3, please reopen this issue.

**Closed by andycochran** 2016-07-03 02:29 UTC
Labels: awaiting reply
