### ISSUE TITLE
[Breakpoints Issue]: Large - medium 1024px

### ISSUE THREAD

**Issue by GBratsos** [zurb/foundation-sites#7475] opened 2015-12-10 12:50 UTC
Hello,

I tried yesterday on an internal project to create something an one page template.

I run on this issue

```
<div class="medium-8 large-8 large-pull-2 columns>Lorem Ipsum</div>
}
```

By using this code on 1024px width (iPad landscape) the medium-8 class was overriden with the large classes. I tested in on Chrome mobile development view not a real iPad.

Can you test it ?

**Comment by EricWizKidOdom** [comment] 2015-12-10 16:23
I can verify that this is the case. An iPad in landscape is 1024px, which is technically large screen based on the new breakpoints. 

**Small**
0 - 639px

**Medium**
640px - 1023px

**Large**
1024px +

**Comment by zurbchris** [comment] 2015-12-10 19:10
Your breakpoints are fully customizable in the `_settings.scss` file. 
```scss
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
$breakpoint-classes: (small medium large);
```

**Comment by zurbrandon** [comment] 2015-12-11 00:21
This is by design, we're not targeting devices but widths. In our experince 1024 is great place for the large breakpoint on a good majority of screens. As @zurbchris mentioned these can be customized to your needs.

**Comment by GBratsos** [comment] 2015-12-11 18:10
I know about all the customization i can do with scss and i use it regularly.

I just tried the CSS version and i found that on 1024px width the large breakpoint class work. Maybe i am wrong.

**Comment by zurbrandon** [comment] 2015-12-11 22:16
Hm yeah, this is the desired effect. I'll close this for now, but if i'm misunderstanding that this is another issue than feel free to reopen.

**Closed by zurbrandon** 2015-12-11 22:16 UTC
Labels: scss
