### ISSUE TITLE
[Sticky] Error destroying plugin when no anchor is set in options

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#8636] opened 2016-04-20 05:23 UTC
I was having a look at the sticky plugin tonight and started to write the unit test for the constructor function of the plugin. I was able to get the test passing without issue. After each test the destroy method is used, and that shows as failing:

``` sh
  1) Sticky "after each" hook for "stores the element and plugin options":
     TypeError: 'undefined' is not an object (evaluating 'this.$anchor.off')
```

**To reproduce:**
1. Create sticky container & element
2. Destroy it
3. Check console and see this message:
   `TypeError: 'undefined' is not an object (evaluating 'this.$anchor.off')`

This happens when there is no anchor set in the options.

**Comment by gehasia** [comment] 2016-05-01 11:08
Hi !
This is a duplicate of 
https://github.com/zurb/foundation-sites/issues/8393

PR here
https://github.com/zurb/foundation-sites/pull/8719

**Closed** 2016-12-04 17:20 UTC
Labels: bug, javascript
