### ISSUE TITLE
[Dropdown Menu] Positions to the right instead of below

### ISSUE THREAD

**Issue by EFXPROMedia** [zurb/foundation-sites#8602] opened 2016-04-14 13:33 UTC
The dropdown on v6.2.1 on iPad mini or screen size 1024 wide has a misbehaviour on placement, a class is aplied to place at bottom but on screen size it places on the right of the element trigger.

**What did you expect to happen?**
Position at class determined positioning

**What happened instead?**
paired to right of trigger element on screen 1024

**Test case:**
https://www.dropbox.com/s/68x8vznbglzfjac/Screenshot%202016-04-14%2014.21.41.png?dl=0

Give us a link to a CodePen or JSFiddle that recreates the issue.
[http://codepen.io/RICARDOALVES/pen/redKML](%28http://codepen.io/RICARDOALVES/pen/redKML%29)

**Comment by Owlbertz** [comment] 2016-04-14 15:48
Hi. Your Fiddle looks odd because of the broken image references. Could you either put in a link to your site or adjust the Fiddle so that it recreates the issue better?

**Comment by EFXPROMedia** [comment] 2016-04-14 16:01
The link to the project:

http://building-bradshaws.worldsecuresystems.com/

**Comment by denisahac** [comment] 2016-04-14 17:59
In your project link the issue is on 1024px wider. 

Replicating the issue as follows:
1. Hover the menu(reveals the mega-submenu in the desired position)
2. Hover on any part of the revealed mega-submenu.
3. Hover back to the parent menu(Then, there goes the re-positioning issue)

What's weird is that in the codepen I can't replicate the issue in your website.

:confused:

**Comment by EFXPROMedia** [comment] 2016-04-14 19:21
For some reason the code pen doest behave the same, the site has only foundation working no other scripts.

I think to best resolve this is to script the behaviour to enable positioning the dropdown as a column size this way I think the user can position  as screen size responsiveness.

Also I have noticed that the dropdown-pane does not fill the row size when nested there, is it a bug or something I am missing on F6?

**Comment by denisahac** [comment] 2016-04-14 20:01
Also, in your "Shop Kitchen" link the drilldown menu re-positions after the 3rd step. Then when you hover back to the parent link it then re-positions the mega-menu. Another weird scenario is, when there's a drilldown menu it requires another hover to the parent link to replicate the mega-submenu position issue. 

Considering that your codepen sample doesn't replicate the issue in your website. I suspect that other script is causing the issue.

**Comment by EFXPROMedia** [comment] 2016-04-14 20:09
Theres no other scripts on this site apart from F6, I would have found already if it had.

When you return back for hovering thats a big bug on it! some script with css bug I guess.

**Comment by denisahac** [comment] 2016-04-14 20:44
Try resizing the output window of your codepen sample, another mega-submenu position issue in the "Shop Kitchen" link. Yeah, this is a ZF bug.

Anyway, a quick fix to your problem:

`.new-arrivals.dropdown-pane {
   width: 100% !important;
   left: 0 !important;
}`

Hope that helps @EFXPROMedia

**Comment by EFXPROMedia** [comment] 2016-04-18 20:49
thanks denisahac! that solved the problem for now

**Comment by Owlbertz** [comment] 2016-04-20 16:46
@denisahac While analyzing this, where you able to find the root cause in the Foundation code? If you, do you mind opening a PR for that?

**Comment by denisahac** [comment] 2016-04-21 13:40
@Owlbertz  This only exists according this his desired feature(Making a mega-submenu) which takes up the whole width of the parent container.

Since he modified the width of the `.dropdown-pane` to 100% to take up the whole space. No problem with any default ZF Dropdown implementation.

**Comment by EFXPROMedia** [comment] 2016-04-21 22:50
I have not had time enough to shred the script to find whats the problem so far looks alright but I can say a few other functionalities it lacks but its already built on F5:

- inherit the parent size example if it is inside a row> large-12 columns. it should automatically center and get the parent width, this would lessen code for sizing mega menus on fast production.

- Close on orientation device change, iPad mini tends to misplace the Dropdown pane and not close on change of orientation.

!! When customising Dropdown Pane sizes from the .scss it tends to misbehave positioning. the current overwrite is as above example by denisahac.

The best work around custom sizes I tried and maybe could be added to the .scss was:

```
.custom-class.dropdown-pane{
	width: 935px !important; 
        left: 50% !important; 
        margin-left: -467px !important;  
}
```
Maybe it could be added as follow:

// 16. Dropdown
// ------------

$dropdown-padding: 1rem;
$dropdown-border: 1px solid $medium-gray;
$dropdown-font-size: 1rem;
$dropdown-width: 300px;
$dropdown-radius: $global-radius;
**$dropdown-custom: true; ** //would overwrite the default width and enable custom size and position screen centered.
$dropdown-sizes: (
  tiny: 100px,
  small: 200px,
  large: 400px,
  **custom: 935px,**
);

**Comment by JeremyEnglert** [comment] 2018-02-01 23:23
This seems like an edge case and not a framework bug. Closing out.

**Closed by JeremyEnglert** 2018-02-01 23:23 UTC
Labels: bug, help wanted
