### ISSUE TITLE
Row > Column > * > Row : Wrong Margins

### ISSUE THREAD

**Issue by BicanMarianValeriu** [zurb/foundation-sites#9899] opened 2017-03-25 19:24 UTC
#### How to reproduce this bug:
```
<div class="row expanded">
<div class="column">
<div class="row">
</div>
</div>
</div>
```
I have this HTML

#### What should happen:
The child row should have margin auto. This happens only on flexbox.
#### What happened instead:
Second row floats to left.
#### Test case:

https://codepen.io/wecodeart/pen/ryrjRj

**Comment by IamManchanda** [comment] 2017-03-26 04:52
Although not released in latest foundation but this is already solved in `develop` branch 
( attaching screenshot below too of local testing too )
Thanks for reporting though!

Dupe of #9729 & fixed in #9730 

@BicanMarianValeriu ... i would request to close this if your issue is resolved!

-------------------------------------------------------------------------------------------------------------------

![screenshot-newtab 2017-03-26 10-17-16](https://cloud.githubusercontent.com/assets/4970624/24328691/a75d0868-120d-11e7-8c99-a577193ab14f.png)

**Closed** 2017-03-26 07:07 UTC
