### ISSUE TITLE
close button - scss error - (small:1.5em,medium:2rem) isn't a valid CSS value.

### ISSUE THREAD

**Issue by gpspake** [zurb/foundation-sites#9310] opened 2016-10-31 17:21 UTC
This is a little strange but I'm getting the following error related to this block in the 6.2.4 settings.scss file
```
// 14. Close Button
// ----------------

$closebutton-position: right top;
$closebutton-offset-horizontal: (
        small: .66rem,
        medium: 1rem,
);
$closebutton-offset-vertical: (
        small: .33em,
        medium: .5rem,
);
$closebutton-sizes: (
        small: 1.5em,
        medium: 2em,
);
```
Error:
```
Message:
    bower_components/myfoundation/scss/_settings.scss
Error: (small:0.66rem,medium:1rem) isn't a valid CSS value.
        on line 349 of bower_components/emerald/scss/_settings.scss
>>         small: .66rem,
   --------^

Error in plugin 'sass'
Message:
    bower_components/myfoundation/scss/_settings.scss
Error: (small:0.66rem,medium:1rem) isn't a valid CSS value.
        on line 349 of bower_components/emerald/scss/_settings.scss
>>         small: .66rem,
   --------^
```

The strange thing is that this syntax is used all over the settings file with no problem; in fact, if I comment out the rules in the first two variables, but leave them in the third, shich uses the exact same syntax, it works fine.
```
// 14. Close Button
// ----------------

$closebutton-position: right top;
$closebutton-offset-horizontal: (
        //small: .66rem,
        //medium: 1rem,
);
$closebutton-offset-vertical: (
        //small: .33em,
        //medium: .5rem,
);
$closebutton-sizes: (
        small: 1.5em,
        medium: 2em,
);
```
Why wouldn't I get the same error for that $closebutton-sizes variable

Hopefully this is just user error. 
Here are my dependencies as listed in package.json in case I'm using the wrong version of sass or something. It appears to be correct though.
```
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.2.0",
    "gulp-concat": "^2.6.0",
    "gulp-load-plugins": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.5.1"
  },
```

**Comment by geraldyeo** [comment] 2016-12-03 02:09
I am getting the same issue.

**Comment by Erbenos** [comment] 2016-12-15 23:16
Same issue here too. Any ideas?

**Comment by kball** [comment] 2016-12-15 23:18
Very odd.  Can you try using a leading 0 on the values that are <1? e.g. `0.66rem` instead of `.66rem` and let me know if it makes a difference?

**Comment by Erbenos** [comment] 2016-12-15 23:20
My version of settings file already has this precaution used, yet it still throws an error.

**Comment by kball** [comment] 2016-12-15 23:24
Ah interesting.  Digging into it more, it looks as though the issue is a difference in setting value between 6.3.0 and 6.2.4.   In 6.2.4, the $closebutton related variables were all scalar, while in 6.3.0 they were moved to be responsive maps...

I'm not sure why you're ending up with the 6.3 settings defaults in a 6.2.4 project, can you explain a little more how you got this set up?

**Comment by Erbenos** [comment] 2016-12-15 23:26
Probably didn't update my npm_modules directory for few weeks, but didn't copy settings file from older  project - instead got a new one from master branch. So there could have been a version mismatch.

Thank you for help.

**Comment by ncoden** [comment] 2016-12-16 00:34
`...isn't a valid CSS value` is not throw by an incorrect value in SCSS, but by a SCSS-only value (map, some strings...) generated as CSS. Because of the bad error handling of Sass, it can appear when you pass a SCSS-only value to an undeclared function.

**Comment by rafibomb** [comment] 2017-02-07 00:41
Based on @kball 's solution - we'll close this here. Thanks!

**Closed by rafibomb** 2017-02-07 00:41 UTC

**Comment by stephane-r** [comment] 2017-06-28 14:44
@rafibomb Same issue in 6.4.0, but with `$grid-column-gutter`
