### ISSUE TITLE
Exiting Off Canvas menu in Microsoft Edge page scrolls bottom

### ISSUE THREAD

**Issue by cliveeastgate** [zurb/foundation-sites#7746] opened 2016-01-02 23:41 UTC
I have a page with an Off Canvas menu which works fine in Chrome and Firefox.  However in Microsoft Edge, when  I click away from the menu and it closes and then the current page scrolls to the bottom.

Are there any changes that need to be made on the page to make Off Canvas work in Edge?

**Comment by rafibomb** [comment] 2016-01-05 01:00
DO you have an example link so we can replicate it?

**Comment by cliveeastgate** [comment] 2016-01-05 10:58
You can see this at test.beembroidered.co.uk

**Comment by colin-marshall** [comment] 2016-04-29 17:27
I'm closing this issue because we don’t have a reproducible case to test against. If this is still an issue, please reopen with the info requested here:
https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

**Closed by colin-marshall** 2016-04-29 17:27 UTC
Labels: bug, javascript
