### ISSUE TITLE
Cannot call method 'split' of null

### ISSUE THREAD

**Issue by SylarRuby** [zurb/foundation-sites#7896] opened 2016-01-16 17:55 UTC
Just a heads up lovely peeps at zurb. This breaks meteor 1.3 beta 4.

```
TypeError: Cannot call method 'split' of null
    at /tools/isobuild/linker.js:231:38
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/sylar/.meteor/packages/meteor-tool/.1.1.11-modules.5.gs455p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules
```

**Comment by zurbchris** [comment] 2016-01-18 17:21
Can you let us know what plugin or method is breaking?

**Comment by gakimball** [comment] 2016-01-18 19:11
Also @juliancwirko can you offer any insight?

**Comment by juliancwirko** [comment] 2016-01-18 20:00
I test it for the first time and it seems that there are problems with npm and motion-ui. For now we have:
```
Npm.depends({
  'motion-ui': '1.1.0'
});
(...)
api.addFiles('.npm/package/node_modules/motion-ui/dist/motion-ui.css', 'client');
api.addFiles('.npm/package/node_modules/motion-ui/dist/motion-ui.js', 'client');
(...)
```
Now in 1.3 it probably can't be used like that.
We probably need another Meteor package for Motion-ui.  It should be simple to do because Motion-ui has its own repo. It will be much cleaner too.
Also I think this library should be optional and now it is required by some of the Foundation's plugins (as far as I know).

The second problem is that when I want to test it locally and I `git clone` all to the `packages` it will not run because in v1.3 Meteor can see also files which are not added in the `addFiles` rule and it can't manage it. I don't know exactly why. For me it looks like a bug in 1.3 beta version.

For now I think the best solution is to wait for official Meteor 1.3 release with official docs on how to use packages. We eventually can prepare Motion-ui meteor package, for example `zurb:motion-ui` then we can add it in the `zurb:foundation-sites` as a dependency so we don't have to use npm package here.

Also I'll try to ask on the Meteor forums why Meteor 1.3 sees all the files in the local package. This is quite important because Foundation for Meteor hasn't its own repo (with files only for Meteor) and testing it locally is very hard with Meteor 1.3.

**Comment by juliancwirko** [comment] 2016-01-18 20:26
... also I am not sure if we need Meteor package in Meteor 1.3 It will have standard Npm support, and maybe it will be simpler to just instal Foundation from Npm.

**Comment by gakimball** [comment] 2016-01-18 20:28
@juliancwirko I can get behind that.

**Comment by zurbchris** [comment] 2016-01-18 20:31
:+1: 
One addition though, Motion-UI is no longer required by any plugin as of Orbit getting a fallback for slide changing, and a bug fix for Toggler/Close Button.

**Comment by juliancwirko** [comment] 2016-01-18 20:37
Foundation and Motion-UI is on NPM registry. I wonder if Meteor 1.3 users will want to have Meteor packages with Foundation and Motion at all. Because they'll be able to just include it in the packages.json in the Meteor app and install it through Npm. I think we could wait for Meteor 1.3 and then decide. Or if you want there could be also Meteor package for both.

**Comment by gakimball** [comment] 2016-01-18 20:39
@juliancwirko It's not a huge hassle to keep publishing the package for now, and it's possible that there will be folks who can't upgrade to 1.3 right away, so we can keep it around.

But since we don't plan on doing anything Meteor-specific with the framework, transitioning users to npm makes sense.

**Comment by juliancwirko** [comment] 2016-01-18 20:51
It sounds reasonable. So we can publish `zurb:motion-ui` on the Atmospherejs.com and then modify `package.js` in `zurb:foundation-sites` We can remove Motion-UI at all. We can only add a week dependency ([http://docs.meteor.com/#/full/pack_use](http://docs.meteor.com/#/full/pack_use)) because now it is not needed and if people want Motion-UI they will be able to add it (by `meteor add zurb:motion-ui`) and it should play well with Foundation package and also as a standalone library.

Anyway there is a problem with local testing and not needed Scss files in Foundation repo. I mean when we clone Foundation to `/packages` folder in Meteor app. I've tested it with Stylus and there is the same problem. Meteor bundles files which we don't want to. We want only those which are added in `addFiles` so I think this is a bug in 1.3 beta. I'll try to find out what's going on.

**Comment by gakimball** [comment] 2016-01-19 00:13
@juliancwirko So if:

- The problem is with our Atmosphere package when used in Meteor 1.3
- Meteor 1.3 has first-class support for npm

Can we consider this a non-issue, given our recommendation to 1.3 users will be to use the npm package instead?

**Comment by juliancwirko** [comment] 2016-01-19 01:11
I think yes, but for now there are problems with .scss files imports from `node_modules` This is because Meteor has a specific build plugin for scss and also it is a community package (3rd party) so maybe it needs to be prepared too. I hope that till official Meteor 1.3 it will be working well. There are similar problems on the forum [here](https://forums.meteor.com/t/material-ui-and-meteor-1-3-npm/16439?u=juliancwirko)

I'll try to do more research ASAP (for now I have 2:10 AM here ;) so probably in a few hours)

**Comment by gakimball** [comment] 2016-01-19 01:13
Alright, I'll close this for now, but do keep us in the loop. :) Since Meteor 1.3 is still in beta this is sort of out of our hands.

**Closed by gakimball** 2016-01-19 01:13 UTC
Labels: awaiting reply, bug, meteor

**Comment by juliancwirko** [comment] 2016-01-19 09:39
Ok there are two issues reported by me which we can track:

- [Style files imports from node_modules](https://github.com/meteor/meteor/issues/6037)
- [Style files in local packages](https://github.com/meteor/meteor/issues/6036)
