### ISSUE TITLE
[Responsive Navigation] menu of topbar items are out of view

### ISSUE THREAD

**Issue by timaschew** [zurb/foundation-sites#8142] opened 2016-02-12 00:36 UTC
**How can we reproduce this bug?**

1. create navigation with the top bar like in the docs
2. create 7 items on root level (not as a sub menu)
3. shrink scree size

**What did you expect to happen?**

UX is friendly and all menu items can be accesses

**What happened instead?**

Item are accessable but when you scroll, you scroll out of the container and outer border, looks broken.

**Comment by rafibomb** [comment] 2016-02-12 23:26
Are you able to share an example so we can dig into this? http://codepen.io/rafibomb/pen/NxovRj

**Comment by timaschew** [comment] 2016-02-12 23:36
Sure: http://codepen.io/anon/pen/jWdLBa

**Comment by muhammetm** [comment] 2016-02-14 15:10
I got the same issue when having the dropdown menu on the far right of the top-bar. Foundation 5's dropdown menu worked and looked a lot better imho.

**Comment by timaschew** [comment] 2016-02-26 10:56
any feedback @zurbchris @gakimball

**Comment by gakimball** [comment] 2016-03-02 20:05
The current dropdown plugin isn't super mobile-friendly, although that also begs the question *how* you make it mobile-friendly. If you have ideas, we're all ears.

In the mean time, this is why we created the Responsive Menu plugin: so you can convert from a mobile-friendly drilldown or accordion menu, to a dropdown menu on desktop.

In your CodePen, I swapped out the data attributes on the dropdown menu to read like this:

```html
<ul class="dropdown menu" data-responsive-menu="drilldown medium-dropdown">
```

I also updated the CSS/JS to version 6.2.0, and it works very well. Let me know if a solution like that works for you.

**Comment by timaschew** [comment] 2016-03-02 21:12
:+1: Looks much better with drilldown and the new JS version seems also to fix some visual stuff.
But the last item is still out of view if I shrink the window width to the most thin value. It's even not accessable by scrollinng (it doesn't scroll at all anymore).

I added 

```css
.menu.drilldown {
  overflow-x: scroll;
}
```
now and the menu become scrollable
http://codepen.io/timaschew/pen/eZNEvj?editors=1100

But there is another issue with the right topbar (`.top-bar-right`) 
It's at the bottom of the page, it seems that the drilldown does reserve some height.

Another strange thing is that this markup
`<ul class="dropdown menu">` is transformed to `<ul class="menu drilldown">`
This is just not expected by the user. I was wondering why my selector `.dropdown.menu` wasn't working.

**Comment by JeremyEnglert** [comment] 2016-04-28 16:53
I'm not 100% sure this is a bug. As previously mentioned, getting this to work on mobile would be extremely tricky.

The responsive menu component allows you to use a more mobile friendly menu type on small screens. This seems like the best way to address the issue.

@brettsmason, @andycochran - thoughts? I'm leaning towards closing this.

**Comment by andycochran** [comment] 2016-04-28 17:28
Agreed. Seems like an edge case.

**Comment by brettsmason** [comment] 2016-04-28 17:33
I think the problem is more down to

**Closed** 2016-04-28 17:35 UTC
Labels: awaiting reply, javascript
