### ISSUE TITLE
"Inline Labels and Buttons" is broken

### ISSUE THREAD

**Issue by imaia** [zurb/foundation-sites#7403] opened 2015-12-04 19:39 UTC
"Inline Labels and Buttons" is broken:
http://foundation.zurb.com/sites/docs/forms.html#inline-labels-and-buttons
![error](https://cloud.githubusercontent.com/assets/14771411/11599409/89e716e2-9aa5-11e5-994e-ff814ed2fba2.png)

F5 and CTRL+R did not do the trick here.

**Comment by gakimball** [comment] 2015-12-04 22:52
Duplicate of #7373

**Closed by gakimball** 2015-12-04 22:52 UTC
Labels: bug, scss
