### ISSUE TITLE
[Visibility Classes] data-hide-for medium not working for title-bar + top-bar

### ISSUE THREAD

**Issue by heliohm** [zurb/foundation-sites#8637] opened 2016-04-20 08:28 UTC
**Setup**

Foundation v6.2.1 (foundation-rails)
Firefox (latest)
Chrome (latest)
Ubuntu 15.10

**Description**

While reproducing the Foundation 5 top bar as described in a Zurb University lesson [1] I see that when a link is clicked (to e.g. "/" with screen size > medium, the following happens:

* Both the title bar and top bar is shown stack on top of each other. Refreshing the page makes it appear correctly again.
* Shrinking the screen to small causes menu to display correctly but menu icon is non-responsive.

**Test case:**

1: Opened attached saved web site with a medium width browser window
[ruutr-foundation.zip](https://github.com/zurb/foundation-sites/files/228444/ruutr-foundation.zip)

Modifications to Foundation base style are found in _foundation_ruutr.css_

2: Click the "Ruutr" link to index.html
3: Both top bar and title bar shows at the same time.
![screenshot](https://cloud.githubusercontent.com/assets/2904917/14668018/62e6fbbc-06e2-11e6-84e8-277ad953def0.png)

**Comment by denisahac** [comment] 2016-04-20 09:51
You need to make sure you referenced the foundation.js file and call the `$(document).foundation()`. If you're sure you included those files then make sure the path are correct.

**Comment by heliohm** [comment] 2016-04-20 12:45
Forgot to include reference above:
[1]https://zurb.com/expo/lessons/how-to-re-create-top-bar-with-foundation-6

**Comment by denisahac** [comment] 2016-04-20 13:57
I can't reproduce the issue you're experiencing. Try checking the browser network tab for some missing resources if there's any.

**Comment by heliohm** [comment] 2016-04-20 18:50
Update zip file attachment, asset folder contained letter "|" which caused it not to show in Windows.

I just tested the contents of the zip file on Win 7 (Chrome + IE11) and the example works perfectly fine here. It seems to be an issue on Ubuntu only for now.

**Comment by colin-marshall** [comment] 2016-04-22 18:11
Are there any errors in the console? If they're both appearing at the same the JavaScript is probably not functioning in the browser like it's supposed to. Test some other components that require javascript (accordions for example) and see if they function normally. Interesting that this is only happening on Ubuntu.

Have you tried moving all the scripts to just before the closing body tag?

**Comment by heliohm** [comment] 2016-04-23 08:35
There is indeed a warning in the Chrome console:
" Tried to initialize responsive-menu on an element that already has a Foundation plugin".

Setting a breakpoint here in the JS shows that element causing the warning is ul.menu.dropdown.vertical.medium-horizontal.

Not sure what I have done wrong but will look more into it.

**Comment by heliohm** [comment] 2016-04-25 20:21
The problem goes away when turbolinks are removed from application.js. Turbolinks seems like it is having a lot of issues with Jquery and Foundation.

I didn't see the issue on Windows since I am simply opening the index.html file in Chrome which causes turbolinks.js to crash it seems. 
On Ubuntu I am running the server at 127.0.0.1:3000 mapped to example.com with the /etc/hosts file.

**Closed** 2016-04-25 21:04 UTC
