### ISSUE TITLE
jQuery 3 support request

### ISSUE THREAD

**Issue by umphy** [zurb/foundation-sites#8834] opened 2016-05-24 00:48 UTC
This is not a bug, but a question / request.

Are there any plans in the near future to support jQuery 3 given that RC1 was just released recently? jQuery 3 has the same IE support (9+) as Foundation 6, so it would seem a good fit.

**Comment by IamManchanda** [comment] 2016-05-24 04:55
+1

**Comment by DaSchTour** [comment] 2016-05-24 08:02
But I think this should be optional. For bigger projects it's not easy to move to jQuery 3.

**Comment by waleedka** [comment] 2016-05-27 19:45
At the very least, Foundation should stop using deprecated functions. We tested jQuery 3.0RC on our site but got errors in Foundation because it's still using .load() event handlers that have been deprecated since jQuery 1.8. 

https://api.jquery.com/category/deprecated/

**Comment by silverelizard** [comment] 2016-06-10 18:46
Made a PR (https://github.com/zurb/foundation-sites/pull/8923) to remove references to .load()

**Comment by dmethvin** [comment] 2016-06-24 13:07
As an interim measure it should be possible to simply put [jQuery Migrate 3.0](https://github.com/jquery/jquery-migrate#readme) into the site to shim the deprecated functionality.

**Comment by jay-codes** [comment] 2016-08-04 09:32
+1

**Comment by jwvanderbeck** [comment] 2016-09-02 18:34
Ran into this today.  What is the status of this?  As pointed out this is a function that has been deprecated for a very long time, so shouldn't be used regardless.  It was deprecated I think even before JQuery 2

**Comment by andrewjmead** [comment] 2016-09-08 19:24
+1

**Comment by isaak-ordonez** [comment] 2016-09-08 20:04
+1

**Comment by tyteen4a03** [comment] 2016-09-13 20:19
+1

**Comment by sammykumar** [comment] 2016-09-20 15:31
+1

**Comment by olthof** [comment] 2016-09-21 03:59
+1 It's been out for 3 months, would love official support for this.

**Comment by romelperez** [comment] 2016-09-23 10:37
+1

**Comment by kball** [comment] 2016-09-27 22:56
This is fixed in develop, will be released in 6.2.4 in the next few weeks.

**Comment by olthof** [comment] 2016-09-28 04:39
@kball Does this mean Foundation's JS is compatible with jQuery 3, or does it mean that the version of jQuery that ships with will be jQuery 3? For example in the node package, **node_modules\foundation-sites\vendor\jquery\**

**Comment by kball** [comment] 2016-09-28 17:49
Great question @olthof - as of now we're packaging up 2 still, but 3.0 is supposed to be slimmer and faster, so seems like perhaps we should upgrade the default.

@colin-marshall @Owlbertz what are your thoughts?

**Comment by beaubothavich** [comment] 2016-10-02 07:05
+1

**Comment by DaSchTour** [comment] 2016-10-02 08:24
Why is jquery shiped together with foundation? I never used it and even didn't know it's done this why. I think it would be best to let the user choose the version. Every packagemanager will handle the dependencies and if somebody isn't using a packagemanager he must be aware of the fact, that he needs to resolve dependencies by himself.

**Comment by HaddagAbdelkader** [comment] 2016-10-02 09:56
JQuery is well known framework having a package manager will force Zurb to
handle all the differences between the versions which is itself a project
called version control. If Zurb adds this feature it will be a great deal
or rework on the optimization part.

**Comment by user58258** [comment] 2016-10-22 15:05
@kball 

What were you referencing here?

> This is fixed in develop, will be released in 6.2.4 in the next few weeks.

6.2.4 is just recent;y bower-available, but an update still leaves with jQuery 2x.

    foundation-sites#6.2.4 bower_components/foundation-sites
    ├── jquery#2.2.4
    └── what-input#2.0.1

Can we, and how, get tp F6 + jQuery 3 (yet)?

**Comment by tyteen4a03** [comment] 2016-10-23 21:22
No problems on the npm side. Probably a misconfiguration in bower.json?

**Comment by user58258** [comment] 2016-10-24 02:51
@tyteen4a03 

here's what I've got currently:

    cd <proj root>
    cat bower.json
        {
          "name": "test-site",
          "description": "===",
          "main": "gulpfile.babel.js",
          "license": "ISC",
          "homepage": "",
          "ignore": [
            "**/.*",
            "node_modules",
            "bower_components",
            "test",
            "tests"
          ],
          "dependencies": {
            "foundation-sites": "^6.2.4",
            "jquery": "^3.1.1"
          },
          "private": true,
          "resolutions": {
            "jquery": "^3.1.1"
          }
        }

    cat bower_components/foundation-sites/bower.json
        {
          "name": "foundation-sites",
          "version": "6.2.4",
          "license": "MIT",
          "main": [
            "scss/foundation.scss",
            "dist/foundation.js"
          ],
          "ignore": [
            "config",
            "docs",
            "gulp",
            "lib",
            "test",
            "composer.json",
            "CONTRIBUTING.md",
            "gulpfile.js",
            "meteor-README.md",
            "package.js",
            "package.json",
            "sache.json",
            ".editorconfig",
            ".npm",
            ".gitignore",
            ".npmignore",
            ".versions",
            ".babelrc"
          ],
          "dependencies": {
            "jquery": "~3.1.0",
            "what-input": "~2.0.0"
          }
        }

**Comment by tyteen4a03** [comment] 2016-10-24 03:31
Have you tried deleting `bower_components` and re`install`ing?

**Comment by user58258** [comment] 2016-10-24 04:47
@tyteen4a03 

> Have you tried deleting bower_components and reinstalling?

Multiple times, as well as complete clean installs.  Reproducible as above

> Also, resolutions shouldn't be needed.

Is that  a comment to/for me?  I certainly didn't add that ... manually anyway ...

**Comment by colin-marshall** [comment] 2018-01-27 06:45
Closing this out since we have been using jQuery 3+ for awhile now. Feel free to reopen if you feel I have done so in error.

**Closed by colin-marshall** 2018-01-27 06:45 UTC
Labels: feature request
