### ISSUE TITLE
gulp-sourcemaps does not work in javascript() of gulpfile.babel.js

### ISSUE THREAD

**Issue by RisaHigashiyama** [zurb/foundation-sites#10524] opened 2017-08-08 17:01 UTC
#### How to reproduce this bug:

Use gulp-sourcemaps and webpack.

#### What should happen:

A Source Maps is added as a DataUrl to the bundle.

#### What happened instead:

Nothing is added.

#### Foundation Version(s) you are using:

v 6.4.1

---

gulp-sourcemaps seems to be incompatible with webpack.

- (https://github.com/gulp-sourcemaps/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support)

And in the webpack-stream document:

> If you need further special handling of source maps, such as using with gulp-sourcemaps then just pipe to a stream and handle the source map files emitted by webpack:

- (https://github.com/shama/webpack-stream#source-maps)

I used the setting `devtool: 'inline-source-map'` of webpack. And it worked.

But, Chrome devtool doesn't recognized source map urls produced with 'inline-source-map'.
It may be a Chrome bug. Because firefox recognized it.

**Comment by DanielRuf** [comment] 2018-03-05 07:18
> gulp-sourcemaps seems to be incompatible with webpack

Using gulp with webpack may not be the best solution.

Anyway, I close this issue as this is not a bug on our side but in gulp-sourcemaps in combination with webpack.

**Closed by DanielRuf** 2018-03-05 07:18 UTC
Labels: Gulp, build
