### ISSUE TITLE
Accordion Menu -- 'aria-multiselectable' is not an allowed attribute for aria role 'menu'

### ISSUE THREAD

**Issue by ctcpip** [zurb/foundation-sites#10061] opened 2017-05-21 23:05 UTC
The accordion menu adds `role="menu"` for the `<ul>` and adds the `aria-multiselectable="true"` attribute, which is not allowed for the 'menu' role.

See: https://www.w3.org/TR/wai-aria/states_and_properties#aria-multiselectable

**Comment by ctcpip** [comment] 2017-05-21 23:31
It also gets applied elsewhere.  It appears the attribute should not be added on any of these:

https://github.com/zurb/foundation-sites/search?utf8=%E2%9C%93&q=aria-multiselectable&type=

**Comment by IamManchanda** [comment] 2017-05-22 09:07
Dang!!
cc @kball @Owlbertz

**Comment by IamManchanda** [comment] 2017-05-22 09:12
@ctcpip An accordion is a `tablist` btw .... just that being used in menu.
Marius what do you think about this ??

**Comment by Owlbertz** [comment] 2017-05-22 12:02
Refering to [my comment for a pending PR](https://github.com/zurb/foundation-sites/pull/9348#issuecomment-300390820), in my opinion `menu` is the wrong role for that case. If `tree` would be used as I suggested, `aria-multiselectable` would be working as intended.

**Comment by IamManchanda** [comment] 2017-05-22 12:27
In that case @kball .... Shall we make a point fix for 6.3.2 if that PR and suggestion will take some time??

**Comment by rafibomb** [comment] 2017-05-22 16:40
6.4 is the next release - so it would be best to make this a separate update to use the `role="tree"`

@Owlbertz Are you able to submit this as a PR against the develop branch?

**Comment by Owlbertz** [comment] 2017-05-22 16:53
Yeah.

**Comment by rafibomb** [comment] 2017-05-22 17:01
Sorry - @IamManchanda has it right - for the 6.3.2 release since it's not a breaking change

**Comment by ctcpip** [comment] 2017-05-22 17:46
Wow.  Awesome response time!  Looking forward to the fix.  Didn't want to submit a PR because there are different ways to resolve this.  Thanks everyone.

**Comment by IamManchanda** [comment] 2017-05-22 18:42
Thanks @ctcpip 
Yes We are `Yetis` and Yetis are awesome! :wink:

**Comment by rafibomb** [comment] 2017-05-22 18:44
PR merged thanks @Owlbertz !

@ctcpip Thanks for the report and No worries - you can submit a pr and we'll offer suggestions or you can offer a suggestions and we'll guide you!

**Closed by rafibomb** 2017-05-22 18:44 UTC
Labels: accessibility
