### ISSUE TITLE
Foundation Uncaught TypeError: elem.getBoundingClientRect is not a function()

### ISSUE THREAD

**Issue by enochfernandez** [zurb/foundation-sites#11505] opened 2018-09-17 19:15 UTC
## What should happen?

When dropdown menu component is included in html it should work as known. 

## What happens instead?
The dropdown list doesnt work. The ul list just show a list without dropdown and I working with angular 6 on this. this happens when I place it the dropdown component in a structural directive such as *ngFor.
...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.
no idae

## Context

...

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Google Chrome
- Device, Operating System and version: IOS
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

![foundationerror](https://user-images.githubusercontent.com/14158121/45644524-35904500-babe-11e8-8cac-357ff73d992e.PNG)

I am working with foundation and angular and I have this 
     `ngAfterViewInit() {
          $(document).foundation();
        }`
defined and everything works, my modals, dropdowns and all, but as soon as I put these into structural directives such as `ngFor` I get the error above. Please help would be appreciated, I cant continue my project.

**Comment by DanielRuf** [comment] 2018-09-17 21:30
Please provide a codepen which reproduces this.
Also check line 192 of zone.js.

It also seems you deleted our issue template so we can not help you.

**Comment by enochfernandez** [comment] 2018-09-18 07:42
Can you make clear what you mean by deleted your issue template? And yes I do see zone.js but I dont know what it means.

**Comment by DanielRuf** [comment] 2018-09-18 08:03
We have issue templates, see https://github.com/zurb/foundation-sites/issues/new/choose

**Comment by DanielRuf** [comment] 2018-09-18 08:03
> Can you make clear what you mean by deleted your issue template? And yes I do see zone.js but I dont know what it means.

Please check the code in line 192 and what is written there. There is probably just an element missing.

**Comment by enochfernandez** [comment] 2018-09-18 08:11
I created a bug report by the link you sent me. And also can you check 
[https://stackoverflow.com/questions/52376558/foundation-and-angular-menu-dropdown-component-not-working](url)
Can yo please check this issue I asked on stackoverflow because it seems the issue is with dropdown menu, becuase modal is working just fine. Solutions available is to rearrange the dropdown but its everything seems to be in the right order as I am working with version 6.4.3

Will check the project and the line 192 as well soon as I dont have access to the project now.

**Comment by DanielRuf** [comment] 2018-09-18 08:16
> I created a bug report by the link you sent me

No, because then we would have additional data like a codepen link and exact information about your environment.

**Comment by DanielRuf** [comment] 2018-09-18 08:17
See https://github.com/zurb/foundation-sites/issues/new?template=1-bug-report.md

This template should not be removed. Either edit your first comment in this issue and update the template according to your issue or create a new one and close this.

**Comment by DanielRuf** [comment] 2018-09-18 08:29
I've updated your issue. Please replace the `...` parts.

**Comment by DanielRuf** [comment] 2018-09-18 08:30
![bildschirmfoto 2018-09-18 um 10 30 16](https://user-images.githubusercontent.com/827205/45674672-dc5ffa00-bb2d-11e8-920d-d7978b34fb5a.png)

**Comment by ncoden** [comment] 2018-09-20 21:20
Hi @enochfernandez :wave

Thank you for your issue. We provide a [template](https://github.com/zurb/foundation-sites/issues/new?template=1-bug-report.md) for bug reports to get all the information we need to reproduce and resolve the bug.

Please follow the template and provide us a way to reproduce a bug. You can find help in the template itself and the [CONTRIBUTING.md](https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md#issues) document.

I am closing this issue for now. Feel free to reopen it once you edited it so it provides all the required informations.

**Closed** 2018-09-20 21:21 UTC

**Comment by radiantone** [comment] 2020-02-06 13:36
Problem still exists. Y'all can squabble about formalities or get on with a proper fix.

foundation.esm.js:1058 Uncaught TypeError: t.getBoundingClientRect is not a function
    at E (foundation.esm.js:1058)
    at Object.GetExplicitOffsets (foundation.esm.js:1106)
    at e.value (foundation.esm.js:4704)
    at e.value (foundation.esm.js:4930)
    at HTMLDivElement.dispatch (jquery.js:5237)
    at HTMLDivElement.m.handle (jquery.js:5044)
    at Object.trigger (jquery.js:8471)
    at C.fn.init.triggerHandler (jquery.js:8555)
    at MutationObserver.n (foundation.esm.js:1940)
E @ foundation.esm.js:1058
GetExplicitOffsets @ foundation.esm.js:1106
value @ foundation.esm.js:4704
value @ foundation.esm.js:4930
dispatch @ jquery.js:5237
m.handle @ jquery.js:5044
trigger @ jquery.js:8471
triggerHandler @ jquery.js:8555
n @ foundation.esm.js:1940
attributes (async)
attr @ jquery.js:7784
U @ jquery.js:3976
attr @ jquery.js:7741
resizeListener @ foundation.esm.js:1846
(anonymous) @ foundation.esm.js:1902
setTimeout (async)
(anonymous) @ foundation.esm.js:1901
dispatch @ jquery.js:5237
m.handle @ jquery.js:5044

**Comment by DanielRuf** [comment] 2020-02-06 15:29
Hi @radiantone,

creating a reproducible testcase ourself and trying to get all the required details is often very time consuming.

Please open a new issue and use the issue template so we can resolve this.
Thank you very much.

**Comment by DanielRuf** [comment] 2020-02-06 15:30
> $(document).foundation();

This is not a reproducible testcase and lacks much information (like the used Foundation Sites version) ;-)
