### ISSUE TITLE
[Drilldown Menu] Drilldown width not recalculated on screen resize

### ISSUE THREAD

**Issue by shaunmorrison** [zurb/foundation-sites#7948] opened 2016-01-20 19:50 UTC
Having trouble getting the Drilldown width to recalc on screen resize. If making screen smaller the Drilldown menu will potentially be too wide for screen (causing usability issues). My menu is set to width:100%.

Thanks.

**Comment by Silvester20** [comment] 2016-01-20 23:39
Already reported at https://github.com/zurb/foundation-sites/issues/7774

**Comment by gakimball** [comment] 2016-02-01 22:02
Yep, duplicate of #7774

**Closed by gakimball** 2016-02-01 22:02 UTC
Labels: bug, javascript
