### ISSUE TITLE
[Responsive Navigation] Vertical menu bug in safari when resizing

### ISSUE THREAD

**Issue by kaladivo** [zurb/foundation-sites#7749] opened 2016-01-03 15:43 UTC
When I resize the Safari window such that all items in menu are under each other and then resize the window back two first items get stucked and won't return to horizontal position. 

After resizing:
![After resizing](https://cloud.githubusercontent.com/assets/11568934/12079416/8f5e7a02-b238-11e5-9bab-151fe74331fa.png)

You should be able to reproduce it easily by just resizing window as I described above. The bug occurs on documentation page ([here](http://foundation.zurb.com/sites/docs/responsive-navigation.html))

My Safari version: 9.0.1.

**Comment by rafibomb** [comment] 2016-01-05 01:10
Confirmed in Safari 8 too. It's because it still has the display: table-cell; when sized back to large.

**Comment by rafibomb** [comment] 2016-02-15 23:35
Not sure what the fix is short of a float based menu. Anyone deal with this table based menu issue before?

**Comment by rafibomb** [comment] 2016-02-15 23:38
Closing in favor of https://github.com/zurb/foundation-sites/issues/7235 . We're trying some different things and still looking for suggestions.

**Closed by rafibomb** 2016-02-15 23:38 UTC
Labels: bug, scss
