### ISSUE TITLE
Zurb template fails to build using Node v7.0.0

### ISSUE THREAD

**Issue by kobrix** [zurb/foundation-sites#9303] opened 2016-10-27 12:14 UTC
**How can we reproduce this bug?**

1. Step one

    impetuously upgrade Node to v7.0.0, like a fool

2. Step two

    ```
    npm start
    ```

3. Step three

    watch it fail

**What did you expect to happen?**
success, riches, fame

**What happened instead?**
angst as my deadline approaches

I tried updating npm, updating packages, but eventually downgraded Node:

```
brew uninstall node
Uninstalling /usr/local/Cellar/node/7.0.0... (3,861 files, 44.3M)
node 6.8.1 is still installed.
Remove all versions with `brew uninstall --force node`.
brew link node
Linking /usr/local/Cellar/node/6.8.1... 7 symlinks created
```
... and relax, build system working again.

It looks like it choked on gulp-sass:

```
npm start

> foundation-zurb-template@1.0.0 start /Library/WebServer/Documents/MySite
> gulp

[13:03:26] Requiring external module babel-register
[13:04:49] Using gulpfile /Library/WebServer/Documents/MySite/gulpfile.babel.js
[13:04:49] Starting 'default'...
[13:04:49] Starting 'build'...
[13:04:49] Starting 'clean'...
[13:04:50] Finished 'clean' after 475 ms
[13:04:50] Starting 'pages'...
[13:04:50] Starting 'sass'...
[13:04:50] Starting 'javascript'...
[13:04:50] Starting 'images'...
[13:04:50] Starting 'copy'...
[13:04:54] 'sass' errored after 4.1 s
[13:04:54] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.0
    at Object.<anonymous> (/Library/WebServer/Documents/MySite/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:13:11)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Library/WebServer/Documents/MySite/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Library/WebServer/Documents/MySite/node_modules/gulp-sass/index.js:187:21)
[13:04:54] 'build' errored after 4.58 s
[13:04:54] 'default' errored after 4.59 s
[13:04:54] The following tasks did not complete: pages, javascript, images, copy
[13:04:54] Did you forget to signal async completion?
```

**npm-debug.log:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundation-zurb-template@1.0.0~prestart: foundation-zurb-template@1.0.0
6 silly lifecycle foundation-zurb-template@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle foundation-zurb-template@1.0.0~start: foundation-zurb-template@1.0.0
8 verbose lifecycle foundation-zurb-template@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle foundation-zurb-template@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Library/WebServer/Documents/MySite/node_modules/.bin:/usr/local/Cellar/node/7.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
10 verbose lifecycle foundation-zurb-template@1.0.0~start: CWD: /Library/WebServer/Documents/MySite
11 silly lifecycle foundation-zurb-template@1.0.0~start: Args: [ '-c', 'gulp' ]
12 silly lifecycle foundation-zurb-template@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle foundation-zurb-template@1.0.0~start: Failed to exec start script
14 verbose stack Error: foundation-zurb-template@1.0.0 start: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid foundation-zurb-template@1.0.0
16 verbose cwd /Library/WebServer/Documents/MySite
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error foundation-zurb-template@1.0.0 start: `gulp`
22 error Exit status 1
23 error Failed at the foundation-zurb-template@1.0.0 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the foundation-zurb-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs foundation-zurb-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls foundation-zurb-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by DaSchTour** [comment] 2016-10-27 13:22
Duplicate of https://github.com/sass/node-sass/issues/1766

**Comment by kobrix** [comment] 2016-10-27 15:28
Cheers.

**Comment by colin-marshall** [comment] 2016-10-27 17:29
@kobrix be careful about using the latest version of Node when developing. I find things more stable when I keep a few versions back from the latest. Also, I highly recommend using [nvm](https://github.com/creationix/nvm) to switch between different versions of Node without having to uninstall/reinstall every time you switch.

I'm closing this issue for now as @DaSchTour seems to have resolved it. Feel free to reopen if you still have problems once Node Sass is supported in Node v7.0.0.

**Closed by colin-marshall** 2016-10-27 17:29 UTC

**Comment by kobrix** [comment] 2016-10-27 17:41
@colin-marshall yes, it wasn’t exactly on purpose that I upgraded Node and downgrading was easy but I thought it was worth posting anyway in case it helped anyone else who might hit the issue. And yes, nvm is a good thing.

**Comment by colin-marshall** [comment] 2016-10-27 17:45
Thanks! Figured you were probably aware of it but it's so useful that it's always worth mentioning.
