### ISSUE TITLE
Problem with the height of off-canvas component

### ISSUE THREAD

**Issue by luisarriojas** [zurb/foundation-sites#9292] opened 2016-10-25 14:14 UTC
There are two problems with off-canvas component.
## 1) Height of .off-canvas-content

The following code solves the problem with the height. You can use this fix with .off-canvas-content or with .off-canvas-wrapper-inner, but in both cases an additional height is added to the bottom of the document.

```
.off-canvas-content{
  height:100vh;
}
```
## 2) The height of .off-canvas

.off-canvas adjusts its height to its content and not to the height of the screen. So, one possible fix could be the following, but this adds an additional height to the bottom of the off-canvas component.

```
#offCanvasLeft{
    height:100vh;
    background-image: url(http://wallpapercave.com/wp/CpRGNUC.jpg);
    background-repeat: no-repeat;
    background-size: cover;
};

```

You can check it on [CodePen](http://codepen.io/anon/pen/XjGkvj?editors=1100)

**Comment by Silvester20** [comment] 2016-10-26 13:44
> .off-canvas adjusts its height to its content and not to the height of the screen. 

This is the right and intended behaviour in my opinion. In my website I don't want the height to be the height of the whole website. If you code your website in the right way it should fit/solve your case without modifying the default Foundation core.

**Comment by paxperscientiam** [comment] 2016-10-26 22:34
@luisarriojas 

The problem with using `.off-canvas-content{height:100vh;}`  is that it will defeat the purpose of flexbox. Of course, that is assuming you're using the flexbox version.

Assuming I understand your problem, I recommend making the background color of ".off-canvas-wrapper" the same as that of ".off-canvas".

**Comment by Lindsor** [comment] 2016-11-12 22:23
@luisarriojas setting height to 100vh has a bug on android devices running chrome. The value of 100vh is different when scrolling up vs scrolling down because of the chrome menu drawer showing up. This makes the page "jump" and is super annoying.

**Comment by paxperscientiam** [comment] 2016-11-16 19:14
@Lindsor Just curious, are you referring to `html,body{height:100vh}`?

**Comment by Lindsor** [comment] 2016-11-17 01:46
@paxperscientiam Yes. So android chrome factors in the url bar into the vh units. So

assume:

`screen size = 1000px`
`url bar = 100px`

When scrolling down the page the url bar disapears so the the value of `100vh` is:
`100vh = screen size = 1000px`

When scrolling up the page the url bar shows up so the value of `100vh` is:
`100vh = screen size + url bar = 1100px`

The switch from scrolling up / down and vice versa causes the browser to recalculate `100vh` and repaint the browser, and this causes the page to 'jump'.

The example on codepen doesnt work because they use iframes, but copy the `html/css` to a localhost version and open up chrome for android and you'll see the jump.

http://codepen.io/Lindsor/pen/jVMjdd/?editors=1100

**Comment by brettsmason** [comment] 2016-12-01 20:31
Off canvas has been completely reworked for 6.3 and this issue should now be solved.
Release candidate is out today, witht he full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.

**Closed by brettsmason** 2016-12-01 20:31 UTC
Labels: off-canvas
