### ISSUE TITLE
Version 6.4.4-rc1 XY grid is broken

### ISSUE THREAD

**Issue by jimsheen** [zurb/foundation-sites#10757] opened 2017-10-30 10:43 UTC
After upgrading to 6.4.4-rc1 from 6.4.0 the example vertical scrolling XY grid found at this link no longer works:

https://codepen.io/ZURBFoundation/pen/MogrXG

Vertical scrollbars are missing from the "Independent scrolling sidebar" and "body"

**Comment by colin-marshall** [comment] 2018-03-07 21:03
This appears to have been introduced in #10649 with https://github.com/zurb/foundation-sites/pull/10649/commits/b1924e099540e4e7411a948d776691e1e5746fbf. That fix was introduced for when the cell-block doesn't overflow the height of the container so the cell-block takes up the empty space. The problem is that when the cell-block _does_ overflow the height of the container, `height: 100%` disables vertical scrolling.

**Comment by colin-marshall** [comment] 2018-03-07 21:08
This actually looks to be resolved with #10704.

**Comment by colin-marshall** [comment] 2018-03-24 22:06
Resolved in #11085.

**Closed by colin-marshall** 2018-03-24 22:06 UTC
Labels: PR open, XY Grid, bug
