### ISSUE TITLE
Odd Behavior with IE 11 and Off Canvas

### ISSUE THREAD

**Issue by LDigital84** [zurb/foundation-sites#8561] opened 2016-04-08 21:25 UTC
I just upgraded to 6.2.1 and I'm noticing an odd behavior in IE 11.

Here is the site in question: http://www.kerryblues.info/

When you go to the site, you'll see a  "Menu" tab on the left. This pulls out an off canvas menu. When you click that, the off canvas menu slides open and pushes the content to the right. This is how it should work, however, in IE 11 it pushes everything but the Menu tab to the left. I cannot figure out why. It was working fine in 6.2. All other browsers, including Edge, do not have this issue.

The menu tab is using fixed positioning but again, I don't have this issue on other browsers as everything is pushed to the left. 

I cannot find the problem and I do not know if this is a Foundation problem or a problem with some of my code. I am using the flex version of Foundation.

Any direction or thoughts are welcome.

**Comment by colin-marshall** [comment] 2016-04-17 02:14
Can anybody that has IE11 look into this, please? I will get IE VM's setup next week for testing.

**Comment by mwellner** [comment] 2016-05-09 11:59
Tested on IE 11.0.9600 (Windows 7), could not confirm the behavior. Works as expected.

**Comment by LukePettway** [comment] 2016-05-09 13:55
I'm seeing that issue using IE11 on Browserstack. The menu button is used in fixed position which is based off the viewport, so I think it has to do with IE being strict about that positioning. I think Chrome has a few ways to work around that, which is why it works in it. Is it possible to do position absolute?

**Comment by Lynda333** [comment] 2016-05-15 05:06
@LukePettway - Cannot use absolute positioning with the way the site is setup. This did work pre-6.2.1.

**Comment by Geczy** [comment] 2016-07-20 17:59
Having a similar issue in IE11! Cannot reproduce on Foundation demo site. I'm on 6.2.3

IE11 

![](http://i.imgur.com/3mjS81T.png)

Chrome

![](http://i.imgur.com/lZPEM4g.png)

**Comment by andycochran** [comment] 2016-07-25 19:01
Can this be reproduced in a [CodePen](http://codepen.io/pen?template=NNyXxB)?

**Comment by Geczy** [comment] 2016-07-25 19:36
Thanks @andycochran , I wasn't able to reproduce it so I looked into my own CSS files that are being loaded and found the culprit. I had some CSS targeting off-canvas that was conflicting it (the css was setting it to position: fixed. Removing that fixes my issues)

False alarm. Carry on.

**Comment by andycochran** [comment] 2016-07-25 20:02
Glad to hear you were able to fix your app, @Geczy. A little [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging) often solves the bugs I create. 😃 

@LDigital84 I'm going to close this. But if you're still having trouble, please reopen and provide a Codepen if you can.

**Closed by andycochran** 2016-07-25 20:02 UTC
Labels: bug, feedback wanted, help wanted
