### ISSUE TITLE
Setup CLI does not work properly with 6.2.0, Babel error

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8261] opened 2016-02-27 18:51 UTC
I just did this: 

- foundation update (nothing to update) 
- foundation new (sites with zurb handlebar template) 
- cd in folder and foundation watch 

and i am getting this error: 

![test62](https://cloud.githubusercontent.com/assets/3061129/13374659/8477a072-dd8b-11e5-95b3-138e07f89e56.JPG)

**Comment by Diablo-D3** [comment] 2016-02-27 20:14
This might be a dupe of #8256, I'm having the same problems.

**Comment by colin-marshall** [comment] 2016-02-28 09:30
Try running `npm install` inside the root directory of the project.

**Comment by phifa** [comment] 2016-02-28 11:04
I tried it and this is what I get. I am on Windows and using PowerShell as admin. 
![screen](https://cloud.githubusercontent.com/assets/3061129/13378831/71392ef8-de13-11e5-8919-85a54aaa7c0f.JPG)

**Comment by colin-marshall** [comment] 2016-02-28 18:29
@phifa: http://stackoverflow.com/questions/30860795/fail-to-install-npm-package-npm-err-errno-4048

**Comment by gakimball** [comment] 2016-03-02 02:01
Going to roll into #8256 to keep all of the Babel discussion in one place.

**Closed by gakimball** 2016-03-02 02:01 UTC
