### ISSUE TITLE
Opened Off-Canvas with visible double scrollbars on Windows

### ISSUE THREAD

**Issue by fanfarian** [zurb/foundation-sites#9742] opened 2017-02-02 12:25 UTC
In Foundation 6.3.0 an opened Off-Canvas element has double scrollbars when there is long content in both elements.

#### How to reproduce this bug:
1. Standard Off-Canvas setup
2. Long content in both elements (Page content & Off-Canvas content)
3. Double scrollbars side by side on the right side of all Windows 10 Browsers (Latest Chrome & Firefox, IE 11 & Edge).

#### What should happen:
Only one scrollbar for active Off-Canvas content should be visible.

#### What happened instead:
Two scrollbars on the right side.
Outer scrollbar for Page content
Inner scrollbar for Off-Canvas content

#### Test case:
http://codepen.io/fanfarian/pen/zNWabg

#### 
This might be intentional from the Browser/OS view, but looks like an error from the user/customer side. On macOS: Both scrollbars are only visible while scrolling and are above each other so it's not a problem there.

The second scrollbar for page content is hidden when I use `data-content-scroll="false"`.
But then there is the Issue #9696 (Off-Canvas v6.3 does not scroll on mobile)

A solution might be to hide the scrollbars with css, but keep the scrolling functionality e. g. `::-webkit-scrollbar { display: none; }` or a jQuery thing.

**Comment by kball** [comment] 2017-02-02 17:08
tag @brettsmason

**Comment by brettsmason** [comment] 2017-02-03 15:22
@kball if #9707 can get finished and merged I personally think that should solve this issue.
If you want the content to be scrollable, then in my opinion a scroll bar should be visible, I don't think we should be trying to hide it.

**Comment by brettsmason** [comment] 2017-02-13 08:02
I'm going to close this now that #9707 has been merged which solves the use of `data-content-scroll="false"` on mobile devices. That feature was intended to solve just this problem, and I dont personally think its Foundations place to decide if the user wants the other scrollbar or not if content is allowed to scroll.

Any other issues though please re-open this! 👍

**Closed by brettsmason** 2017-02-13 08:02 UTC
Labels: bug, off-canvas
