### ISSUE TITLE
Orbit Slider: First bullet jumps 8px to the top

### ISSUE THREAD

**Issue by marvinbernd** [zurb/foundation-sites#11328] opened 2018-06-06 17:19 UTC
## What should happen?
The bullets in the orbit slider should stay all on the same height.

## What happens instead?
The first bullet in the orbit slider jumps 8px to the top after the slide changed. It only happens in Safari on macOS. I only testet it in Safari 11.1 on macOS 10.13.4

## Test Case and/or Steps to Reproduce

Test Case: https://www.oeriginal.ch/

How to reproduce:
1.
2.
3.

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Safari 11.1
- Operating System and version (desktop or mobile): macOS 10.13.4

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by marvinbernd** [comment] 2018-06-07 09:42
I found the problem: Between <button></button> i added <span class="show-for-sr"> slide details.</span> to every bullet. The problem is not that the first buttom jumps to the top. Because oft the <span>. Every bullet jumps 8px to the bottom. When you change the slide for some reason the <span> in the first bullet will be removed. And it jumps to the correct position. The other bullets stay at the bottom. If you remove all <span class="show-for-sr"> in the bullets it works.

I don't find the reason why the bullets jumps to the bottom (but I think it is a CSS problem with Safari >=11.1) and I don't know why the span in the first bullet will be removed.

**Comment by DanielRuf** [comment] 2018-06-07 19:20
So far I can not reproduce it on Browserstack.

**Comment by macgraphic** [comment] 2018-07-17 09:51
Still happening in 6.5.0-rc.2, on Mac OSX 10.13.6, with Safari 11.1.2

**Comment by DanielRuf** [comment] 2018-07-17 10:58
> Still happening in 6.5.0-rc.2, on Mac OSX 10.13.6, with Safari 11.1.2

Please provide a codepen where we can clearly see this and additional information about the environment.

**Comment by ncoden** [comment] 2018-08-03 21:22
@macgraphic I think I found where the problem comes from.

Take a look at the template we provide for bullets in the [Orbit Documentation](https://foundation.zurb.com/sites/docs/orbit.html#bullets):
```html
```html
<nav class="orbit-bullets">
  <button class="is-active" data-slide="0">
    <span class="show-for-sr">First slide details.</span>
    <span class="show-for-sr">Current Slide</span>
  </button>
  <button data-slide="1">
    <span class="show-for-sr">Second slide details.</span>
  </button>
  <button data-slide="2">
    <span class="show-for-sr">Third slide details.</span>
  </button>
  <button data-slide="3">
    <span class="show-for-sr">Fourth slide details.</span>
  </button>
</nav>
```

Orbit will automatically detach the last `span` inside the button of the current slide and move it to the next. If you forgot `<span class="show-for-sr">Current Slide</span>`, this will work incorrectly as the "last span".

For now, make sure you have two `span` in the active bullet button: one to describe the slide and one to indicate the active status.

I'll see if we can change this to a less opinionated and more customizable approach. For the "8px jump", I am not able to reproduce it (it seems you updated your website). Could you provide a Codepen so we can reproduce the issue ?

**Comment by ncoden** [comment] 2018-08-04 22:07
I opened a PR related to the issue of the disappearing `span` elements. See https://github.com/zurb/foundation-sites/pull/11434.

For the "8px jump", I were not able to reproduce it and I am waiting for a reply of @macgraphic or @marvinbernd.

**Comment by macgraphic** [comment] 2018-08-16 13:05
Hi @ncoden & @marvinbernd.
Hopefully you can both see the following Codepen OK.
During more local testing, I found this Safari issue only occurred when there was more than one Orbit set up on the same page. 
And whats-more  problematic, is it's not every time it shows the problem.
Have a try on the following, using Safari - the issue is with the second slider (one with images).
https://codepen.io/MacGraphic/pen/ajgZPE

**Comment by ncoden** [comment] 2018-08-16 21:05
@macgraphic Thank you, I'll take a look.

**Comment by ncoden** [comment] 2018-08-16 21:14
@macgraphic I am not able to reproduce it. Even after may tries, bullets always render correctly, without jump.

macOS 10.13.6 Safari 11.0.2 (13605.3.8)

<img width="928" alt="screen shot 2018-08-16 at 23 09 32" src="https://user-images.githubusercontent.com/9939075/44235460-ea76cf80-a1a9-11e8-8c82-beb293a4ff63.png">

**Comment by macgraphic** [comment] 2018-08-17 15:51
I think I may have found the culprit...
On the [codepen](https://codepen.io/MacGraphic/pen/ajgZPE) I have commented out the last bullet. When this is commented out, and the number of bullets do not match the number of slides, the issue shows.
One too many bullets, has no effect. But one too few, shows the issue in Safari.
It also only happens on the second or third cycle through the orbit slides.

Unless @marvinbernd has anything else to add, or any other issue can be found, I would close this issue, and mark as resolved.

**Comment by ncoden** [comment] 2018-08-17 20:06
Thank you @macgraphic for your investigation. I'm closing the issue.

**Closed by ncoden** 2018-08-17 20:06 UTC
Labels: PR open, awaiting reply, 🐛browser bug
