### ISSUE TITLE
Orbit "White Flash" Visual Bug in Firefox 58

### ISSUE THREAD

**Issue by bitbruder** [zurb/foundation-sites#10924] opened 2018-02-07 07:39 UTC
#### How to reproduce this bug:

1. Open the Orbit Docs in Firefox 58
2. Scroll to the example
3. Click the Arrows, see the "white flash"

#### What should happen:

There should be a seamless animation between the images. 

#### What happened instead:

There is a white flicker / flash between the animations. Its also happening with the HTML Content Examples. Its not a Image only problem.

#### Browser(s) and Device(s) tested on:

Firefox 58, Windows and Mac.

#### Foundation Version(s) you are using:

6.4.

#### Test case link:

https://foundation.zurb.com/sites/docs/orbit.html

#### Additional Information

- Firefox started breaking the Orbit Animation, when they released Version 58
- It was working fine in Firefox Version 57
- Someone already made a Video about the Bug https://www.youtube.com/watch?v=p-xjjJAWEXw
- I noticed, that when you click to the "left" direction, the Contents get properly displayed
- It seems that fading with motionUI works just as expected, but sliding to the left causes problems
- When you check out the demo pen (https://codepen.io/IamManchanda/pen/GmGzWY?editors=1100) it seems to work, but when you start to play around with the bullet points, its also happening

**Comment by gaialabs** [comment] 2018-02-09 13:11
Discovered that bug too. Published a post in the Foundation forum, no answer. But the video I made is here :-) It fails since version 58.0b3 of Firefox. The bug is still there with version 59b3, but a bit "less" visible.

**Comment by DanielRuf** [comment] 2018-02-10 09:50
Summoning @hiikezoe

**Comment by DanielRuf** [comment] 2018-02-10 09:57
cross referencencing https://bugzilla.mozilla.org/show_bug.cgi?id=1437272

**Comment by DanielRuf** [comment] 2018-02-10 10:00
For other testers, try mozregression https://github.com/mozilla/mozregression/releases

**Comment by DanielRuf** [comment] 2018-02-11 00:01
Can anyone confirm that this still happens in Firefox 59 and 60? https://bugzilla.mozilla.org/show_bug.cgi?id=1425213#c26

**Comment by ncoden** [comment] 2018-02-11 01:33
This is still present in Firefox Nightly 60.0a1 (2018-02-09)

**Comment by ncoden** [comment] 2018-02-11 01:52
> I can reproduce the all of the following issues under Firefox 60.0a1 (BuildId:20180210220139) on macOS 10.13.4.
> - http://jsfiddle.net/mediaxtend/t4svvhsz/embedded/result,html,css,js/
> - https://foundation.zurb.com/sites/docs/orbit.html
> - http://getbootstrap.com/docs/3.3/javascript/#carousel
>
> See: http://www.giphy.com/gifs/3o7WIDHwT2eOxa0RG0

**Comment by DanielRuf** [comment] 2018-02-11 10:49
New binaries at https://bugzilla.mozilla.org/show_bug.cgi?id=1437272#c8

At least transitions are often used and the behavior before Firefox 58 was totally ok.

Not sure why the change was done.

**Comment by DanielRuf** [comment] 2018-02-13 06:55
https://bugzilla.mozilla.org/show_bug.cgi?id=1437272#c8 seems to be fine.

**Comment by ncoden** [comment] 2018-03-30 20:34
Cannot be reproduced it anymore with Firefix 60. I guess this was a browser bug with animations and that we couldn't resove it. Closing.

**Closed by ncoden** 2018-03-30 20:34 UTC
Labels: Orbit, bug

**Comment by DanielRuf** [comment] 2018-03-30 20:39
It was/will be resolved in Firefox 60, see https://bugzilla.mozilla.org/show_bug.cgi?id=1437272#c38 ;-)

**Comment by DanielRuf** [comment] 2018-03-30 20:40
And yes it was a browser bug / regression on their side.
