### ISSUE TITLE
Multiple clicks on tooltip cause funky behavior.

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#8697] opened 2016-04-28 23:13 UTC
**How can we reproduce this bug?**

1. Go to tooltip page in docs
2. Click on tooltip once.  Tooltip will open.
3. Click on same tooltip again without clicking anywhere else.  Tooltip will close.
4. Click on same tooltip again without clicking anywhere else.  Tooltip will not open. 

**What did you expect to happen?**
3rd click should reopen tooltip

**What happened instead?**
Tooltip stayed closed

**Test case:**

- [Docs tooltip page](http://foundation.zurb.com/sites/docs//tooltip.html)

**Comment by nachtwandler** [comment] 2016-04-29 10:49
Hi,
in the foundation.tooltip.js is an if like this (line 267):
`if ((_this.options.disableHover || !_this.$element.attr('tabindex')) && !_this.isActive) {
     _this.show();
}`

I'm not shure, why theres a check for hover and tabindex inside the 'mousedown.zf.tooltip' event ?!
If disableHover is false, the tooltip will never show up on click.

**Comment by coreysyms** [comment] 2016-04-29 18:28
Im not sure the intended behavior is correct anyhow. The click should not close the tooltip if "hover" is the intended action, especially if the click is on the target tooltip span. If you hover and click the tip should stay open until you click the outside body, why should we expect to click click click, open and close, it's "hover" to activate, "click" to extend.

**Comment by nachtwandler** [comment] 2016-04-29 18:37
I don't know, which behavior is the right here. I would say "hover" is only an addition to the "click" open and close. There isn't more content to show and if the click does nothing, it "feels" broken.

**Comment by coreysyms** [comment] 2016-04-29 18:39
Right, I'm saying we fix it to be open on hover, stay open on click, if you click the body (outside the span) it closes, if you click the span again the tip should just stay open, not close like it does now.

**Comment by nachtwandler** [comment] 2016-04-29 18:42
Ok, got it. That sounds reasonable.

**Comment by coreysyms** [comment] 2016-04-29 18:47
@zurb/yetinauts thoughts? Marking as feedback wanted

**Comment by Owlbertz** [comment] 2016-04-29 18:50
Agree with you, that should be the desired behavior.

**Comment by colin-marshall** [comment] 2016-04-29 19:03
@coreysyms I agree with you, and fwiw, that appears to be the default behavior used in Bootstrap.

**Comment by coreysyms** [comment] 2016-05-03 14:43
Ill take this and submit a PR

**Comment by coreysyms** [comment] 2016-05-03 17:10
Closing this in reference to PR https://github.com/zurb/foundation-sites/pull/8730 which should now correct the issue.

**Closed by coreysyms** 2016-05-03 17:10 UTC
Labels: bug, feedback wanted, javascript
