### ISSUE TITLE
[Installation] NORMALIZE-SCSS AND SASSY-LISTS ARE NOT INCLUDED

### ISSUE THREAD

**Issue by IvanCookies** [zurb/foundation-sites#10074] opened 2017-05-24 16:45 UTC
#### How to reproduce this bug:

1. Create or open .NET asp project
2. Add Foundation 6.3.1 via Nuget
3. Compile foundation.scss and you will see the mentioned error.

#### What should happen:
Compile foundation.scss correctly

#### What happened instead:
Error: File to import not found or unreadable: ../_vendor/normalize-scss/sass/normalize.
       Load path: C:/PROJECTS/website/lib/foundation-sites.6.3.1/scss
        on line 9 of C:/PROJECTS/website/lib/foundation-sites.6.3.1/scss/foundation.scss
        from line 2 of C:\PROJECTS\website\lib\foundation-sites.6.3.1\scss\custom-foundation.scss

#### Browser(s) and Device(s) tested on:
Visual Studio 2010, IE11

**Comment by IamManchanda** [comment] 2017-06-03 18:48
cc @kball

**Comment by DanielRuf** [comment] 2018-03-05 06:30
Duplicate of https://github.com/zurb/foundation-sites/issues/9790

**Closed by DanielRuf** 2018-03-05 06:30 UTC
Labels: build
