### ISSUE TITLE
[Reveal] new instance of Foundation.Reveal (docs)

### ISSUE THREAD

**Issue by sebastiansulinski** [zurb/foundation-sites#10278] opened 2017-06-28 11:01 UTC
I think you might have a typo in your docs referring to `Reveal` [http://foundation.zurb.com/sites/docs/reveal.html#js-class](http://foundation.zurb.com/sites/docs/reveal.html#js-class)
- it says that in order to instantiate it you need to use:

```javascript
Foundation._setup
```
which I believe should be

```javascript
Foundation.Reveal
```
(but I might be wrong?)

**Comment by sebastiansulinski** [comment] 2017-06-28 11:03
Hmm - seems like you're using it for all components - didn't seem to work for me until I changed to the actual class name?

**Comment by IamManchanda** [comment] 2017-06-28 17:34
Yeah if remember it correctly, it was `Foundation.Reveal` , `Foundation.Accordion` etc only before

Poke @kball - Was it changed ??

**Comment by kball** [comment] 2017-06-28 17:48
Bother, this is a docs and autogenerated JS docs issue. _setup should be internal, the correct way to instantiate is `new Reveal($element,  options)` (or if using global namespace, `new Foundation.Reveal($element, options)`)

I'll fix this later today.

**Comment by kball** [comment] 2017-06-28 22:55
This turns out to be tricker than I thought it would be... there's a lot of jsdoc magic going on here, and it's not properly handling the class inheritance added in 6.4.0. I can brute force it, (did a couple like this in this branch: https://github.com/zurb/foundation-sites/compare/master...fix-autodoc-for-js?expand=1) but I think the real answer is to dig into how jsdoc handles ES2015 classes and teach the docs generator (and really underlying that supercollider https://github.com/zurb/supercollider) how to handle them.

@gakimball do you have any thoughts on the quickest way to do this?

**Comment by gakimball** [comment] 2017-06-30 17:46
@kball The issue is that the `_setup` method in every plugin is being annotated as if it's a class. So the "class name" it extracts is `_setup`, instead of `Abide`.

```js
class Abide extends Plugin {
  /**
   * Creates a new instance of Abide.
   * @class
   * @fires Abide#init
   * @param {Object} element - jQuery object to add the trigger to.
   * @param {Object} options - Overrides to the default plugin settings.
   */
  _setup(element, options = {}) {
    this.$element = element;
    this.options  = $.extend({}, Abide.defaults, this.$element.data(), options);

    this._init();
  }

  // ...
}
```

Now that every plugin inherits a base class, I assume they're all guaranteed to have the same constructor signature of `element`, `options`. My suggestion would be to edit the page template in `foundation-docs` and just hardcode that section explaining how the constructor works. The table of params is the same for every plugin; the only thing that's different is the name `new Foundation.<Plugin>(element, options);`, so that would be the only dynamic element.

You might need to rework the JSDoc for each plugin so that the class itself is annotated instead of the `_setup` method. Then you can use the `name` property of that class doclet to write out the sample code correctly.

**Comment by kball** [comment] 2017-06-30 19:09
Thanks for the quickfix @gakimball - agree we should rework this, we need to deal with events fired from core plugin class as well, but having a quick workaround to unbreak this base use is very helpful

**Comment by DanielRuf** [comment] 2018-02-20 21:55
What is the current state?

**Comment by DanielRuf** [comment] 2018-02-23 05:52
At least the PR was already merged.

**Comment by DanielRuf** [comment] 2018-03-10 23:34
I close this as the docs are correct now.

Feel free to reopen if the issue is not solved.

**Closed by DanielRuf** 2018-03-10 23:34 UTC
Labels: docs
