### ISSUE TITLE
[Reveal] Does not work using foundation.min.js

### ISSUE THREAD

**Issue by JoshuaDeatonZPFC** [zurb/foundation-sites#7068] opened 2015-11-20 17:28 UTC
**How can we reproduce this bug?**

1. use foundation.min.js instead of foundation.js 
2. use main Reveal example

**What did you expect to happen?**
   Reveal should open a modal
**What happened instead?**
  Absolutely nothing, not even an error call

**Comment by aibrean** [comment] 2015-11-20 17:44
Duplicate of https://github.com/zurb/foundation-sites/issues/7046

**Comment by zurbchris** [comment] 2015-11-20 17:52
When did you start the project? We had an issue with mangled code on the .min version that we patched a fix for yesterday with the 6.0.1 release. From the browser console, type `Foundation.version` to see if you're up to date.

**Comment by zurbchris** [comment] 2015-11-20 18:54
If you're using a copy of Foundation from the customizer, do not use the .min file for the js. There's been an issue getting it to update to v6.0.1. If you are using bower/npm to install, you should be able to update and switch back to the .min

**Comment by JoshuaDeatonZPFC** [comment] 2015-11-20 19:17
I started the project today and downloaded it directly from the foundation website.

Sincerely,
Joshua Deaton

**Comment by zurbchris** [comment] 2015-11-20 19:19
We do apologize, there's an issue with how our node service handles versioned releases and is not yet giving updated .min files. Please use the unminified version for now.

**Comment by zurbchris** [comment] 2015-11-20 23:07
https://github.com/zurb/foundation-sites/issues/7088

**Closed by zurbchris** 2015-11-20 23:07 UTC
