### ISSUE TITLE
Possible memory leak with foundation-cli

### ISSUE THREAD

**Issue by IngoVals** [zurb/foundation-sites#9160] opened 2016-09-06 21:10 UTC
During _Foundation new_ with the node **foundation-cli** I get this error message after selecting template (either)

`(node:2208) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

This error repeats several times and it seems to stall, however the basic site template managed to complete successfully once even thought the errors were present.

I'm using 
- npm -v 3.10.3
- node -v v6.3.1
-  foundation -v Foundation CLI version 2.1.0
-  git --version git version 2.9.2.windows.1
- Windows 10

This seems like a issue with attaching too many listeners to a singular event in Node.

**Comment by alen12345** [comment] 2016-09-13 14:04
Same here, hanging at _extract:style-sherpa_

Here is what I am using:

- npm -v 3.10.7
- node -v v6.5.0
- foundation -v Foundation CLI version 2.1.0
- git --version git version 2.9.3
- Arch Linux

Using foundation-cli, I am getting _Segmentation dumped_, whereas the same error reported by @IngoVals using github clone and _npm install_.

**Comment by colin-marshall** [comment] 2018-02-03 18:29
Related issue on cli repo: https://github.com/zurb/foundation-cli/issues/41

**Comment by colin-marshall** [comment] 2018-02-03 18:43
@IngoVals @alen12345 sorry for the late response! Can you please confirm this is still an issue? Please provide your current Node version, npm version, and OS version as you previously did.

Also, if the issue is still present, please run `npm install -g npm@next` and see if that resolves the issue. Thank you!

**Comment by DanielRuf** [comment] 2018-03-04 23:23
This might be an npm / Node.js issue. I recall seeing it in the past bery often but not with the current Node.js versions.

**Comment by DanielRuf** [comment] 2018-03-10 20:51
Can this still be reproduced with the current Node.js versions or can we close this?

**Comment by DanielRuf** [comment] 2018-03-12 18:49
As there is no full stacktrace and this is probably related to an old version of npm and request (see https://github.com/npm/npm/issues/13806#issuecomment-243452027) it might make sense to close this then as no one else reported the same issue and it is not directly related to Foundation Sites.

@ncoden or what do you think? I can not reproduce it with nvm and different projects at work which use Node.js 4, 6 and 8.

**Comment by colin-marshall** [comment] 2018-03-12 18:53
@DanielRuf let's close this. There's already an open issue on the cli repo, which is the more appropriate place for it anyway. Thanks.

**Closed by colin-marshall** 2018-03-12 18:53 UTC
Labels: bug, cli
