### ISSUE TITLE
[Slider] Snaps to right

### ISSUE THREAD

**Issue by tonister** [zurb/foundation-sites#8665] opened 2016-04-25 08:05 UTC
**How can we reproduce this bug?**
1. Open the zurb foundation Slider docs http://foundation.zurb.com/sites/docs/slider.html.
2. Test on the first slider demo on the page by draggig the slider to the right edge  smoothly.
3. At the last 5-ish mm's test dragging slightly left and right and notice the slider "snaping" to the right edge.

**What did you expect to happen?**
I expected to be able to drag through every integer, not skipping any.
**What happened instead?**
The slider snapped from value 91 to 100 skipping 92..99.
**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

It can be tested on the slider doc page here http://foundation.zurb.com/sites/docs/slider.html and also on the CodePen link below:
- [CodePen with Foundation 6 testing Slider.js](http://codepen.io/tonister/pen/KzxpMe?editors=1111)

**Comment by tonister** [comment] 2016-04-25 08:34
The same behaviour can be observed on the vertical sliders bottom edge.

**Comment by tonister** [comment] 2016-04-25 10:25
An update, the slider value seems to be related to the actual width of the element, the wider it is the higher the value it snaps from is.

**Comment by Owlbertz** [comment] 2016-04-30 17:02
The issue comes from the ```halfOfHandle = this.$handle[0].getBoundingClientRect()[param] / 2,```; if you set that to `0` you can also select values like 99, which is not possible otherwise.
I understand that this part makes sense, because *theoretically* you need that to calculate the exact position, but it just works without that value. I think there is no one who just moves the slider (or clicks onto the trail) and expects that the value is correct, you will always either adjust it in small steps until it has the value you want or you will not care about the 1% inaccuracy that may occur at all...
So now I am asking, if you it would make sense to remove that variable from the calculation. 

Any thoughts from the @zurb/yetinauts?

**Comment by bousquet** [comment] 2016-05-31 06:37
Also having this issue.  Slider jumps from 9.1 to 10 on a scale of 0.0-10.0.

**Comment by designerno1** [comment] 2016-05-31 07:57
is it still present after the update to v6.2.3???

**Comment by Owlbertz** [comment] 2016-05-31 08:10
If so, we should consider what I wrote above I guess.

**Comment by bousquet** [comment] 2016-05-31 08:20
Actually, I'm using `foundation-rails` which is behind this repo by a couple releases (6.2.1 currently).  Disregard my comment above.

**Comment by kball** [comment] 2016-11-12 00:56
I'm pretty confident this was fixed in 6.2.3, and I'm currently not able to reproduce, but if not please reopen.

**Closed by kball** 2016-11-12 00:56 UTC
Labels: feedback wanted, javascript
