### ISSUE TITLE
Reveal - on open focus on first input

### ISSUE THREAD

**Issue by wgstjf** [zurb/foundation-sites#8938] opened 2016-06-16 16:35 UTC
Hi guys,

Struggling to focus on an input field inside a reveal when the reveal is opened.  Currently the focus is just being ignored, though I do get the word 'focus' logged on the console which is coming from your afterAnimationFocus() function.

Simple example as follows:

```html
<a class="button" data-open="reveal-modal">Open Reveal</a>

<div class="reveal full" id="reveal-modal" data-reveal data-animation-in="fade-in" data-animation-out="fade-out">
  <form action="" method="post" name="login-form" id="login-form">
    <div class="input-group">
      <span class="input-group-label">E</span>
      <input name="email" id="email" type="email" class="input-group-field" placeholder="Email address" required/>
    </div>
    <div class="input-group">
      <span class="input-group-label">P</span>
      <input name="pwd" id="pwd" type="password" class="input-group-field" placeholder="Password" required/>
    </div>
    <p>
      <a href="" id="login-submit" class="button expanded with-icon icon-left"><i class="fa fa-key"></i>Login</a>
    </p>
  </form>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
```
JS:
```js
$(document).ready(function() {
  $('#reveal-modal').on('open.zf.reveal', function() {
    console.log('reveal open');
    $('#reveal-modal').find("input:visible").first().focus();
  });
});
```

Using Foundation 6.2.3.  Would really appreciate any advice on this.

Cheers,

Will

**Comment by andycochran** [comment] 2016-06-30 21:54
It's the animation. Your focus is firing before the model is open, so the input isn't visible yet. If you remove the `data-animation-*` attributes, it just works. Or you could set a timeout longer than the animation duration so the focus fires once the input is actually visible. Hope that helps.

I'm gonna close this, as it's not a bug. Best place for questions like this is the [Forum](http://foundation.zurb.com/forum/).

**Closed by andycochran** 2016-06-30 21:54 UTC
