### ISSUE TITLE
Orbit Swipe does not work

### ISSUE THREAD

**Issue by motiejuss** [zurb/foundation-sites#11737] opened 2019-04-11 14:19 UTC
## What should happen?

Orbit slide swipe left/right slide should change.

## What happens instead?

Slide didn't change.

In the Orbit documentation page it says: `data-swipe` default is `true` - Allows the Orbit slides to bind to swipe events for mobile, requires an additional util library.

Is there any 3rd party util library thet is required? Because in `foundation.orbit.js` I can see the part where element subscribes to `swipeleft.zf.orbit` and `swiperight.zf.orbit`, but I can't find implementation of these. 

Swipe does not work on any of the Orbit sliders in doc page neither (https://foundation.zurb.com/sites/docs/orbit.html). 

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Use a basic example from documentation: https://foundation.zurb.com/sites/docs/orbit.html

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Google Chrome 73.0.3683.103
- Device, Operating System and version: Windows 10
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2019-04-11 14:31
Not sure if https://github.com/zurb/foundation-sites/pull/11716 is related.

**Comment by motiejuss** [comment] 2019-04-11 14:32
Seems to be related: https://github.com/zurb/foundation-sites/issues/11714

**Comment by DanielRuf** [comment] 2019-04-11 14:32
Can you check if 6.5.0, 6.5.1 and 6.5.2 also have this issue?
Closing as duplicate of #11714

**Closed by DanielRuf** 2019-04-11 14:32 UTC
Labels: Orbit, events, javascript, 🐛bug
