### ISSUE TITLE
Responsive Accordion deep linking is broken

### ISSUE THREAD

**Issue by sensaetions** [zurb/foundation-sites#11314] opened 2018-05-30 22:21 UTC
## What should happen?
I'm using the responsive accordion-tab component with deep linking, accordions on small screens and vertical tabs on large screens. Deep linking should work regardless of which mode the component is in, and after browser resize. *See steps to reproduce below for more specific details.*

## What happens instead?
After browser resize, accordions appear to be broken. Selected accordion's ID hashtag gets appended to URL, but accordions do not change to display content.

## Possible Solution

- Check deep linking functionality

## Test Case and/or Steps to Reproduce

Test Case: [Example Link](http://sandbox.collegiseducation.com/ras/sandbox/)

How to reproduce:
1. Used the following responsive accordion tab settings, with accordion as default:
```html
<ul class="accordion" id="admissions-audience" data-responsive-accordion-tabs="accordion large-tabs" data-multi-expand="true" data-allow-all-closed="true" data-deep-link="true" data-update-history="true" data-deep-link-smudge="true" data-deep-link-smudge="500">
```
2. After page loads, click on any of the accordions. The URL appends the hashtag ID of the selected accordion.
3. Enlarge width of browser. The component changes to vertical tabs (tabs on left, content on right), with the selected tab ID appended in URL.
4. Shrink width of browser. The component changes back to accordions, hashtag still appended in URL. However, accordions do not work anymore. Chrome Developer Console shows the following error message:

```javascript
Uncaught TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (app.js:9537)
    at Accordion._checkDeepLink (app.js:11670)
    at Accordion._init (app.js:11687)
    at Accordion._setup (app.js:11608)
    at Accordion.Plugin (app.js:10098)
    at new Accordion (app.js:11589)
    at ResponsiveAccordionTabs._checkMediaQueries (app.js:18711)
    at app.js:18668
    at dispatch (app.js:5026)
    at elemData.handle (app.js:4831)
```

## Context

Fixing this issue is critical as we use a significant amounts of responsive accordion-tabs on our website.

## Your Environment

- Foundation version(s) used: 6.4
- Browser(s) name and version(s): Mac Chrome 66
- Operating System and version (desktop or mobile): MacOS Sierra

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment] 2018-06-26 18:28
Can you still reproduce this with Foundation 6.5?

**Comment by ncoden** [comment] 2018-06-27 21:10
This is caused by `jQuery(window).load(...)` that was deprecated in jQuery 3.

In jQuery 3, the following function get called instead: http://api.jquery.com/load/

> Note: Prior to jQuery 3.0, the event handling suite also had a method named .load(). Older versions of jQuery determined which method to fire based on the set of arguments passed to it.

This was fixed in v6.5.0 (RC1 for now).

**Closed** 2018-06-27 21:10 UTC

**Comment by sensaetions** [comment] 2018-07-10 21:28
@rafibomb How would I go about updating my local repo to pull Foundation v6.5.0?

**Comment by DanielRuf** [comment] 2018-07-10 21:30
Did you use the `^` selector?

**Comment by DanielRuf** [comment] 2018-07-10 21:32
You may have to run `npm i foundation-sites@6.5.0-rc.2`

**Comment by sensaetions** [comment] 2018-07-11 17:07
@DanielRuf When I run the command `npm i foundation-sites@6.5.0-rc.2`, I get this error:

`foundation-sites@6.5.0-rc.2  invalid`

How to resolve?

**Comment by DanielRuf** [comment] 2018-07-11 17:16
`yarn add foundation-sites@6.5.0-rc.2` works and so should `npm i foundation-sites@6.5.0-rc.2`
