### ISSUE TITLE
Customizer downloading non-xy grid has xy index file

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#10449] opened 2017-07-21 21:54 UTC
When downloading the legacy grids via the customizer, we should include an index.html that uses the legacy grids, not the xy classes.

**Comment by ncoden** [comment] 2018-02-13 00:37
Duplicate of https://github.com/zurb/foundation-sites/issues/10934

**Closed by ncoden** 2018-02-13 00:37 UTC
Labels: customizer, duplicate
