### ISSUE TITLE
[Forms] input-group and ABIDE form-error are incompatible

### ISSUE THREAD

**Issue by ingedgarmorales** [zurb/foundation-sites#8962] opened 2016-06-23 17:43 UTC
FOUNDATION 6

```html
This doesnt work:
<form data-abide novalidate>

  <div class="input-group">
    <input class="input-group-field" type="text" name="first_name" required placeholder="your name">
    <span class="input-group-label"><i class="fa fa-user"></i></span>
  </div>
  <span class="form-error">* This field is required</span>

</form>

This works but not with input-group:
<form data-abide novalidate>

  <input class="input-group-field" type="text" name="first_name" required placeholder="your name">
  <span class="form-error">* This field is required</span>
  
</form>
```

**What did you expect to happen?**

Show error message when the field is empty.

**What happened instead?**

Abide can not display the error message because it can not find the element span class="form-error"

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

http://codepen.io/ingedgarmorales/pen/OXWLyN

**Comment by andycochran** [comment] 2016-07-02 19:24
This is a duplicate of #7802.

**Closed by andycochran** 2016-07-02 19:24 UTC
