### ISSUE TITLE
DropdownMenu click close on Mozilla

### ISSUE THREAD

**Issue by LeG3nDz** [zurb/foundation-sites#9470] opened 2016-12-08 09:41 UTC
**How can we reproduce this bug?**
When the DropdownMenu is open (on click only), i can't close this on second click with Mozilla (last version). It work on Chrome and IE (last version).

I've add ` data-disable-hover="true"` for enable click only. But don't work for close my submenu.

**Test case:**
[Codepen test case](http://codepen.io/LeG3nDz/pen/yVEgjP).

Maybe i need other data argument ?

**Comment by ncoden** [comment] 2016-12-08 10:08
Hi @LeG3nDz,

What is your Foundation version ?
I tested with chrome (v54), it don't work neither. But it is expected: if you disable the open on Hover, you have to enable the open on Click. Add `data-click-open="true"` to your dropdown ([Codepen](https://codepen.io/ncoden/pen/gLKmMg)).

The documentation is incorrect about the default value of `data-click-open`, see https://github.com/zurb/foundation-sites/issues/9464.

**Comment by LeG3nDz** [comment] 2016-12-08 10:42
Hi @ncoden 

I've test your Codepen, it don't work on my Mozilla, but work on Chrome.
I use last version off Foundation.

**Comment by ncoden** [comment] 2016-12-08 10:47
Can you give your version number of:
- Foundation (`package.json`)
- Mozilla Firefox

Thanks.

**Comment by LeG3nDz** [comment] 2016-12-08 11:00
I use :
- Foundation 6.2.4
- Mozilla Firefox 50.0.2

Example on my Mozilla, your can see the second click refresh my page :

![submenu](https://cloud.githubusercontent.com/assets/4712791/21007607/dd8748ce-bd3d-11e6-819f-1e8a6d07c55f.gif)

Thank you for your support

**Comment by ncoden** [comment] 2016-12-08 11:08
So **the click refresh your page when the dropdown is open**. I still can't reproduce 😕  (https://codepen.io/anon/pen/gLKWgj)

- What about the Copepen you given ?
- Can you provide the HTML markup of your DropdownMenu (in pastebin) ?
- Do you have a link to the current page (or to an other page) on your DropdownMenu ? If yes, you shouldn't.

**Comment by LeG3nDz** [comment] 2016-12-08 11:29
Sorry, my example is local only.

I can reproduce my problem on your code pen : the second click open my `href`
![submenu2](https://cloud.githubusercontent.com/assets/4712791/21008432/f7598e34-bd41-11e6-9ae8-56d519dd79d4.gif)

**Comment by ncoden** [comment] 2016-12-08 11:36
Ok. This should be on Firefox for Windows only. We'll wait the @brettsmason's test.

**Comment by LeG3nDz** [comment] 2016-12-08 11:40
I see same problem with Safari 10 (iPad), tested on Codepen only.

**Comment by brettsmason** [comment] 2016-12-08 13:11
@ncoden sorry playing catchup. So its this Codepen that needs testing right? https://codepen.io/anon/pen/gLKWgj

So if I understand this correctly, clicking on the Item 1 link in this Codepen when the submenu is open navigates to that link?

**Comment by ncoden** [comment] 2016-12-08 13:17
@brettsmason  This would be the bug, yes.

**Comment by brettsmason** [comment] 2016-12-08 13:22
@ncoden I tried it in Firefox for Windows (50.0.2) and can't recreate this bug.
I tried your Codepen, and also created a visual test in the RC1 version I have locally, and seems to work correctly.

**Comment by ncoden** [comment] 2016-12-08 13:26
@LeG3nDz With https://codepen.io/anon/pen/gLKWgj, do you have errors in console ?

**Comment by LeG3nDz** [comment] 2016-12-08 13:58
@ncoden No errors in the console :(. I did test my friend, no bug on his side. But, i can recreate the bug on Safari 10 iPad :/

**Comment by kball** [comment] 2016-12-08 19:26
Hmm... so this appears to be related to touch devices and the `forceFollow` option.  For reasons that I do not understand, it appears that _by default_ if when a dropdown contains a link, on touch devices the second touch will follow that link rather than closing the dropdown.

I'm not sure why this is the case; unfortunately the commit message for the commit adding it is not very communicative e89d0cb4d2461522bbcafdcf6a1524505fa5b301

The workaround is to add `data-force-follow="false"` to your dropdown menu

**Comment by LeG3nDz** [comment] 2016-12-09 07:48
Hi @kball 

Thank you, `Foundation.DropdownMenu.defaults.forceFollow = false;` work nice !

My Mozilla isn't touch devices, it's on PC. But it work, than you for your support every body :)

**Closed** 2016-12-15 23:00 UTC
Labels: dropdown menu

**Comment by akosblazsik** [comment] 2017-07-14 10:13
This is still an issue with 6.4.1 when data-disable-hover and data-click-open are combined in the data-options attribute...
https://codepen.io/akosblazsik/pen/ZyPpev/

On Firefox 54.0 running on Ubuntu 17.04 (64-bit):
- submenu remains closed, no show/hide event fired

and on Chrome Version 59.0.3071.109 running on Ubuntu 17.04 (64-bit):
- submenu opens, but remains open after the second click
