### ISSUE TITLE
grid-column-position(center) override issue?

### ISSUE THREAD

**Issue by carpusmedia** [zurb/foundation-sites#8899] opened 2016-06-05 16:18 UTC
Hello,

We are having issues with the `grid-column-position` mixin in _Foundation 6 (ZURB Template)_. We have one column that is set with

`grid-column(10)`

and we are trying to center this with

`grid-column-position(center)`

however, the column in question does not center.

When we check the source

```
element:last-child:not(:first-child) {
  float: right;
}
```

seems to override the code of grid-column-position, which seems to be

```
element {
  float: none;
  margin-left: auto;
  margin-right: auto;
  padding-left: 0.625rem;   
  padding-right: 0.625rem;
  width: 83.3333%;
}
```

Anything we are missing, or is this just a bug?

Thanks

**Comment by ar-rm** [comment] 2016-06-19 03:08
I think I'm seeing exactly the same as well.

**Comment by ar-rm** [comment] 2016-06-19 15:52
I figured it out (at least for me).

The clue was "last" and "not first" in the selector:
`element:last-child:not(:first-child)`

This was my markup:
```
<div class="container">
    <h4>Header</h4>
    <div class="centerplease">Center this</div>
</div>
```

This was my sass:
```
.container {
    @include grid-column(12);
}
h4 {
    visibility: hidden;
}
.centerplease {
    @include grid-column(10);
    @include grid-column-position(center);
}
```

The problem was the `h4` in the **markup**.
`grid-column-position(center)` will only work if it's the only element in that row. (And by "row" I don't necessarily mean `grid-row()`)

I didn't think about the `h4` being related since it was visually *hidden* in the css. But the first-child, etc. pseudo selectors only care about the *actual* markup, not the how it's styled.

IOW:
- Not a bug (unless you count my brain as a bug)
- Check your **markup** to see if there are any other elements in same containing row as the column you want to center.

I hope this helps.

**Comment by andycochran** [comment] 2016-07-01 18:01
I'll fix this so that any number of elements can be centered…

**Comment by ar-rm** [comment] 2016-07-01 18:24
@andycochran Ohhh! That would be ideal. Thanks.

**Comment by rafibomb** [comment] 2016-07-01 20:54
Closing for PR #8990

**Closed by rafibomb** 2016-07-01 20:54 UTC
