### ISSUE TITLE
meteor package path error

### ISSUE THREAD

**Issue by masterofdaemon** [zurb/foundation-sites#8418] opened 2016-03-16 18:58 UTC
Hi, i can't install meteor package https://atmospherejs.com/zurb/foundation-sites here is log:
Error: File to import not found or unreadable: {zurb:foundation-sites}/scss/util/util
so where is his path?

**Comment by gakimball** [comment] 2016-03-16 19:55
@juliancwirko Could you chime in here?

**Comment by masterofdaemon** [comment] 2016-03-16 20:02
what do you mean? here is output:
[22:59:01] Starting 'sass'...
Error in plugin 'sass'
Message:
    scss/_settings.scss
Error: File to import not found or unreadable: {zurb:foundation-sites}/scss/util/util
       Parent style sheet: /Users/serg/projs/mannersweb/public/scss/_settings.scss
        on line 42 of scss/_settings.scss
>> @import '{zurb:foundation-sites}/scss/util/util';
   ^

[22:59:01] Finished 'sass' after 341 ms

i need path @import 'to meteor package'

**Comment by juliancwirko** [comment] 2016-03-16 20:10
@masterofdaemon hi, which version of `zurb:foundation-sites` package do you use? And also which version of Meteor do you use? 

For me when I do:

```
$ meteor create zf-test-app
$ cd zf-test-app
$ meteor add zurb:foundation-sites
$ meteor
```
it works

Do you use a custom `_settings.scss` file in you projects? Could you show how you import foundation and settings in your main .scss file?

**Comment by masterofdaemon** [comment] 2016-03-16 20:17
yes i'm, and i don't know how to import this

i now that is wrong but i don't know the path : @import 'settings';
@import '{zurb:foundation-sites}/scss/foundation';
@import 'motion-ui';

**Comment by juliancwirko** [comment] 2016-03-16 20:29
Ok, I'll try to explain with the example. In your project after you add foundation package by: 

```
$ meteor add zurb:foundation-sites
```
You may want to import your custom settings from the copied `_settings.scss` file and also foundation file from the package. 

Let's assume that you have your `main.scss` file in your app in the `client/styles/main.scss` then you can get the settings file from here: https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss and copy it to the same folder in your project. So it will be `client/styles/_settings.scss`. Then in `main.scss` file you can do something like:

```
@import 'settings';
@import '{zurb:foundation-sites}/scss/foundation';
```
In this case you should edit the copied `_settings.scss` file and change `@import 'util/util'` to `@import '{zurb:foundation-sites}/scss/util/util'`.

As you can see we import the settings file from the same folder here. If you have your `_settings.scss` file in other folder you should provide a proper path to it. If you don't want to create your custom `_settings.scss` file you can remove `@import 'settings';` part from the `main.scss` file and ignore the steps related to `_settings.scss` file. It should still work.

**Comment by kball** [comment] 2016-04-28 18:43
looks like this is not a bug but rather configuration.  Closing

**Closed by kball** 2016-04-28 18:43 UTC
Labels: bug, meteor
