### ISSUE TITLE
Swipes detection does not work on v6.5.0 and v6.5.1

### ISSUE THREAD

**Issue by achouippe** [zurb/foundation-sites#11643] opened 2019-01-02 12:24 UTC
## What should happen?

I try to upgrade from foundation-sites v6.4.3 to v6.5.1.

Everything works fine, except that my listeners on `swipeleft` and `swiperight` events are not triggered anymore, even after checking that I am using [touch utilities](https://foundation.zurb.com/sites/docs/javascript-utilities.html#touch) correctly.

## What happens instead?
I understand that `foundation.util.touch.js` reacts to `touchmove` events in order to detect swipes. Then it triggers custom events.

[Previously](https://github.com/zurb/foundation-sites/blob/v6.5.0-rc.3/js/foundation.util.touch.js#L41), custom `swipe*` events were triggered by 
```javaScript
$(this).trigger('swipe', dir).trigger(`swipe${dir}`);
```
 
But since this [fix](https://github.com/zurb/foundation-sites/commit/8d0d739c3fd105558db38f5090a406b81507c7c8) in [v.6.5.0-rc-4](https://github.com/zurb/foundation-sites/blob/v6.5.0-rc.4/js/foundation.util.touch.js#L53), custom swipe events are triggered by this code :
 
```javaScript
$(this)
  .trigger($.Event('swipe', e), dir)
  .trigger($.Event(`swipe${dir}`, e));
```
 
 
[Constructor](https://github.com/jquery/jquery/blob/master/src/event.js#L515) of `jquery.Event` do something like this :

```javaScript
jQuery.Event = function( src, props ) {
 // [...]
 if ( src && src.type ) {
   // Skipped because src = 'swipe', 'swipeleft' or 'swiperight'
 } else {
    this.type = src;
 }
 if ( props ) {
  jQuery.extend( this, props );
 }
 // [...]
}
```

Here, `props` is the original `touchmove` event, which has its own `type` attribute. The bug is caused by `jQuery.extend( this, props )` that override the type of the custom event with the type of the original event.

## Possible Solution

This is not a fix, but a possible workaround is to listen to `touchmove` events, and then check extra parameters :

```javaScript
const handleSwipes = (event, swipeDirection) => {
  if (swipeDirection === 'left') {
    // swipe left
  } else if (swipeDirection === 'right') {
    // swipe right
  }
};

$('selector').on('swipe', handleSwipes); // Just here to enable swipe detection, never triggered
$('selector').on('touchmove', handleSwipes);

```

## Test Case and/or Steps to Reproduce (for bugs)

With a mobile device, or with Chrome Dev tools in mobile mode : 
- [Swipe test 6.5.0-rc.3](https://codepen.io/anon/pen/aPEByz) - OK,
- [Swipe test 6.5.1](https://codepen.io/anon/pen/GPyrGz) - KO.

6.5.0-rc.3 triggers `swipe`, `swipeleft` and `swiperight` events. v6.5.1 only triggers `touchmove` event with direction as extra parameter.

## Your Environment

- Foundation version(s) used: v6.5.1 - ES6 code built with webpack.
- Browser(s) name and version(s): Tested on Chrome 71 for desktop, and Chrome 70 for mobile, 
- Device, Operating System and version: Mac OSX / Android 8.0.0

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2019-01-02 12:44
Hi @achouippe,

did we miss something when we tested this using the testfiles?

https://github.com/zurb/foundation-sites/pull/11430#issuecomment-427610743

**Comment by gforcada** [comment] 2019-05-31 11:59
This is still happening to us on 6.5.3 :disappointed: 

has been any new work on this front since then? :thinking: I see that there are **1.2k commits** since 6.5.3 release, is there a plan to make a new release, which I guess, given the amount of commits is not going to be 6.5.4 but 6.6.0 or 7.0.0? :thinking:

**Comment by DanielRuf** [comment] 2019-05-31 12:05
> I see that there are **1.2k commits**

Not sure but there are not 1.2k commits since the release.
@ncoden has cherry-picked the needed changes for v6.5 releases and rebased them.
https://github.com/zurb/foundation-sites/compare/v6.5.3...develop-v6.5 there are currently no changes on the `develop-v6.5` branch.

**Comment by gforcada** [comment] 2019-05-31 13:07
Then github is not getting the numbers right: https://github.com/zurb/foundation-sites/releases/ :sweat_smile:

**Comment by DanielRuf** [comment] 2019-05-31 13:09
I am aware of this. This is normal because we have rebased on v6.5 and so they are different and it is compared against the current default branch which is currently `master` ;-)

**Comment by DanielRuf** [comment] 2019-05-31 13:13
You can see it on https://github.com/zurb/foundation-sites/branches/all?utf8=%E2%9C%93&query=develop, around 330 commits were rewritten by rebasing.

**Comment by DanielRuf** [comment] 2019-08-03 22:45
Duplicate of https://github.com/zurb/foundation-sites/issues/11714#issuecomment-470006387

Will be fixed by https://github.com/zurb/foundation-sites/pull/11716

**Closed by DanielRuf** 2019-08-03 22:45 UTC
Labels: javascript, javascript utilities
