### ISSUE TITLE
Minor nit with styling of selects (possibly a firefox only issue)

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#7916] opened 2016-01-19 03:04 UTC
A bit of background:
1. Only modification to Foundation is replace Arial Helvetica with Open Sans. 

*\* Issues **
1. the default padding of selects looks incorrect compared to text areas and text inputs(only tested in firefox). A modification i have found that looks correct is to change select's padding to `padding: 0.190rem;` .
   - before
     ![img](http://puu.sh/mB2hr/df6986d4da.png)
   - after
     ![img](http://puu.sh/mB2jn/a6b015bf36.png)
2. Selects allow text to run behind dropdown arrow of select box which is just _horrible_. The fix here is simple. 
   ![img](http://puu.sh/mB2uh/114931447d.png)

``` css
padding: 0.19rem 1.666rem 0.19rem 0.19rem;
text-overflow: ellipsis;
```

**Comment by andycochran** [comment] 2016-01-19 15:51
Ack! You're right; changing the fonts can cause this cropping issue. It's the padding. 

The fix for this is to not use top/bottom padding on `<select>` elements: 
```css
select {
  padding-top: 0;
  padding-bottom: 0;
}
```
The `line-height` could be set to mach `height`, but I'm not certain that's necessary.

**Comment by whatcould** [comment] 2016-01-19 18:06
I was just writing up a forum post about the left-alignment issue! Which is separate from the cropping / text-under-arrow issue.

The select box text left-alignment issue happens even on the Zurb Foundation site; in my testing, it doesn't depend at all on the font, seems contrary to @r3wt's experience (?)

Here is a direct screenshot clipped from the Foundation docs:

![select-menu-text-alignment-firefox](https://cloud.githubusercontent.com/assets/8288/12427328/90be7278-beac-11e5-9941-3c2c3fd8191b.png)

The Select elements have mis-aligned text in Firefox, and in Chrome on Windows (and slightly less mis-aligned on IE11/Win8). Graphic is Firefox 43 Mac, but it's a similar mis-alignment on FF & Chrome Windows. Chrome and Safari on Mac align the text in the Select elements the same as the input elements, with no extra padding.

If you take off the default 0.5rem padding, Chrome/Safari Mac both push the text right against the border, and these other browsers add. So it's some browser issue with the select boxes.

Interestingly, FF Mac has a double-text-indent bug on select boxes (http://stackoverflow.com/questions/28108434/firefox-select-element-doubles-text-indent-value), that doesn't seem to be what causes it but is maybe related.

Maybe this is a known issue, and maybe there's no fix since it's such a browser/OS dependent thing. I'm having a hard time un-seeing it though!

**Comment by DanielRuf** [comment] 2018-02-15 19:04
We should either remove the top and bottom paddings as the line-height is often enough or use a font-specific unit like `ex`.

https://codepen.io/DanielRuf/pen/qxVOJQ

https://developer.mozilla.org/en-US/docs/Web/CSS/length
https://msdn.microsoft.com/en-us/library/ms537660(v=vs.85).aspx

**Comment by DanielRuf** [comment] 2018-03-01 00:24
@SassNinja what is your opinion about this?

**Comment by SassNinja** [comment] 2018-03-01 20:58
@DanielRuf I would prefer removing top and bottom padding.
I haven't seen `ex` or `ch` being used often so imo it's better to stay with the 'usual units'

**Comment by DanielRuf** [comment] 2018-03-01 21:04
@SassNinja thanks for the input. You are right. Even if it is already in CSS1 spec I'm not 100% confident that `ex` / `ch` is the best solution.

Do you want to open a PR for the padding change?

@whatcould please create a separate issue for this.

@r3wt regarding the overflow: we might better discuss this in a separate issue. Do you want to create it?

**Comment by whatcould** [comment] 2018-03-01 21:09
Not sure what issue this is trying to solve — OP flagged the padding issue (vertical & horizontal cross-browser both seem to be inconsistent with padding on eg <input>) and also the text-overflow issue. I was posting further info on the padding issue (since OP only tested on FF), pointing out it displayed correctly on Mac Webkit/Blink.

**Comment by DanielRuf** [comment] 2018-03-01 21:12
@whatcould your issue is caused by something else and not related to top / bottom padding or is it?

**Comment by whatcould** [comment] 2018-03-01 21:15
It's left padding. The OP's screenshot showed it and I imagine the top/bottom padding browser differences are a similar issue to the left/right padding? I dunno, seems weird to split those two issues.

**Comment by DanielRuf** [comment] 2018-03-01 21:27
Please open a new issue for the left padding issue so we can track this better.

**Closed** 2018-08-06 20:39 UTC
Labels: PR open, forms, inputs, scss, 🐛bug
