### ISSUE TITLE
Block Grid Gutter

### ISSUE THREAD

**Issue by JU5TY** [zurb/foundation-sites#8857] opened 2016-05-26 17:32 UTC
In Foundation 6 you use the 'grid-layout' mixin for a block grid, but what controls the gutter? The child elements have no padding left or right?

This is my code:

```
.block {
  &__list {
    @include grid-layout($n:4, $selector:li);
    list-style: none;
    margin-left: 0;
  }
}

<div class="block block--front">
   <ul class="block__list">
        <li><img src="http://placehold.it/640x480"></li>
       <li><img src="http://placehold.it/640x480"></li>
       <li><img src="http://placehold.it/640x480"></li>
       <li><img src="http://placehold.it/640x480"></li>
   </ul>
</div>
```

**Comment by brettsmason** [comment] 2016-05-27 11:37
@JU5TY So the `grid-layout` mixin is a simple mixin to just output the code needed to layout the elements in that number of columns, as you said it doesn't add any padding.

To do this you would probably need to write something like:
```
.block {
  &__list {
    @include grid-row($behavior: nest);
    @include grid-layout(4, 'li');

    & li {
    	@include grid-col();
    }
  }
}
```
This is assuming you wanted to remove the left/right padding on the edge `li` elements, if not remove the `$behavior: nest` from the above code.

Does that help?

**Comment by JU5TY** [comment] 2016-05-27 12:27
Thank you for your response @brettsmason.

That makes sense, although when I used your example the blocks stacked up full width, it only worked when I defined the grid-layout after assigning the columns to the list items (see below), does that seem right?

```
  &__list {
    @include grid-row($behavior: nest);
    & li {
      @include grid-col();
    }
    @include grid-layout(4, 'li');
  }
```

**Comment by brettsmason** [comment] 2016-05-27 12:38
@JU5TY Hmm you are right actually after looking at the generated code.
The issue is `grid-col()` is outputting the widths as well as the padding, which you don't want. Ideally what you need in this situation is a `grid-col-gutter()` mixin that outputs just the gutters, but at the moment that doesn't exist (might be worth adding though).

Try something like this and let me know if this works correctly:

```
.block {
  &__list {
    @include grid-row($behavior: nest);
    @include grid-layout(4, 'li');

    & li {
    	padding: rem-calc(0 map-get($grid-column-gutter, small));

    	@include breakpoint(medium) {
    		padding: rem-calc(0 map-get($grid-column-gutter, medium));
    	}
    }
  }
}
```

This was all assuming you wanted to use the standard gutters of course :smile:

**Comment by JU5TY** [comment] 2016-05-27 13:00
It does work, but not perfectly.

My medium gutter is set to the standard 30px.

When working correctly, I get 15px left and 15px right padding on each li, and a -15px left and -15px right padding on the ul.

Your latest example adds 30px left and 30px right padding to each li, the blocks aren't inline with the rest of the grid because it doesn't have the minus padding on the ul.

I could obviously half the gutter on the li and add the minus padding to the ul, but that seems very long winded.

**Comment by brettsmason** [comment] 2016-05-27 13:32
@JU5TY Sorry my fault, I forgot to divide the gutter, it should of been:

```
.block {
  &__list {
    @include grid-row($behavior: nest);
    @include grid-layout(4, 'li');

    & li {
        padding: rem-calc(0 (map-get($grid-column-gutter, small) / 2));

        @include breakpoint(medium) {
            padding: rem-calc(0 (map-get($grid-column-gutter, medium) / 2));
        }
    }
  }
}
```

You are right though that its a bit long winded. What do you think would be the best solution? I'm thinking a new option to the `grid-layout` mixin to include required padding.

**Comment by brettsmason** [comment] 2016-05-27 14:41
@JU5TY I've worked on adding an extra option to the `grid-layout` mixin as it sounded useful to others. It works by taking either a number/pixel value, or passing in the `$grid-column-gutter` as the value. This then gives you the same padding as columns. I'll try and get a PR up later - if you are able to test it that would be great.

**Comment by JU5TY** [comment] 2016-05-27 17:27
Sounds great @brettsmason, kind of you.

**Comment by rafibomb** [comment] 2016-07-12 20:58
Closing for PR #8871

**Closed by rafibomb** 2016-07-12 20:58 UTC
Labels: PR open, scss
