### ISSUE TITLE
"Developer" Menu disappears when mouse moved to items below "Develop" separator

### ISSUE THREAD

**Issue by stelovsky** [zurb/foundation-sites#9195] opened 2016-09-20 22:00 UTC
**How can we reproduce this bug?**
Actually, it's even **How can we fix this bug?**:)
1. [http://foundation.zurb.com/sites.html](http://foundation.zurb.com/sites.html)
2. Click "Developer" menu
3. Move mouse to an item below "Develop", e.g. "HTML Templates". Note that you'll have to move onto the label. When you move to the empty black area to the right, the menu stays... Actually, it seems to be dependent on some element(s) that the menu overlaps because it's dependent on the width of the browser window:  when the width is smaller, menu items in "Showcase" menu have the same effect. Well, wait, I think that I got it: the menus overlap "Foundation for Sites 6", but
   "Get from Prototype to Production" is on top of the menus (being transparent, the bug is not quite obvious...). So when the mouse enters "Get from Prototype to Production", it leaves the menu which makes the menu hide. So to fix the bug, simply make sure that the menu is defined after the "Get from Prototype to Production" element or give the menu a better "z-index". 

**What did you expect to happen?**
Menu stays displayed

**What happened instead?**
Menu hides

**Comment by brettsmason** [comment] 2018-01-31 15:25
I'm not able to reproduce this, but as its actually related to the ZURB site rather than Foundation specifically I'm going to go ahead and close this.

**Closed by brettsmason** 2018-01-31 15:25 UTC
