### ISSUE TITLE
FLIP CARD (building blocks) Through the Looking Glass

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#10070] opened 2017-05-24 00:44 UTC
#### How to reproduce this bug:

1. Go to Foundation Building Blocks
http://foundation.zurb.com/building-blocks/containers.html

2.Go to Containers > Flip Card
3. Click SEE CODE 
4. You will notice that the card title in desktop mode doe snot beahve the same as in mobile mode.
For example: Before clicking.  ROLL TO A HOT SPOT
After clicking:  Title Remains on Card and is backwards - Alice through the looking glass syndrome.
Absolutely FABULOUS effect - but not quite there yet for desktop.

![backwards flip card desktop](https://cloud.githubusercontent.com/assets/14908417/26382095/e1a12930-3fe6-11e7-99c6-9564e0d8f395.png)

#### What should happen:
The FLIP CARD hould behave same on desktop  as in mobile device - the First Card Title should disappear on the Flip (Mouse Click) and not be backwards and overlay the flip.

#### Test case link:

Cant do that yet - but attached screen shot

- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by Deckluhm** [comment] 2017-05-24 08:08
You should open this issue in the Building Blocks repository: [zurb/building-blocks](https://github.com/zurb/building-blocks) (and close this one since this repository is for Foundation for Sites core framework only)

**Comment by IamManchanda** [comment] 2017-05-24 19:46
@blynnc sorry can't reproduce .... can you tell which browser you are using??

PS: Also if you can move this thread to building blocks repo then that will be great!

**Comment by blynnc** [comment] 2017-05-24 21:17
Browser used Firefox 53.0.3 - latest version for Mac OSX.

I'm not sure how to move thread to building blocks repo. Please explain how. i am going through the building blocks and have found a few more issues.

**Comment by blynnc** [comment] 2017-05-24 21:22
Ok. i figured out how to add it to Building Blocks repo.

**Comment by IamManchanda** [comment] 2017-05-24 21:23
Great closing this!

**Closed by IamManchanda** 2017-05-24 21:23 UTC

**Comment by IamManchanda** [comment] 2017-05-24 21:25
Just create issues here 
https://github.com/zurb/building-blocks/
