### ISSUE TITLE
top-bar-right offset?

### ISSUE THREAD

**Issue by Mellnik** [zurb/foundation-sites#9656] opened 2017-01-16 16:55 UTC
#### How to reproduce this bug:

1. Go to http://foundation.zurb.com/templates-previews-sites-f6/product-page.html
2. Hit F12 and replace the .min.css in head with Version 6.3.0. (https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css)
3. As you can see the top-bar where the "Search" Button is jumps slightly to the right.

#### What should happen:
Stay at the same position?

#### What happened instead:
It positions itself slightly to the right.

Is this a bug or some codebreaking change in Version 6.3.0?
What do I have to change in my project? This is very ugly.
Thanks!

**Comment by kball** [comment] 2017-01-16 18:20
@rafibomb can you take a look at this?

**Comment by Mellnik** [comment] 2017-01-23 11:49
Anything?

**Comment by kball** [comment] 2017-04-18 22:08
@canterberrie can you take a look?

**Comment by webuxr** [comment] 2019-08-15 05:01
@Mellnik I can reproduce and have attached 2 screenshots for reference.

ORIGINAL:
![B7E148E4-7D17-4D5C-9718-E9F53827A91E](https://user-images.githubusercontent.com/1559023/63073328-f6e15580-beed-11e9-948f-68b7d8e3b598.jpeg)

WITH 6.3.0 CSS SWAPPED-IN:
![63DCB326-67F9-4755-BF69-6C4C387E7E6F](https://user-images.githubusercontent.com/1559023/63073329-f6e15580-beed-11e9-82cf-39d94c8c4df6.jpeg)

You can certainly tell there is different CSS providing the rounded-corner search box styling in 6.3.0. But that makes sense because we’re talking about 2, completely different CSS files:

ORIGINAL CSS:
https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css

6.3.0 CSS:
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css

I have a hunch that you may also need to swap-in a matching 6.3.0 JS file from the CDN to have an accurate test. I also didn’t have time to do further testing but wanted to get these screenshots posted sooner than later.

Speaking of testing... @Mellnik: What are you trying to accomplish? Upgrade to 6.3.0 from an earlier release?

Cheers!

**Comment by DanielRuf** [comment] 2019-08-15 05:07
> https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css

This uses a very old normalize.css version.
We support only the latest releases of Foundation Sites.

I think we can close this as this is probably fixed.

6.5.3 is the latest release.

**Closed by DanielRuf** 2019-08-15 05:07 UTC
Labels: Top Bar, scss, 🐛bug
