### ISSUE TITLE
Input text or search is not working in dropdown top bar.

### ISSUE THREAD

**Issue by ve3** [zurb/foundation-sites#8535] opened 2016-04-06 06:05 UTC
Link to demo: [demo](http://yenped.com/pen/test-foudnation-search-topbar/)
I'm also try it in codepen but I think Foundation js does not work properly in codepen. [codepen link](http://codepen.io/anon/pen/EKbOwx)

The problem is I cannot use **space**, **enter** in the input field.

```html
<div class="top-bar">
  <div class="top-bar-title">
    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
      <span class="menu-icon dark" data-toggle></span>
    </span>
    <strong>Site Title</strong>
  </div><!--.top-bar-title-->
  <div id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li><a href="#cat1">Category 1</a></li>
        <li><a href="#cat2">Category 2</a></li>
        <li><a>Search icon</a>
          <ul class="menu">
            <li>
              <form class="search-form">
                <div class="input-group">
                  <input class="input-group-field input-search" type="search" name="q" value="" placeholder="Search...">
                  <div class="input-group-button">
                    <button type="submit" class="button search-button">Search</button>
                  </div>
                </div>
              </form>
            </li>
          </ul>
        </li>
        <li><input type="search" placeholder="Search"></li>
        <li><button type="button" class="button">Search</button></li>
      </ul><!--.menu-->
    </div><!--.top-bar-left-->
  </div><!--#responsive-menu .top-bar-menu-items-container-->
</div><!--.top-bar-->
```

If I remove `data-dropdown-menu` from dropdown menu (`ul`) then it works but I have to use this dropdown menu in real site.
How to fix this?

**Comment by brettsmason** [comment] 2016-04-07 08:23
The Codepen example does work, you just have a typo in the foundation call :smile: 
From a quick investigation you are right though, it looks like the dropdown menu JS may be causing the issue. Hopefully someone else may have a better idea of the cause.

**Comment by ve3** [comment] 2016-04-07 08:40
The codepen example is really not working. Please carefully check again. If it does work the hamburger icon (three horizontal lines) must not appears.
The html and js are same on both codepen and example site.

However, thanks to take care of this bug. :)

**Comment by brettsmason** [comment] 2016-04-07 09:42
@ve3 Sorry I meant the JS in your CodePen wasn't working because of the typo (`$(document).foudnation();`), not that this bug was working in CodePen - sorry for the confusion! You are correct that the bug is present in CodePen when the JS was working correctly.

**Comment by Owlbertz** [comment] 2016-04-10 16:05
Hi,
this issue was already fixed for other components (Reveal I believe...) and is caused by the way the Keyboard util handles the keydown event. I am currently enhancing this util, and the issue is already fixed. I guess I will create the corresponding PR within the next days.

**Comment by kball** [comment] 2016-04-15 00:09
Fixed in https://github.com/zurb/foundation-sites/commit/5a1450dc9b0abc70dc529903e87914c36e065553, will be in 6.2.2

**Closed by kball** 2016-04-15 00:09 UTC
Labels: bug, javascript
