### ISSUE TITLE
[Firefox] Wrong row size rendering

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8155] opened 2016-02-13 05:23 UTC
Hi guys, i have this error with Foundation 6 and Firefox:
![seleccion_120](https://cloud.githubusercontent.com/assets/5034215/13026039/88e5286e-d1e7-11e5-9433-4d430957cfae.png)
I want that web page width going to 1200px, but in firefox i haven't this size, with the new Foundation, but the old version i have these size.

The problem is that in Chromium and Opera i have the correct size:
![seleccion_116](https://cloud.githubusercontent.com/assets/5034215/13026047/b9432628-d1e7-11e5-8c24-eb468fb1a41f.png)

The fonts are render with different wight or size, i don't know, but in Chromium and Opera haven't this bug:
![area de trabajo 1_121](https://cloud.githubusercontent.com/assets/5034215/13026251/d40c8ac4-d1ee-11e5-9ac4-70972c5cf6e4.png)
It's more evident between two Firefox windows:
![area de trabajo 1_122](https://cloud.githubusercontent.com/assets/5034215/13026273/966ff722-d1ef-11e5-893a-e543ac00e476.png)

I don't know why i have this errors, my Firefox version is 44.2. 

Thank you.

**Comment by SalahAdDin** [comment] 2016-03-03 04:33
I have and update, this problem is new but i think that have to see with Firefox and Chrome/Opera:
![seleccion_010](https://cloud.githubusercontent.com/assets/5034215/13484786/db0dc038-e0ce-11e5-8181-2be18ecae7c5.png)
![seleccion_011](https://cloud.githubusercontent.com/assets/5034215/13484790/e0545548-e0ce-11e5-8f07-d5da99a38467.png)

I have a problem with button padding, for fix it i have put a different padding in Firefox (.84em) and Chrome/Opera(.82em), and i don't know why this estrange rendering.

With Foundation 5 i hadn't this problem, and with old Foundation 6 version haven't too.

Thanks.

**Comment by colin-marshall** [comment] 2016-04-27 22:53
@SalahAdDin, I'm closing this issue because we don’t have a reproduceable case to test against. If this is still an issue, please reopen with the info requested here:
https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

**Closed by colin-marshall** 2016-04-27 22:53 UTC
Labels: bug, scss

**Comment by SalahAdDin** [comment] 2016-04-28 03:50
I'll test this issue again soon and if i have again, i'll say you guys, thanks :+1:
