### ISSUE TITLE
Magellan adding `is-active` to `<a>` instead of to `<li>`

### ISSUE THREAD

**Issue by proimage** [zurb/foundation-sites#11014] opened 2018-03-05 14:17 UTC
#### How to reproduce this bug:

1. Apply Magellan code to a regular `.menu`, and have relevant content to scroll through.
2. Open dev-tools and watch the `is-active` class be applied to the `<a>` tags instead of the `<li>` as you scroll.
3. ???
4. Don't profit. :(

#### What should happen:
Either Magellan should add the `is-active` class to the `<li>` menu item, or the Menu component should apply active styles to menu items regardless of whether the `is-active` class is found on the `<li>` or the `<a>`.

#### What happened instead:
Magellan adds `is-active` to the `<a>` element, but the Menu component only styles active menu items when the `is-active` class is applied to the `<li>`.

#### Browser(s) and Device(s) tested on:
Chrome  / Windows 10

#### Foundation Version(s) you are using:
6.4.3

#### Test case link:

https://codepen.io/sandwich/pen/yvWZjo

**Comment by DanielRuf** [comment] 2018-03-05 14:19
Hi, thanks for reporting this. That is already known.

**Comment by DanielRuf** [comment] 2018-03-05 14:20
Also the class should be applied to the link.

See https://github.com/zurb/foundation-sites/issues/10470

**Comment by DanielRuf** [comment] 2018-03-05 14:21
Duplicate of https://github.com/zurb/foundation-sites/issues/10470

**Closed by DanielRuf** 2018-03-05 14:21 UTC
