### ISSUE TITLE
Screen artifact in drilldown menu

### ISSUE THREAD

**Issue by briandanchuk** [zurb/foundation-sites#8177] opened 2016-02-16 19:24 UTC
A vertical line artifact is showing in the operation of the vertical drilldown menu, but only in Mac browsers. It displays after clicking the "back" button on the lowest level of a 3 level menu and disappears when the top menu level is restored. On a desktop Mac  the effect is viewable in the Foundation docs for the drilldown using Firefox (43.04) and Chrome (48). http://foundation.zurb.com/sites/docs/drilldown-menu.html. See attached screenshot. … Javascript issue?
![screen shot 2016-02-16 at 11 22 45 am](https://cloud.githubusercontent.com/assets/17278893/13088088/b8020350-d49f-11e5-9b14-d90a33c0cc55.png)
![screen shot 2016-02-16 at 11 22 58 am](https://cloud.githubusercontent.com/assets/17278893/13088087/b7fddabe-d49f-11e5-926e-a711c7508beb.png)

**Comment by rafibomb** [comment] 2016-02-16 23:00
Yes - it's definite the :focus state adding the outline. This should only be added to the individual links when keyboard is used to navigate. It's in the JS but not sure where.

**Comment by briandanchuk** [comment] 2016-02-17 15:52
A simple work-a-round that I used to get past the issue (in FIrefox and much better in Chrome) is to put a border on the focus state.

.vertical.menu li a{
	color: $black;
	background-color: $primary-color;
}
.vertical.menu * a:focus{ 
		border-style: solid;
		border-color: $primary-color;
		border-width: 1px;
}

This works for a very simple styling of the menu.

**Comment by rafibomb** [comment] 2016-02-17 17:25
Thanks Brian!
Looking for what is causing it, though it seems to be from the JS. Still looking for the cause.

**Comment by kball** [comment] 2016-02-18 01:37
Fixed in https://github.com/zurb/foundation-sites/commit/a85174b69cbe403b887573f1e93283ff7c734544

**Closed by kball** 2016-02-18 01:37 UTC
Labels: bug, javascript
