### ISSUE TITLE
Dropdown Menu: Last Item Dropdown Positioning Bug

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#7251] opened 2015-11-27 03:55 UTC
If the last item in a menu is a dropdown, the dropdown isn't positioned quite right. I'm assuming its shifting left to avoid the edge of the browser, but it's shifting pretty far left.

The dropdown below is the the "Page With Posts" menu item.

![screen shot 2015-11-26 at 8 52 41 pm](https://cloud.githubusercontent.com/assets/6110968/11433797/de7bbc48-947f-11e5-8696-b003c97fd408.png)

**Comment by zurbchris** [comment] 2015-12-01 23:30
@designerno1 @JeremyEnglert 
damn... caused by the border, I suspect. Edge detection just tells the JS if something is clear, not by how much or in what direction. Possibly solvable, albeit temporarily, with an equivalent margin-right on the last link in the dropdown.
That aside, lemme think a for a couple minutes on this one.

**Comment by apcrane** [comment] 2015-12-10 11:18
I am also seeing this issue on the dropdown menu and I am using the latest version (6.0.5). I was just wondering if there was a solution for this yet? 

![dropdown-issue](https://cloud.githubusercontent.com/assets/5689025/11714112/ae5ca01c-9f2f-11e5-81ee-7a568b12c316.PNG)

**Comment by apcrane** [comment] 2015-12-10 11:30
Found a fix that seems to work for me, although haven't fully tested this yet. But I just changed right:100% to right: 0 via an overrides.scss file:

```
.dropdown.menu .is-dropdown-submenu-parent.opens-left .submenu {
  right: 0;
}
```

**Comment by designerno1** [comment] 2015-12-10 11:39
+1
looks good for me
_dropdown-menu.scss
change
```scss
.is-dropdown-submenu-parent.opens-left .submenu {
      left: auto;
      right: 100%;
    }
```
to
```scss
.is-dropdown-submenu-parent.opens-left .submenu {
      left: auto;
      right: 0;
    }
```
solve the problem for me too
don't checked if this effects for example align-right menus

**Comment by nska02** [comment] 2015-12-16 13:57
@apcrane @designerno1 fyi, your fix makes nested dropdown menus overlap each other

<img width="231" alt="screen shot 2015-12-16 at 14 54 19" src="https://cloud.githubusercontent.com/assets/11373782/11842614/f20c187c-a404-11e5-82a0-e66763c85593.png">

**Comment by designerno1** [comment] 2015-12-16 14:33
you are right thinking about it

**Comment by designerno1** [comment] 2015-12-16 14:42
quick and dirty fix
```css
.is-dropdown-submenu-parent.opens-left .submenu {
    left: auto;
    right: 0;
  }
  .is-dropdown-submenu-parent .is-dropdown-submenu-parent.opens-left .submenu {
    left: auto;
    right: 100%;
  }
```

**Comment by apcrane** [comment] 2015-12-17 09:53
Thanks, I've added this in and all ok. Although I don't have any nested dropdowns in the instance I'm using it for.

**Comment by JeremyEnglert** [comment] 2015-12-24 17:23
I saw that this was fixed in 6.1, but I'm still experiencing this issue even after updating to 6.1.1.

**Comment by zurbchris** [comment] 2016-01-08 19:43
It should be fixed now, based on my local stuff and codepen samples. If anyone is still having this issue, please let us know, otherwise I'll close this issue on Monday 1/11.
![screen shot 2016-01-08 at 11 36 51 am](https://cloud.githubusercontent.com/assets/13631168/12207573/42a978d4-b5fc-11e5-9f8f-b27a33a081f8.png)

**Comment by JeremyEnglert** [comment] 2016-01-08 21:48
@zurbchris - I used bower to pull down 6.1.1 and I'm still getting the issue.

Demo link here: http://jointswp.staging.wpengine.com/demo/

**Comment by zurbchris** [comment] 2016-01-08 22:24
Ahhh! Ok, the (less than ideal) solution, though in my mind close to the correct way to handle this is adding the `align-right` class to the dropdown menu. Since it is visually aligned to the right of the page, you need that class, otherwise, the js has to spend a lot more time calculating for collisions and trying to correct it, when you could just add a class and it's done. One caveat to that, which is what makes it less than ideal, is you have to manually add back the `float: left;` to the li's in the menu.

In summation, using the `align-right` class when your menu is visually aligned to the right of the viewport is the answer, and then to maintain the order floating the li's left. I know there's a way to do this properly with the sass functions we have, and conditionally add the float direction based on ltr/rtl, but that will have to wait for a patch.

Here's a screencap of your demo page after I fiddled with it, hopefully that's what you're looking for. 
![screen shot 2016-01-08 at 2 19 51 pm](https://cloud.githubusercontent.com/assets/13631168/12211035/427a91c4-b613-11e5-987f-28a7c67db1ca.png)

**Comment by Baedda** [comment] 2016-01-19 10:56
I am using Foundation 6.1.1 via bower and have the same issue. As many people here have written before the following code (at the comment) can fix the issue:

```scss
.menu {
    @include menu-base;
    @include menu-direction(vertical);
    @include breakpoint(large) {
        @include menu-direction(horizontal);
    }
    > .is-dropdown-submenu-parent {
        > a {
            color: $black;
            font: {
                size: $nav-font-size;
            }
        }
        &:hover {
            background: {
                color: $black;
            }
            > a {
                color: $white;
                &:hover,
                &:focus {
                    color: $nav-font-hover-color;
                }
            }
        }
        &.opens-left {
            > .submenu {
                // Foundation Bugfix
                // https://github.com/zurb/foundation-sites/issues/7251
                right: 0 !important;
            }
        }
    }
}
```

It would be really nice to see a fix in the core here. I dont want to add the align-right class manually.

**Comment by Baedda** [comment] 2016-01-25 18:09
I have updated to 6.1.2 today and now there is another bug with the (new?) class called '.opens-inner'. I have not figured out whats wrong yet, but there is a 'top: 100%' that is inherited and positions a flyout of my navigation at a wrong position.

**Comment by zerodahero** [comment] 2016-01-26 16:31
I believe this is related. Since the release of 6.1.2, everything is working much better with the dropdown menu, but the positioning is still an issue on the far edge of the top-bar in a page. I found a dirty fix based on some of the comments above for the issue of the menu appearing directly under--which becomes outside the window.
![dropdown-6 1 2-issue7251](https://cloud.githubusercontent.com/assets/6423168/12586856/8ebe7746-c417-11e5-9050-930a32437e29.png)

adding into the sass

```sass
.top-bar .dropdown.menu .submenu{
    left: auto !important;
    right: 0 !important;
}
```
yields:
![dropdown-6 1 2-issue7251-dirtyfix](https://cloud.githubusercontent.com/assets/6423168/12586903/b361e72c-c417-11e5-9ebe-33ec9cabaf2d.png)

None of the align right things seemed to work in this case. Hope this helps with a permanent fix!

**Comment by kball** [comment] 2016-02-16 17:26
I believe this to actually be a scss bug... the edge detection is just changing the class of the menu item to 'opens-left', which then has broken scss.

**Comment by kball** [comment] 2016-02-17 17:00
I believe this is related to #7251.  Taking it back - tweaking 'opens-left' in isolation is unlikely to be enough, need to look at the menu scss holistically

**Comment by gakimball** [comment] 2016-02-23 19:36
Fixed via #8200. 6.2 will be out Friday!

**Closed by gakimball** 2016-02-23 19:36 UTC
Labels: bug, scss

**Comment by JTallis** [comment] 2016-03-29 01:52
I'm having an issue with positioning. Oddly enough the second sub-menu would overlap the first sub-menu. See http://codepen.io/anon/pen/ZWJzmg for an example of this.

I added the "quick and dirty fix" posted above to fix this and this can be seen here: http://codepen.io/anon/pen/vGJBzZ

In both codepens, hover over menu item "One" and then "B".

In my opinion, a sub-menu should be in-line with it's parent menu item and not below it. Not only that but if the menu is unable to open to the right, it will do so and then reposition itself. This is undesirable as it's "flashy".

I can temporarily fix this by adding ".opens-left" but this seems to get removed after resizing the browser so it's not a permanent solution.

In both codepens, you can see that it is using foundation 6.2.0.

**Comment by calderJamNet** [comment] 2016-09-16 07:24
I'm having this issue right now, is it supposed to be fixed by now?
