### ISSUE TITLE
[Tooltip] won't show up in reveal

### ISSUE THREAD

**Issue by amagdic** [zurb/foundation-sites#9466] opened 2016-12-07 11:00 UTC
if u use .tooltip in reveal, tip wont show

I manage to fix this with this CSS fix

body.is-reveal-open .tooltip {
    z-index: 10;
}

**Comment by ncoden** [comment] 2016-12-07 11:39
Codepen: https://codepen.io/ncoden/pen/PbeaRg

![Preview](https://cloud.githubusercontent.com/assets/9939075/20965756/83d333cc-bc77-11e6-9d73-01fe211818ab.gif)

---

Duplicate of: #9122 
Fixed in: #9165
Fix released in [v6.3.0-rc1](https://github.com/zurb/foundation-sites/releases/tag/v6.3.0-rc1)

**Comment by ncoden** [comment] 2016-12-08 11:39
Hmmm. I didn't found the Gihub issue board. So a tweet will do. https://twitter.com/ncodn/status/806823450782400512

**Comment by colin-marshall** [comment] 2018-02-02 04:07
@ncoden this one good to close?

**Closed** 2018-02-02 22:57 UTC
Labels: Reveal, Tooltip, bug, duplicate
