### ISSUE TITLE
Sticky Menu: Rescaling a responsive web site 

### ISSUE THREAD

**Issue by pymoza** [zurb/foundation-sites#8114] opened 2016-02-08 18:54 UTC
I have a problem with resizing a sticked menu when the menu height change. The height is not recalculated.  

It is the version 6.1.2 of Foundation.

Here's the code rendered : 

```
<header class="header" role="banner">
<div class="header-sticky sticky-container" data-sticky-container="" style="height: 253px;">
   <div class="sticky is-anchored is-at-top" data-sticky="uvsgyu-sticky" data-sticky-on="medium" data-margin-top="0" data-margin-bottom="0" data-btm-anchor="root:bottom" data-resize="owjmvm-sticky" style="max-width: 1100px; margin-top: 0px; top: 0px; bottom: 652px;" data-events="resize">
      <div class="top-bar" id="top-bar-menu"></div>
   </div>
</div>
</header>
```

Thank You!

**Comment by colin-marshall** [comment] 2016-04-28 02:08
@pymoza I'm closing this issue because we don’t have a reproducible case to test against. If this is still an issue, please reopen with the info requested here:
https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

Thanks!

**Closed by colin-marshall** 2016-04-28 02:08 UTC
Labels: bug, javascript
