### ISSUE TITLE
Foundation.MediaQuery.current gives unexpected result on "small" screens.

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#9108] opened 2016-08-14 17:02 UTC
**How can we reproduce this bug?**
Enter "Foundation.MediaQuery.current" in your browser's development console whilst emulating a small screen device or using a "small" viewport; the result will be "erif,"small".

**What did you expect to happen?**
I expected the result to be "small" as the variable responds with "medium" and "large" on medium and large displays/viewports, respectively.

**What happened instead?**
Given the aforementioned conditions, the console returns ""erif,"small"". 

**Example**
Go to http://foundation.zurb.com, open the javascript console, and enter "Foundation.MediaQuery.current" whilst using a small viewport. The result will be  ""erif,"small"".

**EDIT**: To clarify, this occurred with FF on OSX.

**Comment by Deckluhm** [comment] 2016-08-16 10:38
I couldn't reproduce the bug you describe.

Tested with these browsers:
- Edge
- Firefox (Linux)
- Chromium (Linux)
- Opera (Linux)

**Comment by pine3ree** [comment] 2016-08-16 12:03
same here, i get "small" with chrome, chromium, opera, firefox (all on linux) even with device emulation provided by chromium

**Comment by paxperscientiam** [comment] 2016-08-16 14:23
Sorry, should have specified user agent.
I'm using FF 47 on OSX 10.11.

I did just check Chrome 51 on same operating system -- the result is the expected "small." Interesting.

Maybe someone else can check FF on OSX?

**Comment by danielnass** [comment] 2016-08-16 23:26
Tested with BrowserStack in MacOS Sierra with Firefox 47, 48 & 49
Tested with BrowserStack in MacOS El Captain with Firefox 47, 48 & 49

Everything's ok here.

Can you provide more information?

**Comment by paxperscientiam** [comment] 2016-08-17 01:17
Here is a [screenshot](https://www.dropbox.com/s/cflc2fnkij12h96/Screenshot%202016-08-16%2021.10.06.png?dl=0).

Please note, this occurs regardless of whether or not extensions are enabled.

**Comment by pine3ree** [comment] 2016-08-17 12:09
@paxperscientiam Just to exclude a developer tools bug, can you download locally the dist http://foundation.zurb.com/sites/download.html  and add a raw alert(Foundation.MediaQuery.current) on window resize?

**Comment by paxperscientiam** [comment] 2016-08-17 14:27
@pine3ree Good day,

Your thought about a possible bug in the dev tools (previously used built-in), gave me the idea to try Firebug. The result was the same.

Then, I tried as you suggested; again, the result is the same.

[one](https://www.dropbox.com/s/1rdkmhgzs5ms6rp/Screenshot%202016-08-17%2010.20.41.png?dl=0)
[two](https://www.dropbox.com/s/nsbt15f3rctwel3/Screenshot%202016-08-17%2010.24.19.png?dl=0)

**Comment by pine3ree** [comment] 2016-08-17 15:22
@paxperscientiam 
Hello, i looked at foundation.util.mediaQuery.js.

what you are reporting looks like a truncated `serif` or `sans-serif` keyword.
From the code i see that a specila head meta element is used
`<meta class="foundation-mq">` (you can find it via dev tools / firebug).
the foundation utility is using the css property "font-family" of this element to extract the current media query name (not sure why it's using that property), in my case for example, via dev tools, i get
`.foundation-mq {
    font-family: "small=0em&medium=40em&large=64em&xlarge=75em&xxlarge=90em";
}`

i guess that something goes wrong when parsing the font-family value, maybe the body font family value is prepended to that as well.

**Comment by diniscorreia** [comment] 2016-09-19 12:44
@paxperscientiam,

I was having the same problem and I think I figured it out (thanks to @pine3ree input on how it works). 

In my case, I'm using inlined critical CSS in the `<head>` and loading the full CSS asynchronously - and `.foundation-mq` wasn't included on my critical CSS (Foundation probably needs to access the font-family when it loads and the async CSS request might not be fast enough).

**Comment by paxperscientiam** [comment] 2016-09-27 20:55
@diniscorreia 

Interesting. I'm not loading my CSS asynchronously -- but I am loading my JS asynchronously. I'll check to see if switching to synchronous loading does away with it.

Did you also only observe this behavior in Firefox (on Mac)?

**Comment by kball** [comment] 2016-09-27 23:48
What's interesting to me is that you're seeing this on the foundation website... so far I'm totally unable to reproduce it.  

That being said, the async idea is a good one to pursue... MediaQuery is initialized when you call $(document).foundation(), so if you can defer that until your css is loaded you should work around any issues...

Another thing we might look into if you don't want to wait for all of this to get the JS going is making MediaQuery cleanly re-initializable.

**Comment by DanielRuf** [comment] 2018-03-05 22:57
Not reproducible in current Chrome stable.

**Comment by colin-marshall** [comment] 2018-03-06 20:46
@paxperscientiam any update on this one?

**Comment by DanielRuf** [comment] 2019-02-27 21:30
Closing as we did not receive any fufther feedback.

**Closed by DanielRuf** 2019-02-27 21:30 UTC
Labels: Media Query
