### ISSUE TITLE
[Orbit] Sample code does not work with raw install of Foundation 6

### ISSUE THREAD

**Issue by eduardom** [zurb/foundation-sites#7296] opened 2015-11-29 17:33 UTC
**How can we reproduce this bug?**

1. Step one
Get a blank copy of Foundation 6 complete

2. Step two
Copy and paste the Orbit Carousel sample code from http://foundation.zurb.com/sites/docs/orbit.html inside a row in the HTML to test it.

3. Step three
Navigate through slides. 

**What did you expect to happen?**
Navigation on slides to work.

**What happened instead?**
After you navigate to the first slide the carousel stops working.

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by xfifix** [comment] 2015-11-30 09:01
make useMui to false in the js file

**Comment by Knight-Yoshi** [comment] 2015-12-01 08:24
You need to add the Motion UI CSS, either load the .css file in the head or bundle it in SCSS. http://foundation.zurb.com/sites/docs/motion-ui.html

**Comment by samvloeberghs** [comment] 2015-12-03 14:55
was this even tested properly? Cause indeed it doesn't work out of the box as it should.

**Comment by Knight-Yoshi** [comment] 2015-12-03 17:19
@samvloeberghs As I said, you need to add the Motion UI CSS. I was also having issues with it not cycling through the slides. Once I added the MUI CSS (via SCSS) it worked just fine.

**Comment by samvloeberghs** [comment] 2015-12-04 08:06
I can confirm that installing the motion ui framework made it work.

**Comment by marysmech** [comment] 2015-12-09 14:03
I have included motion ui css downloaded from http://zurb.com/playground/motion-ui and it works. Thank you!

**Comment by zurbchris** [comment] 2015-12-10 18:17
Closing this as the issue seems resolved. Thanks everyone, sorry for the confusion about MUI.

**Closed by zurbchris** 2015-12-10 18:17 UTC
Labels: bug, javascript

**Comment by seanmavley** [comment] 2016-04-30 00:10
Yet, and yet, it never got added to the docs? I can't find the mention of adding the motion ui css to the orbit slider, at least not on the orbit slider:
http://foundation.zurb.com/sites/docs/orbit.html

**Comment by seanmavley** [comment] 2016-04-30 00:44
Added clear indication on orbit slider page that motion-ui css file is required for proper working of orbit slider:
https://github.com/zurb/foundation-sites/pull/8710

**Comment by abrahamvelazquez** [comment] 2017-06-12 05:53
Thanks @seanmavley, but since you can use `data-use-m-u-i="false"` and get it work out of the box, I'd suggest switching to that as the default, then mentioning that advanced functionality requires Motion UI.
