### ISSUE TITLE
Nav menu bounces, any solution ?

### ISSUE THREAD

**Issue by kultz** [zurb/foundation-sites#9147] opened 2016-08-31 10:10 UTC
Hi there,

Look at this video: https://youtu.be/HCeT3tSSVtg

Navigation menu bounces on page change if you see video it happens so fast and nav bounces about 0.2ms and then would be fit , seems like js loads a bit slowly, any solution how to solve this ?

**Comment by pine3ree** [comment] 2016-08-31 20:43
Hello @kultz
can You provide a codepen/jsfiddle example for that?
did you try this simple tecnique: http://foundation.zurb.com/sites/docs/responsive-navigation.html#preventing-fouc

i encountered similar behaviours with sticky navigation and body final padding top. Everything gets right after all the images in the page are loaded. I believe it could be what's happening to you.

kind regards
maks feltrin

**Comment by kultz** [comment] 2016-08-31 21:27
Hi @pine3ree 
The solution you've provided didn't work out.I removed the responsive toggle and still the same.
I recently started to migrate from Bootstrap to Foundation, I've not had this sort of problems with BS while BS size is about twice of Foundation and it's slower to load up.

**Comment by pine3ree** [comment] 2016-08-31 22:09
Yes, I agree, there are still issues that need to be corrected.
Still, you should add a codepen/jsfiddle example so that someone reading your report can trey and help you solving the bug.

**Comment by markadrake** [comment] 2016-09-16 05:51
@kultz still working on this bug? Did you have any time to reproduce this bug in CodePen or JSFiddle?

**Comment by kultz** [comment] 2016-09-16 06:40
@markadrake Actually i fixed that by using of:
```
    .no-js [data-responsive-toggle]{
    display:none;
        }
```

**Comment by brettsmason** [comment] 2016-09-29 11:40
It looks like you got this sorted so I'll close this 😄

**Closed by brettsmason** 2016-09-29 11:40 UTC
