### ISSUE TITLE
[Tooltips] Bug with positioning tooltip on first hover on right site of a page (Foundation 6.1.2.)

### ISSUE THREAD

**Issue by rianne-o** [zurb/foundation-sites#8190] opened 2016-02-18 10:38 UTC
Hi,

I've discovered a bug with the Foundation 6.1.2. tooltip.

Elements positioned on the right side of the page with the tooltip attach to them, cause strange behaviour. The first time you hover over the element, the position of the tooltip isn't centered above or below the element, but more to the left. When you hover for the second time, the position of the tooltip is as expected.

The more your element is positioned to the right of the page, the more the tooltip gets positioned to the bottom or top left of the element.

Not sure if browsers matter in this situation, but just in case:
Chrome 48.0.2564.109 (64-bit)
Firefox 44.0.2

Here is a screenshot of the situation and I also created a Fiddle.
![scr_foundation_6_tooltip](https://cloud.githubusercontent.com/assets/6838453/13140623/6ed61bfe-d633-11e5-8a99-f4fcac10d80c.jpg)

https://jsfiddle.net/rianne_o/oagy66s8/3/

Hopefully the information I've provided you with gives a good impression of the bug I'm experiencing.

Thanks in advance!

**Comment by Silvester20** [comment] 2016-02-18 13:02
And again a bug in the tooltips, there are more but it seems they are not planning to fix this for 6.2.

https://github.com/zurb/foundation-sites/issues/8144

**Comment by gakimball** [comment] 2016-02-18 16:51
I saw the same behavior with bottom-anchored tooltips in IE9–11 while QAing yesterday, although it was off by like 100 pixels.

**Comment by rianne-o** [comment] 2016-06-02 14:44
@gakimball could you update me about the status of this issue?

**Comment by andycochran** [comment] 2016-06-30 17:01
I can't reproduce this. And the jsfiddle provided works for me. @rianne-o, is this still an issue for you in v6.2.3?

**Comment by Silvester20** [comment] 2016-06-30 21:30
I can confirm the bug is still there in v6.2.3.

I posted a CSS solution at https://github.com/zurb/foundation-sites/issues/8929

**Comment by rianne-o** [comment] 2016-07-01 08:38
I confirm this as well. Updated jsFiddle to Foundation.css 6.2.3 and Foundation.js 6.2.3.

As you can see in the screenshot below, first time hovering this doesn't position the tooltip in the middle
![image](https://cloud.githubusercontent.com/assets/6838453/16516312/b1e6ac4e-3f77-11e6-94e2-7b9eb9ca58df.png)
Second time hovering, is does
![image](https://cloud.githubusercontent.com/assets/6838453/16516333/cd4bb092-3f77-11e6-9a5c-c07199024b56.png)

Tested in Chrome 51.0.2704.103 (64-bit) on a 1920x1280 screen with Foundation 6.2.3.

**Comment by markgibbons25** [comment] 2017-02-13 00:44
Any update on when this will be fixed? Seems to be still an issue in 6.2.4.

**Comment by JeremyEnglert** [comment] 2018-01-27 18:42
It looks like the behavior of tooltips has changed dramatically and this is no longer an issue.

**Closed by JeremyEnglert** 2018-01-27 18:42 UTC
Labels: bug, javascript

**Comment by IamManchanda** [comment] 2018-01-28 19:29
@rianne-o @ghost @markgibbons25 

Though not sure but i think this was fixed in #10053 
But if you still facing any issues ... let us know and we would be happy to reopen it!

**Comment by JanisJenzens** [comment] 2020-07-30 08:26
This bug is still present in 6.6.3.
With a little bit of testing I found out that it happens if the element is positioned not inline and its parent element does not have a static width.
The more towards the right side its positioned the bigger the offset.

Its almost as if the position of the element is read by the tooltip script before the parent has calculated its own width.

For example if the element is "position: absolute" and "right: 0" or if its the second child in a flex parent that is set to "justify-items: space-between" and the parent is set to "width: 100%"

**Comment by DanielRuf** [comment] 2020-07-30 08:56
@JanisJenzens please open a new issue with all relevant details so we can check this in detail.

**Comment by Kloptoe** [comment] 2021-07-03 19:05
This issue still occurs in 6.6.3

**Comment by DanielRuf** [comment] 2021-07-03 19:22
@Kloptoe see https://github.com/foundation/foundation-sites/issues/12118
