### ISSUE TITLE
flex-video doesn't seem to work on Microsoft Edge

### ISSUE THREAD

**Issue by akshaybharwani** [zurb/foundation-sites#8195] opened 2016-02-18 16:24 UTC
I wanted a responsive Google Embed Maps for my website. And I read on SO that I can achieve that if I put the `<iframe>` inside a div with a class of `flex-video`. And it works flawlessly in Chrome and Firefox. But when I tried the website on Edge, the Maps doesn't appear. There are no errors but just that nothing is visible. If I remove the flex-video div around the iframe, map is visible on both the browsers but when I include it, map isn't visible.

**Comment by andycochran** [comment] 2016-02-18 18:00
Hmm… Which version of IE? 

It could be a `DOCTYPE` issue. An `iframe` in IE9 inherits the `DOCTYPE` of its parent when it's in quirks mode. Try adding this to the `head` of your markup. 

```html
<meta http-equiv="X-UA-Compatible" content="IE=8" />
```

Can you reproduce this in a codepin?

**Comment by akshaybharwani** [comment] 2016-02-18 21:47
It contains the exact markup and styles as my website: http://jsfiddle.net/eu2ojocL/3/
And I have corrected the issue as I can see the maps working on IE. But still not on Edge. The JSFiddle here shows weird height and I don't know why. I tried specifying height to both row, column and container but the problem is there. And the `<iframe>` also has a specified height, but the div is stuck in some weird height I think.

**Comment by brettsmason** [comment] 2016-02-19 13:59
It looks like this might be related to `display: flex;` that is added to the `.about-section`. If you remove that it seems to work OK for me in Edge. Not sure on what would cause this though, I'm pretty new to flexbox.

**Comment by akshaybharwani** [comment] 2016-02-19 14:09
@brettsmason Yeah, that does solve the problem. Thank you. But still I would like to know the reason behind this.

**Comment by slavanga** [comment] 2016-02-20 18:54
I just ran into the same issue. The intrinsic padding trick doesn't work consistently within a flexbox parent.
The solution is to move the `height` and `padding-bottom` to a pseudo element.

Here is a working demo: http://jsfiddle.net/eu2ojocL/10/
This new method seems to work with and without the flexbox parent but some more browser testing is required. You can read more details on [stackoverflow](http://stackoverflow.com/a/28076430).

**Comment by andycochran** [comment] 2016-02-20 19:07
That's a good idea, @slavanga. I recently used the zero-heigh/padding-bottom trick on a pseudo element for a responsive background image 'cause I needed the actual element to act as a container. Worked really well. Didn't consider it for this case. I think this bug warrants changing the Flex Video method to use a pseudo element. Maybe I should consider this in the PR I'm working on for refactoring Flex Video (#8199).

**Comment by kball** [comment] 2016-04-27 20:31
Is this still an issue?  Did we determine it is a user css issue, or something that should get handled by foundation?

**Comment by brettsmason** [comment] 2016-04-27 21:06
From looking back over this the issue is adding `display: flex;` to a parent container causes `flex-video` not to display correctly. I'm not familiar with flexbox but @andycochran was what you mentioned above still valid? I know you were looking at flex video.

**Comment by andycochran** [comment] 2016-04-27 22:15
I think this was probably an edge case. Closing. We can reopen if someone runs into Edge + Responsive Embed issues again.

**Closed by andycochran** 2016-04-27 22:15 UTC
Labels: bug, scss
